import { cloneFreeze, isSafeRecord } from "./factory-constitution";
import { isFactoryMode } from "./factory-operating-mode";
import { isFactoryStage } from "./factory-stage";
export const CAPABILITY_ACTIVATION_STATES = ["REGISTERED", "INACTIVE", "QUARANTINED", "DENIED"] as const;
export const CAPABILITY_TYPES = ["INSPECTION", "REVIEW", "REGISTRY"] as const;
export type CapabilityActivationState = (typeof CAPABILITY_ACTIVATION_STATES)[number];
export type FactoryCapabilityManifest = Readonly<Record<string, unknown>>;
export const freezeCapabilityManifest = (value: Record<string, unknown>): FactoryCapabilityManifest => cloneFreeze(value);
const ISO = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{3})?Z$/;
const PATH = /^[^\u0000-\u001f\\\u007f\u200b-\u200f\u202a-\u202e\u2066-\u2069]+$/;
const DISALLOWED_PATH_VARIANTS = /[\\\u2215\u2216\u2044\u29f8\u29f9\uFF3C\uFF0F\uFE68]/u;
const validPath = (path: unknown): path is string => typeof path === "string" && path.length > 0 && path.normalize("NFC") === path && PATH.test(path) && !path.startsWith("/") && !/^[A-Za-z]:/.test(path) && !path.startsWith("//") && !DISALLOWED_PATH_VARIANTS.test(path) && !/%(?:2f|5c|2e)/i.test(path) && !path.endsWith("/") && !path.split("/").some((part) => part === "" || part === "." || part === ".." || /[ .]$/.test(part));
const scopesConflict = (required: readonly string[], prohibited: readonly string[]): boolean => required.some((scope) => prohibited.some((other) => scope === other || scope.startsWith(`${other}/`) || other.startsWith(`${scope}/`)));
const validBudget = (value: unknown): boolean => isSafeRecord(value) && Object.keys(value).length > 0 && Object.values(value).every((item) => typeof item === "number" && Number.isFinite(item) && item >= 0 && item <= 1_000_000_000);
export const isValidCapabilityManifest = (input: unknown): boolean => {
  if (!isSafeRecord(input)) return false;
  const value = input as Record<string, unknown>;
  const required = ["capabilityId", "capabilityType", "owner", "purpose", "version", "contractVersion", "stage", "registrationState", "activationState", "operatingMode", "readWrite", "localRemote", "networkRequirement", "allowedDataClasses", "requiredScopes", "prohibitedScopes", "budgets", "expiresAt", "evidenceRequirements", "reviewerRequirements", "disablePath", "rollbackPath", "quarantinePath", "providerClassification", "provenance", "licensingClassification", "reversibilityClass", "riskClass", "statusReason", "lastReviewedAt", "evidenceFreshnessPolicy", "createsAuthority", "executesActions", "mutatesState"] as const;
  if (Object.keys(value).length !== required.length || Object.keys(value).some((key) => !required.includes(key as never))) return false;
  const textFields = ["capabilityId", "capabilityType", "owner", "purpose", "version", "contractVersion", "providerClassification", "provenance", "licensingClassification", "reversibilityClass", "riskClass", "statusReason", "evidenceFreshnessPolicy"];
  if (textFields.some((key) => typeof value[key] !== "string" || String(value[key]).trim() === "")) return false;
  if (!CAPABILITY_TYPES.includes(value.capabilityType as never)) return false;
  if (value.stage !== "F1" || !isFactoryMode(value.operatingMode) || !["INACTIVE", "QUARANTINED", "DENIED"].includes(String(value.activationState)) || value.registrationState !== "REGISTERED") return false;
  if (value.readWrite !== "READ_ONLY" || value.localRemote !== "LOCAL" || value.networkRequirement !== "DENIED") return false;
  if (value.createsAuthority !== false || value.executesActions !== false || value.mutatesState !== false) return false;
  if (!Array.isArray(value.allowedDataClasses) || !Array.isArray(value.requiredScopes) || !Array.isArray(value.prohibitedScopes) || !Array.isArray(value.evidenceRequirements) || !Array.isArray(value.reviewerRequirements) || value.prohibitedScopes.length === 0 || value.evidenceRequirements.length === 0 || value.reviewerRequirements.length === 0) return false;
  if (![value.allowedDataClasses, value.requiredScopes, value.prohibitedScopes, value.evidenceRequirements, value.reviewerRequirements].every((items) => (items as unknown[]).every((item) => typeof item === "string" && item.trim() !== "") && new Set(items as unknown[]).size === (items as unknown[]).length)) return false;
  if (!(value.requiredScopes as unknown[]).every(validPath) || !(value.prohibitedScopes as unknown[]).every(validPath) || scopesConflict(value.requiredScopes as string[], value.prohibitedScopes as string[])) return false;
  if (!validPath(value.disablePath) || !validPath(value.rollbackPath) || !validPath(value.quarantinePath)) return false;
  if (!["DENIED", "LOCAL_ONLY"].includes(String(value.networkRequirement)) || !["READ_ONLY"].includes(String(value.readWrite)) || !["LOCAL"].includes(String(value.localRemote))) return false;
  return typeof value.expiresAt === "string" && ISO.test(value.expiresAt) && !Number.isNaN(Date.parse(value.expiresAt)) && typeof value.lastReviewedAt === "string" && ISO.test(value.lastReviewedAt) && !Number.isNaN(Date.parse(value.lastReviewedAt)) && Date.parse(value.expiresAt) > Date.parse(value.lastReviewedAt) && validBudget(value.budgets) && ["INTERNAL", "OSS_APPROVED"].includes(String(value.licensingClassification)) && ["REVERSIBLE", "REQUIRES_OWNER_RECOVERY"].includes(String(value.reversibilityClass)) && ["LOW", "MEDIUM", "HIGH"].includes(String(value.riskClass));
};
