import { cloneFreeze, isSafeRecord } from "./factory-constitution";
import { isFactoryMode, type FactoryOperatingMode } from "./factory-operating-mode";
import { isFactoryStage, type FactoryStage } from "./factory-stage";
export type FactoryTaskEnvelope = Readonly<Record<string, unknown>>;
export const freezeTaskEnvelope = (value: Record<string, unknown>): FactoryTaskEnvelope => cloneFreeze(value);
const ISO = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{3})?Z$/;
const REQUIRED = ["taskId", "taskType", "purpose", "requestedBy", "authorizedBy", "authorityClassification", "repositoryId", "repositoryVisibilityClassification", "baselineCommit", "expectedBranch", "permittedPaths", "prohibitedPaths", "permittedCommandClasses", "prohibitedCommandClasses", "networkPolicy", "dataPolicy", "secretPolicy", "providerPolicy", "resourceBudget", "modelBudget", "timeBudget", "outputClasses", "evidenceRequirements", "reviewerRequirements", "expiresAt", "cancellationState", "killSwitchState", "operatingMode", "factoryStage", "policyVersion", "schemaVersion", "provenance", "continuityGapPolicy", "stopConditions", "mutationAllowed", "createsAuthority", "networkAllowed", "productionSecretsAllowed", "productionDataAllowed", "householdPrivateDataAllowed", "gitWriteAllowed", "remoteWriteAllowed", "runtimeActivationAllowed"] as const;
const PATH = /^[^\u0000-\u001f\\\u007f\u200b-\u200f\u202a-\u202e\u2060\u2066-\u2069\ufeff]+$/;
const DISALLOWED_PATH_VARIANTS = /[\\\u2215\u2216\u2044\u29f8\u29f9\uFF3C\uFF0F\uFE68]/u;
const validPath = (path: unknown): path is string => typeof path === "string" && path.length > 0 && path.normalize("NFC") === path && PATH.test(path) && !path.startsWith("/") && !/^[A-Za-z]:/.test(path) && !path.startsWith("//") && !DISALLOWED_PATH_VARIANTS.test(path) && !/%(?:2f|5c|2e)/i.test(path) && !path.endsWith("/") && !path.split("/").some((segment) => segment === "" || segment === "." || segment === ".." || /[ .]$/.test(segment));
const unique = (values: readonly unknown[]): boolean => new Set(values).size === values.length;
const boundedBudget = (value: unknown): boolean => isSafeRecord(value) && Object.keys(value).length > 0 && Object.values(value).every((item) => typeof item === "number" && Number.isFinite(item) && item >= 0 && item <= 1_000_000_000);
export const isValidTaskEnvelope = (input: unknown): boolean => {
  if (!isSafeRecord(input)) return false;
  const value = input as Record<string, unknown>;
  if (Object.keys(value).length !== REQUIRED.length || Object.keys(value).some((key) => !REQUIRED.includes(key as never))) return false;
  if (REQUIRED.filter((key) => !["resourceBudget", "modelBudget", "timeBudget", "permittedPaths", "prohibitedPaths", "permittedCommandClasses", "prohibitedCommandClasses", "outputClasses", "evidenceRequirements", "reviewerRequirements", "stopConditions", "mutationAllowed", "createsAuthority", "networkAllowed", "productionSecretsAllowed", "productionDataAllowed", "householdPrivateDataAllowed", "gitWriteAllowed", "remoteWriteAllowed", "runtimeActivationAllowed"].includes(key)).some((key) => typeof value[key] !== "string" || String(value[key]).trim() === "")) return false;
  if (!/^[a-zA-Z0-9._:-]+$/.test(String(value.taskId)) || !/^[0-9a-f]{40}$/.test(String(value.baselineCommit))) return false;
  if (!ISO.test(String(value.expiresAt)) || Number.isNaN(Date.parse(String(value.expiresAt))) || Date.parse(String(value.expiresAt)) <= 0) return false;
  const arrays = ["permittedPaths", "prohibitedPaths", "permittedCommandClasses", "prohibitedCommandClasses", "outputClasses", "evidenceRequirements", "reviewerRequirements", "stopConditions"] as const;
  if (arrays.some((key) => !Array.isArray(value[key]) || (value[key] as unknown[]).some((item) => typeof item !== "string"))) return false;
  const permitted = value.permittedPaths as string[]; const prohibited = value.prohibitedPaths as string[];
  if (permitted.length === 0 || ![...permitted, ...prohibited].every(validPath) || !unique(permitted) || !unique(prohibited) || permitted.some((path, index) => permitted.some((other, otherIndex) => index !== otherIndex && path.startsWith(`${other}/`))) || permitted.some((path) => prohibited.some((other) => path === other || path.startsWith(`${other}/`)))) return false;
  if (["outputClasses", "evidenceRequirements", "reviewerRequirements", "stopConditions"].some((key) => (value[key] as unknown[]).length === 0)) return false;
  if (arrays.some((key) => !(value[key] as unknown[]).every((item) => String(item).trim() !== "") || !unique(value[key] as unknown[]))) return false;
  if (value.requestedBy !== "collaborator" || value.authorizedBy !== "Rahul" || value.authorityClassification !== "PROPOSAL_ONLY" || value.repositoryId !== "test831495/onyx-alpha1-transfer" || value.repositoryVisibilityClassification !== "PUBLIC" || !/^[A-Za-z0-9._/-]+$/.test(String(value.expectedBranch)) || !["DENY", "LOCAL_ONLY"].includes(String(value.networkPolicy)) || value.dataPolicy !== "REPOSITORY_METADATA_ONLY" || value.secretPolicy !== "PROHIBIT" || value.providerPolicy !== "NONE" || value.continuityGapPolicy !== "TYPED_GAPS" || !boundedBudget(value.resourceBudget) || !boundedBudget(value.modelBudget) || !boundedBudget(value.timeBudget)) return false;
  if (!isFactoryMode(value.operatingMode) || !isFactoryStage(value.factoryStage)) return false;
  const falseFlags = ["mutationAllowed", "createsAuthority", "networkAllowed", "productionSecretsAllowed", "productionDataAllowed", "householdPrivateDataAllowed", "gitWriteAllowed", "remoteWriteAllowed", "runtimeActivationAllowed"];
  if (falseFlags.some((key) => value[key] !== false)) return false;
  return (value.cancellationState === "ACTIVE" || value.cancellationState === "CANCELLED") && (value.killSwitchState === "ARMED" || value.killSwitchState === "ENGAGED");
};
