import { describe, expect, it } from "vitest";
import { createCapabilityRegistry, registerCapability } from "@onyx/train-b-capability-foundation";
import { bindCapability, createConnectorRegistry } from "../src/index";

const definition = (overrides: Record<string, unknown> = {}) => ({ id: "calendar.events.read", version: "1.0.0", label: "Calendar read", description: "Read calendar", domain: "calendar", operations: ["READ"], riskClass: "LOW", inputContractIds: [], outputContractIds: ["calendar.output"], dataClasses: ["CALENDAR_EVENT"], freshnessRequirement: "CURRENT", sourceAttributionRequired: true, costClass: "LOW", dependencies: [], conflicts: [], lifecycleState: "ACTIVE", runtimeEnabled: true, owner: "Rahul", purpose: "read-only", providerNeutralImplementation: true, ...overrides });

describe("capability binding assurance", () => {
  it("binds a known Package 1 capability", () => { const registry = createCapabilityRegistry(); registerCapability(registry, definition() as never); expect(bindCapability(registry, "calendar.events.read", ["READ"]).capabilityId).toBe("calendar.events.read"); });
  it("rejects unknown capabilities", () => expect(() => bindCapability(createCapabilityRegistry(), "missing.capability", ["READ"])).toThrow());
  it("rejects disabled capabilities", () => { const registry = createCapabilityRegistry(); registerCapability(registry, definition({ lifecycleState: "DISABLED" }) as never); expect(() => bindCapability(registry, "calendar.events.read", ["READ"])).toThrow(); });
  it("accepts read-only operations", () => { const registry = createCapabilityRegistry(); registerCapability(registry, definition() as never); expect(bindCapability(registry, "calendar.events.read", ["READ"]).operations).toEqual(["READ"]); });
  it.each(["WRITE", "EXECUTION"] as const)("rejects %s under Train B baseline", (operation) => { const registry = createCapabilityRegistry(); registerCapability(registry, definition() as never); expect(() => bindCapability(registry, "calendar.events.read", [operation])).toThrow(); });
  it("preserves attribution, freshness, and cost requirements", () => { const registry = createCapabilityRegistry(); registerCapability(registry, definition({ freshnessRequirement: "STALE_OK", costClass: "HIGH", sourceAttributionRequired: true }) as never); expect(bindCapability(registry, "calendar.events.read", ["READ"])).toMatchObject({ attributionRequired: true, freshnessRequirement: "STALE_OK", costClass: "HIGH" }); });
  it("allows multiple connectors to reference one provider-neutral capability", () => { const first = createConnectorRegistry(); const second = createConnectorRegistry(); const binding = { capabilityId: "calendar.events.read", operations: ["READ"], permissionReferences: [], attributionRequired: true, freshnessRequirement: "CURRENT", costClass: "LOW" } as const; first.register({ id: "connector.one", type: "CUSTOM", lifecycleState: "DECLARED", adapterReference: "adapter.one", requiresAccount: false, requiresCredential: false, bindings: [binding] }); second.register({ id: "connector.two", type: "CUSTOM", lifecycleState: "DECLARED", adapterReference: "adapter.two", requiresAccount: false, requiresCredential: false, bindings: [binding] }); expect(first.capabilityBindings("connector.one")[0]?.capabilityId).toBe(second.capabilityBindings("connector.two")[0]?.capabilityId); });
  it("does not authorize execution or select a provider", () => { const registry = createCapabilityRegistry(); registerCapability(registry, definition() as never); const binding = bindCapability(registry, "calendar.events.read", ["READ"]); expect(binding).not.toHaveProperty("execute"); expect(binding).not.toHaveProperty("provider"); });
  it("rejects over-large connector binding collections", () => { const bindings = Array.from({ length: 129 }, (_, index) => ({ capabilityId: `capability.${index}`, operations: ["READ"], permissionReferences: [], attributionRequired: false, freshnessRequirement: "CURRENT", costClass: "LOW" })); expect(() => createConnectorRegistry().register({ id: "connector.bounds", type: "CUSTOM", lifecycleState: "DECLARED", adapterReference: "adapter.bounds", requiresAccount: false, requiresCredential: false, bindings } as never)).toThrow(); });
});
