import { WORKFLOW_CONTRACT_VERSION, WORKFLOW_STATES, type WorkflowState } from "@onyx/phase1a5-workflow-engine";
import { RUNTIME_CONTRACT_VERSION } from "@onyx/phase1a6-workflow-runtime";
import {
  ACCESSIBILITY_GATE_CONTRACT_VERSION,
  AGENT_COORDINATION_CONTRACT_VERSION,
  AUTOMATION_CENTER_V2_CONTRACT_VERSION,
  BUDGET_CONTRACT_VERSION,
  COMPATIBLE_UI_CONTRACT_VERSION,
  CONNECTOR_SCOPE_CONTRACT_VERSION,
  CONTEXT_CONTRACT_VERSION,
  COUNCIL_MODE_CONTRACT_VERSION,
  MEMORY_CONTRACT_VERSION,
  PERSONA_PROTECTION_CONTRACT_VERSION,
  SAVED_DRAFT_CONTRACT_VERSION,
} from "@onyx/phase1a8-governed-contracts/shared";

export const PHASE1A9_SCHEDULER_CONTRACT_VERSION = "1.0.0" as const;
export const PHASE1A9_AUTHORITY_CONTRACT_VERSION = "1.0.0" as const;
export const PHASE1A9_LANE_CONTRACT_VERSION = "1.0.0" as const;
export const PHASE1A9_TASK_REFERENCE_CONTRACT_VERSION = "1.0.0" as const;
export const PHASE1A9_EVENT_CONTRACT_VERSION = "1.0.0" as const;
export const PHASE1A9_CLASSIFICATION_MAPPING_VERSION = "1.0.0" as const;
export const PHASE1A9_EVIDENCE_ARTIFACT_CONTRACT_VERSION = "1.0.0" as const;
export const PHASE1A9_DEPENDENCY_RESOLUTION_CONTRACT_VERSION = "1.0.0" as const;
export const PHASE1A9_READY_SET_DECISION_CONTRACT_VERSION = "1.0.0" as const;
export const PHASE1A9_PROMOTION_CONTRACT_VERSION = "1.0.0" as const;
export const PHASE1A9_EVIDENCE_CONTRACT_VERSION = "1.0.0" as const;

export const COMPATIBLE_WORKFLOW_CONTRACT_VERSION = WORKFLOW_CONTRACT_VERSION;
export const COMPATIBLE_RUNTIME_CONTRACT_VERSION = RUNTIME_CONTRACT_VERSION;
export const COMPATIBLE_GOVERNED_CONTRACTS_VERSION = AGENT_COORDINATION_CONTRACT_VERSION;
export const COMPATIBLE_UI_CONTRACT_VERSION_FROM_PREDECESSOR = COMPATIBLE_UI_CONTRACT_VERSION;

if (COMPATIBLE_WORKFLOW_CONTRACT_VERSION !== "1.0.0" || COMPATIBLE_RUNTIME_CONTRACT_VERSION !== "1.0.0" || COMPATIBLE_GOVERNED_CONTRACTS_VERSION !== "1.0.0" || COMPATIBLE_UI_CONTRACT_VERSION_FROM_PREDECESSOR !== "1.0.0") {
  throw new Error("Phase 1A.9 predecessor compatibility versions must remain 1.0.0.");
}

export const PHASE1A8_GOVERNED_CONTRACT_GROUP_VERSIONS = {
  agent: AGENT_COORDINATION_CONTRACT_VERSION,
  budget: BUDGET_CONTRACT_VERSION,
  connector: CONNECTOR_SCOPE_CONTRACT_VERSION,
  context: CONTEXT_CONTRACT_VERSION,
  council: COUNCIL_MODE_CONTRACT_VERSION,
  memory: MEMORY_CONTRACT_VERSION,
  persona: PERSONA_PROTECTION_CONTRACT_VERSION,
  savedDraft: SAVED_DRAFT_CONTRACT_VERSION,
  accessibility: ACCESSIBILITY_GATE_CONTRACT_VERSION,
  automationCenter: AUTOMATION_CENTER_V2_CONTRACT_VERSION,
} as const;

export { WORKFLOW_STATES };
export type { WorkflowState };