import type{AutomationIssueDraft}from"./automationIntakeContracts";import type{ExecutionApproval,OrchestrationValidation,SupervisedRun}from"./automationOrchestrationContracts";
const key="onyx:supervised-runs:v1";
function slug(s:string){return s.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,48)||"automation"}
export function draftToRun(draft:AutomationIssueDraft,now=new Date()):SupervisedRun{return{runId:`run-${draft.draftId}`,draftId:draft.draftId,scopeHash:draft.scopeHash,state:"AWAITING_EXECUTION_APPROVAL",repository:draft.repository,baseBranch:draft.baseBranch,proposedBranch:`automation/intake-${slug(draft.title)}`,plan:{objective:draft.objective,allowedPaths:draft.allowedPaths,acceptanceCriteria:draft.acceptanceCriteria,validationPlan:draft.validationPlan,rollbackPlan:draft.rollbackPlan},preflight:{status:"NOT_RUN",checks:[]},remoteWritesPerformed:false,branchCreated:false,issueCreated:false,draftPrCreated:false,mergeAllowed:false,productionDeployAllowed:false,createdAt:now.toISOString(),updatedAt:now.toISOString()}}
export function validateExecutionApproval(run:SupervisedRun,input:{approvedBy:string;reason:string;scopeHash:string;expiresAt?:string},now=new Date()):OrchestrationValidation{const v:string[]=[];if(input.approvedBy!=="Rahul Kumar")v.push("Execution approval authority must be Rahul Kumar");if(input.reason.trim().length<12)v.push("Execution approval reason must contain at least 12 characters");if(input.scopeHash!==run.scopeHash)v.push("Execution approval scope hash mismatch");if(input.expiresAt&&new Date(input.expiresAt).getTime()<=now.getTime())v.push("Execution approval expiry must be in the future");return{allowed:v.length===0,violations:v}}
export function approveDryRun(run:SupervisedRun,input:{reason:string;expiresAt?:string},now=new Date()):SupervisedRun{const gate=validateExecutionApproval(run,{approvedBy:"Rahul Kumar",reason:input.reason,scopeHash:run.scopeHash,expiresAt:input.expiresAt},now);if(!gate.allowed)throw Error(gate.violations.join("; "));const approval:ExecutionApproval={approvedBy:"Rahul Kumar",reason:input.reason.trim(),scopeHash:run.scopeHash,approvedAt:now.toISOString(),expiresAt:input.expiresAt||undefined,actions:["BUILD_PLAN","RUN_PREFLIGHT"]};return{...run,state:"APPROVED_FOR_DRY_RUN",approval,updatedAt:now.toISOString()}}
export function runLocalPreflight(run:SupervisedRun,now=new Date()):SupervisedRun{if(run.state!=="APPROVED_FOR_DRY_RUN")throw Error("Dry-run approval is required");const checks=[{label:"Exact scope hash",passed:run.approval?.scopeHash===run.scopeHash,detail:run.scopeHash},{label:"Allowed paths",passed:run.plan.allowedPaths.length>0,detail:run.plan.allowedPaths.join(", ")},{label:"Protected operations",passed:!run.plan.objective.toLowerCase().includes("production deploy"),detail:"No merge, deployment, secret, permission, or branch-protection action"},{label:"Validation plan",passed:run.plan.validationPlan.length>0,detail:`${run.plan.validationPlan.length} validation gates planned`},{label:"Rollback plan",passed:run.plan.rollbackPlan.length>0,detail:`${run.plan.rollbackPlan.length} rollback steps planned`}];const pass=checks.every(x=>x.passed);return{...run,state:pass?"DRY_RUN_READY":"BLOCKED",preflight:{status:pass?"PASS":"BLOCKED",checks},updatedAt:now.toISOString()}}
export function saveSupervisedRun(run:SupervisedRun){if(typeof window==="undefined")return;const rows=listSupervisedRuns(),i=rows.findIndex(x=>x.runId===run.runId);if(i>=0)rows[i]=run;else rows.unshift(run);window.localStorage.setItem(key,JSON.stringify(rows));window.dispatchEvent(new CustomEvent("onyx:supervised-run",{detail:run}))}
export function listSupervisedRuns():SupervisedRun[]{if(typeof window==="undefined")return[];try{return JSON.parse(window.localStorage.getItem(key)||"[]")as SupervisedRun[]}catch{return[]}}
