import type{AutomationIssueDraft,IntakeRisk,IntakeValidation,NaturalLanguageIntakeInput}from"./automationIntakeContracts";
const draftsKey="onyx:automation-intake-drafts:v1";const activeKey="onyx:automation-intake-active:v1";
function stableHash(value:string){let h1=0x811c9dc5;for(let i=0;i<value.length;i++){h1^=value.charCodeAt(i);h1=Math.imul(h1,0x01000193)}return `scope-${(h1>>>0).toString(16).padStart(8,"0")}`}
function cleanGoal(goal:string){return goal.trim().replace(/\s+/g," ")}
function titleFromGoal(goal:string){const cleaned=cleanGoal(goal).replace(/[.!?]+$/g,"");return cleaned.length<=92?cleaned:`${cleaned.slice(0,89)}...`}
function classifyRisk(goal:string,paths:string[]):{risk:IntakeRisk;reasons:string[]}{const text=goal.toLowerCase();const reasons:string[]=[];let risk:IntakeRisk="low";if(/secret|permission|branch protection|production|deploy|database|delete|billing|payment/.test(text)){risk="critical";reasons.push("Request contains a protected or high-impact capability")}else if(/auth|identity|api|migration|schema/.test(text)){risk="high";reasons.push("Request may affect authentication, API, or data contracts")}else if(paths.some(x=>x.startsWith("apps/")||x.startsWith("packages/"))){risk="medium";reasons.push("Request may change application or package code")}else reasons.push("Documentation or bounded low-impact scope");return{risk,reasons}}
export function validateNaturalLanguageIntake(input:NaturalLanguageIntakeInput):IntakeValidation{const v:string[]=[];const goal=cleanGoal(input.goal);if(goal.length<12)v.push("Describe the goal using at least 12 characters");if(goal.length>1200)v.push("Goal must not exceed 1200 characters");if(input.requestedBy!=="Rahul Kumar")v.push("Requester must be Rahul Kumar");if(!/^[-\w]+\/[-.\w]+$/.test(input.repository))v.push("Repository must use owner/name format");if(!input.baseBranch.trim())v.push("Base branch is required");if(!input.allowedPaths.length)v.push("At least one allowed path is required");if(input.allowedPaths.some(x=>x.includes("..")||x.startsWith("/")||x==="main"))v.push("Allowed paths must be relative repository paths");return{allowed:v.length===0,violations:v}}
export function createAutomationIssueDraft(input:NaturalLanguageIntakeInput,now=new Date()):AutomationIssueDraft{const gate=validateNaturalLanguageIntake(input);if(!gate.allowed)throw Error(gate.violations.join("; "));const goal=cleanGoal(input.goal),risk=classifyRisk(goal,input.allowedPaths),title=titleFromGoal(goal);const criteria=[`Implement the requested objective: ${goal}`,`Limit changes to approved paths: ${input.allowedPaths.join(", ")}`,"Pass typecheck, focused tests, build, and git diff validation","Produce validation evidence and rollback instructions","Create a Draft PR only after separate approval"];const scope={repository:input.repository,baseBranch:input.baseBranch,objective:goal,allowedPaths:[...input.allowedPaths].sort(),criteria};const scopeHash=stableHash(JSON.stringify(scope));const body=["## Objective",goal,"","## Approved File Boundary",...input.allowedPaths.map(x=>`- ${x}`),"","## Acceptance Criteria",...criteria.map(x=>`- [ ] ${x}`),"","## Governance","- Draft PR only","- No merge","- No production deployment","- No secret, permission, or branch-protection changes"].join("\n");return{draftId:`intake-${now.getTime()}-${scopeHash}`,title,body,objective:goal,acceptanceCriteria:criteria,risk:risk.risk,riskReasons:risk.reasons,allowedPaths:input.allowedPaths,prohibitedActions:["MERGE_PR","WRITE_PROTECTED_BRANCH","PRODUCTION_DEPLOY","MODIFY_SECRETS","MODIFY_PERMISSIONS","MODIFY_BRANCH_PROTECTION","DESTRUCTIVE_GIT"],validationPlan:["pnpm typecheck","focused tests","production build","git diff --check","boundary and prohibited-capability scan"],rollbackPlan:["Stop before any external action","Discard the local draft if rejected","Revert isolated changes if implementation is later authorized","Retain audit and evidence records"],repository:input.repository,baseBranch:input.baseBranch,requestedBy:"Rahul Kumar",scopeHash,state:"DRAFT_AWAITING_REVIEW",remoteIssueCreated:false,executionStarted:false,mergeAllowed:false,productionDeployAllowed:false,createdAt:now.toISOString()}}
export function listAutomationIssueDrafts():AutomationIssueDraft[]{if(typeof window==="undefined")return[];try{return JSON.parse(window.localStorage.getItem(draftsKey)||"[]")as AutomationIssueDraft[]}catch{return[]}}
export function saveAutomationIssueDraft(draft:AutomationIssueDraft){if(typeof window==="undefined")return;const rows=listAutomationIssueDrafts(),i=rows.findIndex(x=>x.scopeHash===draft.scopeHash);if(i>=0)rows[i]=draft;else rows.unshift(draft);window.localStorage.setItem(draftsKey,JSON.stringify(rows));window.localStorage.setItem(activeKey,draft.draftId);window.dispatchEvent(new CustomEvent("onyx:automation-intake-draft",{detail:draft}))}
export function loadActiveAutomationIssueDraft():AutomationIssueDraft|null{if(typeof window==="undefined")return null;const rows=listAutomationIssueDrafts(),id=window.localStorage.getItem(activeKey);return rows.find(x=>x.draftId===id)??rows[0]??null}
export function setActiveAutomationIssueDraft(draftId:string){if(typeof window!=="undefined")window.localStorage.setItem(activeKey,draftId)}
export function deleteAutomationIssueDraft(draftId:string){if(typeof window==="undefined")return;const rows=listAutomationIssueDrafts().filter(x=>x.draftId!==draftId);window.localStorage.setItem(draftsKey,JSON.stringify(rows));if(window.localStorage.getItem(activeKey)===draftId){if(rows[0])window.localStorage.setItem(activeKey,rows[0].draftId);else window.localStorage.removeItem(activeKey)}window.dispatchEvent(new CustomEvent("onyx:automation-intake-deleted",{detail:{draftId}}))}
