type Assistant="nova"|"onyx";
type SpeechRecognitionLike={continuous:boolean;interimResults:boolean;lang:string;start():void;stop():void;abort():void;onresult:((event:any)=>void)|null;onerror:((event:any)=>void)|null;onend:(()=>void)|null;onstart:(()=>void)|null};
type RecognitionCtor=new()=>SpeechRecognitionLike;
const statusEvent="onyx:voice-supervisor-status";const settingEvent="onyx:voice-supervisor-setting";
let enabled=false,wakeEnabled=true,running=false,assistant:Assistant="nova",recognition:SpeechRecognitionLike|undefined,retry=0,restartTimer:number|undefined,lastWake=0;
const emit=(message:string,state="info")=>window.dispatchEvent(new CustomEvent(statusEvent,{detail:{message,state,assistant}}));
const label=(button:HTMLButtonElement)=>[button.getAttribute("aria-label"),button.getAttribute("title"),button.dataset.testid,button.textContent].filter(Boolean).join(" ").toLowerCase();
function findButton(pattern:RegExp){return [...document.querySelectorAll<HTMLButtonElement>("button")].find(b=>pattern.test(label(b)))}
function chooseAssistant(next:Assistant){assistant=next;const b=findButton(new RegExp(`^${next}$|\\b${next}\\b`,"i"));if(b&&!b.disabled)b.click();emit(`${next.toUpperCase()} selected by wake word.`,"wake")}
function armCommand(){const b=findButton(/microphone|voice input|start listening|push.to.talk|(^|\\s)mic($|\\s)|🎙|🎤/i);if(!b){emit("Wake word detected, but the command microphone control could not be located.","warning");return}if(b.disabled){emit("Wake word detected; command microphone is currently disabled.","warning");return}b.click();emit(`${assistant.toUpperCase()} command listening armed.`,"listening")}
function parse(text:string){const normalized=text.trim().toLowerCase().replace(/[.,!?]/g,"");const match=normalized.match(/^(?:hey\\s+)?(nova|onyx)\\b(?:\\s+(.+))?/i);if(!match)return;const now=Date.now();if(now-lastWake<1200)return;lastWake=now;const assistantMatch=match[1];if(!assistantMatch)return;const next=assistantMatch.toLowerCase() as Assistant;chooseAssistant(next);const command=(match[2]||"").trim();window.setTimeout(()=>{armCommand();if(command)window.dispatchEvent(new CustomEvent("onyx:wake-command",{detail:{assistant:next,command}}))},250)}
function ctor():RecognitionCtor|undefined{return (window as any).SpeechRecognition||(window as any).webkitSpeechRecognition}
function schedule(reason:string){if(!enabled||!wakeEnabled||document.hidden)return;window.clearTimeout(restartTimer);const delay=Math.min(5000,600*Math.pow(1.7,retry++));emit(`${reason} Retrying in ${Math.round(delay)} ms.`,"recovering");restartTimer=window.setTimeout(start,delay)}
function start(){if(!enabled||!wakeEnabled||running||document.hidden)return;const C=ctor();if(!C){emit("Wake words are unavailable because this browser does not expose Web Speech Recognition.","unsupported");return}recognition??=new C();recognition.continuous=true;recognition.interimResults=false;recognition.lang="en-IN";recognition.onstart=()=>{running=true;retry=0;emit(`Wake-word listener active for ${assistant.toUpperCase()}.`,"listening")};recognition.onresult=(event:any)=>{for(let i=event.resultIndex;i<event.results.length;i++)if(event.results[i].isFinal)parse(event.results[i][0].transcript||"")};recognition.onerror=(event:any)=>{running=false;const error=String(event.error||"unknown");if(error==="not-allowed"||error==="service-not-allowed"){enabled=false;emit("Microphone permission is required for Auto Listen and wake words.","permission");return}if(error==="aborted"||error==="no-speech"){schedule(error==="aborted"?"Recognition was interrupted.":"No speech detected.");return}schedule(`Voice recognition error: ${error}.`)};recognition.onend=()=>{running=false;if(enabled&&wakeEnabled)schedule("Wake-word listener ended.")};try{recognition.start()}catch(error){running=false;schedule("Recognition start was deferred.")}}
function stop(){enabled=false;window.clearTimeout(restartTimer);try{recognition?.stop()}catch{}running=false;emit("Auto Listen and wake-word listener stopped. Push-to-talk remains available.","idle")}
function setting(event:Event){const d=(event as CustomEvent<{assistant?:Assistant;enabled?:boolean;wakeEnabled?:boolean}>).detail||{};if(d.assistant)assistant=d.assistant;if(typeof d.wakeEnabled==="boolean")wakeEnabled=d.wakeEnabled;if(d.enabled){enabled=true;start()}else if(d.enabled===false)stop()}
if(typeof window!=="undefined"){window.addEventListener(settingEvent,setting);window.addEventListener("focus",()=>{if(enabled)start()});document.addEventListener("visibilitychange",()=>{if(document.hidden){try{recognition?.stop()}catch{}}else if(enabled)start()})}
