import type { CalendarAgendaProjection, CalendarEventRecord, CalendarRangeKind } from "@onyx/calendar-intelligence";
import type { MicrosoftCalendarReadDiagnostic } from "@onyx/workspace-connectors";

const diagnosticWrapStyle = {
  minWidth: 0,
  maxWidth: "100%",
  overflowWrap: "anywhere",
  wordBreak: "break-word",
  whiteSpace: "normal",
} as const;

export function CalendarIntelligencePanel({ summary, busy, onRefresh, onSpeak, onSelectRange = () => {}, connected = false, unavailable = false, events = [], diagnostic }: { summary?: CalendarAgendaProjection; busy: boolean; onRefresh: () => void; onSpeak: () => void; onSelectRange?: (range: CalendarRangeKind) => void; connected?: boolean; unavailable?: boolean; events?: readonly CalendarEventRecord[]; diagnostic?: MicrosoftCalendarReadDiagnostic }) {
  const ranges: { label: string; value: CalendarRangeKind }[] = [
    { label: "Today", value: "TODAY" }, { label: "Tomorrow", value: "TOMORROW" },
    { label: "Current Week", value: "CURRENT_WEEK" }, { label: "Next Week", value: "NEXT_WEEK" },
  ];
  const diagnosticDetails = diagnostic ? <details style={diagnosticWrapStyle}><summary style={diagnosticWrapStyle}>Calendar read diagnostic</summary><dl style={{ ...diagnosticWrapStyle, display: "grid", gridTemplateColumns: "minmax(0, max-content) minmax(0, 1fr)", gap: "0.35rem 0.75rem" }}><dt style={diagnosticWrapStyle}>Stage</dt><dd style={{ ...diagnosticWrapStyle, margin: 0 }}>{diagnostic.stage}</dd><dt style={diagnosticWrapStyle}>Outcome</dt><dd style={{ ...diagnosticWrapStyle, margin: 0 }}>{diagnostic.outcome}</dd><dt style={diagnosticWrapStyle}>Reason code</dt><dd style={{ ...diagnosticWrapStyle, margin: 0 }}>{diagnostic.reasonCode}</dd><dt style={diagnosticWrapStyle}>HTTP status</dt><dd style={{ ...diagnosticWrapStyle, margin: 0 }}>{diagnostic.httpStatus ?? "absent"}</dd><dt style={diagnosticWrapStyle}>Events returned</dt><dd style={{ ...diagnosticWrapStyle, margin: 0 }}>{diagnostic.returnedEventCount ?? "absent"}</dd><dt style={diagnosticWrapStyle}>Events normalized</dt><dd style={{ ...diagnosticWrapStyle, margin: 0 }}>{diagnostic.normalizedEventCount ?? "absent"}</dd><dt style={diagnosticWrapStyle}>Events rejected</dt><dd style={{ ...diagnosticWrapStyle, margin: 0 }}>{diagnostic.rejectedEventCount ?? "absent"}</dd><dt style={diagnosticWrapStyle}>Events rendered</dt><dd style={{ ...diagnosticWrapStyle, margin: 0 }}>{events.length}</dd></dl></details> : null;
  const signInRequired = connected && unavailable && diagnostic?.reasonCode === "MICROSOFT_INTERACTION_REQUIRED";
  if (!summary && connected && !unavailable) return <section id="panel-calendar-intelligence" className="glass-surface" style={{ margin: "1rem", padding: "1rem", borderRadius: "1rem", display: "grid", gap: "0.75rem" }}><small>Calendar</small><h2>Calendar</h2><div><button type="button" onClick={onRefresh} disabled={busy}>Refresh</button> <button type="button" onClick={onSpeak} disabled>Read Agenda</button></div><strong>{events.length} event{events.length === 1 ? "" : "s"}</strong>{events.length === 0 ? <p>No events are scheduled for this range.</p> : <ul>{events.map((event) => <li key={event.id}><strong>{event.subject}</strong><br /><small>{new Date(event.start).toLocaleString()} to {new Date(event.end).toLocaleTimeString()}</small>{event.location && <><br /><small>{event.location}</small></>}</li>)}</ul>}{diagnosticDetails}</section>;
  if (!summary && connected && unavailable) return <section id="panel-calendar-intelligence" className="glass-surface" style={{ margin: "1rem", padding: "1rem", borderRadius: "1rem" }}><small>Calendar</small><h2>Calendar</h2><strong>{signInRequired ? "Connected, sign-in required" : "Connected, unavailable"}</strong><p>{signInRequired ? "Microsoft calendar requires a fresh sign-in before events can be loaded for this range." : "Microsoft calendar is connected, but events could not be loaded for this range."}</p><button type="button" onClick={onRefresh} disabled={busy}>Refresh</button>{diagnosticDetails}</section>;
  if (!summary) return <section id="panel-calendar-intelligence" className="glass-surface" style={{ margin: "1rem", padding: "1rem", borderRadius: "1rem" }}><small>Local Calendar</small><h2>Calendar</h2><button type="button" onClick={onRefresh}>Refresh</button> <button type="button" onClick={onSpeak} disabled>Read Agenda</button><strong>Calendar not configured</strong><p>No calendar events are available.</p><small>Connect a calendar account or refresh to check for events. No connected calendar event data is available.</small></section>;
  return <section id="panel-calendar-intelligence" className="glass-surface" style={{ margin: "1rem", padding: "1rem", borderRadius: "1rem", display: "grid", gap: "1rem" }}>
    <header style={{ display: "flex", justifyContent: "space-between", gap: ".75rem", flexWrap: "wrap" }}><div><small>Local Calendar</small><h2>Calendar</h2></div><div><button type="button" onClick={onRefresh} disabled={busy}>Refresh</button> <button type="button" onClick={onSpeak} disabled={busy}>Read Agenda</button></div></header>
    <div aria-live="polite" style={{ display: "grid", gap: ".75rem" }}>
      <div><strong>Local date and time</strong><div>{summary.currentDateTime}</div><small>{summary.requestedRange.timeZone} · locale-aware browser display</small></div>
      <div role="group" aria-label="Date range"><strong>Date navigation</strong><div style={{ display: "flex", gap: ".5rem", flexWrap: "wrap", marginTop: ".4rem" }}>{ranges.map((range) => <button key={range.value} type="button" onClick={() => onSelectRange(range.value)} aria-pressed={summary.requestedRange.kind === range.value} disabled={busy}>{range.label}</button>)}</div></div>
      <div><strong>Calendar connection</strong><div>{connected ? (signInRequired ? "Connected, sign-in required" : unavailable ? "Connected, unavailable" : "Connected") : "Not configured"}</div><small>{connected ? (signInRequired ? "Microsoft calendar requires a fresh sign-in before events can be loaded for this range." : unavailable ? "Microsoft calendar is connected, but events could not be loaded for this range." : "Microsoft calendar events are available for the selected range.") : "Real meetings require a connected calendar read."}</small></div>{diagnosticDetails}
      <div className="glass-surface" style={{ padding: ".8rem", borderRadius: ".75rem" }}><strong>{connected && !unavailable ? "Calendar events" : "Local agenda"}: {summary.requestedRange.displayLabel}</strong>{connected && !unavailable ? events.length === 0 ? <p>No events are scheduled for this range.</p> : <ul>{events.map((event) => <li key={event.id}><strong>{event.subject}</strong><br /><small>{new Date(event.start).toLocaleString()} to {new Date(event.end).toLocaleTimeString()}</small>{event.location && <><br /><small>{event.location}</small></>}</li>)}</ul> : <><p>No connected calendar event data is available.</p><small>{summary.limitations.join(" ") || "Real event data is unavailable without an approved connector."}</small></>}</div>
    </div>
  </section>;
}