import type { CalendarAgendaProjection, CalendarEventRecord, CalendarRangeKind } from "@onyx/calendar-intelligence";

export function CalendarIntelligencePanel({ summary, busy, onRefresh, onSpeak, onSelectRange = () => {}, connected = false, events = [] }: { summary?: CalendarAgendaProjection; busy: boolean; onRefresh: () => void; onSpeak: () => void; onSelectRange?: (range: CalendarRangeKind) => void; connected?: boolean; events?: readonly CalendarEventRecord[] }) {
  const ranges: { label: string; value: CalendarRangeKind }[] = [
    { label: "Today", value: "TODAY" }, { label: "Tomorrow", value: "TOMORROW" },
    { label: "Current Week", value: "CURRENT_WEEK" }, { label: "Next Week", value: "NEXT_WEEK" },
  ];
  if (!summary && connected) return <section id="panel-calendar-intelligence" className="glass-surface" style={{ margin: "1rem", padding: "1rem", borderRadius: "1rem", display: "grid", gap: "0.75rem" }}><small>Calendar</small><h2>Calendar</h2><div><button type="button" onClick={onRefresh} disabled={busy}>Refresh</button> <button type="button" onClick={onSpeak} disabled>Read Agenda</button></div><strong>{events.length} event{events.length === 1 ? "" : "s"}</strong>{events.length === 0 ? <p>No events are scheduled for this range.</p> : <ul>{events.map((event) => <li key={event.id}><strong>{event.subject}</strong><br /><small>{new Date(event.start).toLocaleString()} to {new Date(event.end).toLocaleTimeString()}</small>{event.location && <><br /><small>{event.location}</small></>}</li>)}</ul>}</section>;
  if (!summary) return <section id="panel-calendar-intelligence" className="glass-surface" style={{ margin: "1rem", padding: "1rem", borderRadius: "1rem" }}><small>Local Calendar</small><h2>Calendar</h2><button type="button" onClick={onRefresh}>Refresh</button> <button type="button" onClick={onSpeak} disabled>Read Agenda</button><strong>Calendar not configured</strong><p>No calendar events are available.</p><small>Connect a calendar account or refresh to check for events. No connected calendar event data is available.</small></section>;
  return <section id="panel-calendar-intelligence" className="glass-surface" style={{ margin: "1rem", padding: "1rem", borderRadius: "1rem", display: "grid", gap: "1rem" }}>
    <header style={{ display: "flex", justifyContent: "space-between", gap: ".75rem", flexWrap: "wrap" }}><div><small>Local Calendar</small><h2>Calendar</h2></div><div><button type="button" onClick={onRefresh} disabled={busy}>Refresh</button> <button type="button" onClick={onSpeak} disabled={busy}>Read Agenda</button></div></header>
    <div aria-live="polite" style={{ display: "grid", gap: ".75rem" }}>
      <div><strong>Local date and time</strong><div>{summary.currentDateTime}</div><small>{summary.requestedRange.timeZone} · locale-aware browser display</small></div>
      <div role="group" aria-label="Date range"><strong>Date navigation</strong><div style={{ display: "flex", gap: ".5rem", flexWrap: "wrap", marginTop: ".4rem" }}>{ranges.map((range) => <button key={range.value} type="button" onClick={() => onSelectRange(range.value)} aria-pressed={summary.requestedRange.kind === range.value} disabled={busy}>{range.label}</button>)}</div></div>
      <div><strong>Calendar connection</strong><div>Not configured</div><small>Real meetings require a future approved connector.</small></div>
      <div className="glass-surface" style={{ padding: ".8rem", borderRadius: ".75rem" }}><strong>{connected ? "Calendar events" : "Local agenda"}: {summary.requestedRange.displayLabel}</strong>{connected ? events.length === 0 ? <p>No events are scheduled for this range.</p> : <ul>{events.map((event) => <li key={event.id}><strong>{event.subject}</strong><br /><small>{new Date(event.start).toLocaleString()} to {new Date(event.end).toLocaleTimeString()}</small>{event.location && <><br /><small>{event.location}</small></>}</li>)}</ul> : <><p>No connected calendar event data is available.</p><small>{summary.limitations.join(" ") || "Real event data is unavailable without an approved connector."}</small></>}</div>
    </div>
  </section>;
}