import { useEffect, useRef, useState, type CSSProperties, type ReactNode } from "react";
import type { FileSourceProjection, LocalPreviewState } from "@onyx/workspace-contracts";
import { convertImage, createPreviewUrl, detectLocalFileCapabilities, formatBytes, readLocalDirectory, readTextPreview, revokePreviewUrl, saveAs, selectLocalDirectory, selectLocalDirectoryFile, selectLocalFile, selectLocalFileFallback, type LocalDirectorySelection, type LocalSelection, writeToHandle } from "../localFilesProvider";

export interface FilesHubPanelProps { readonly sources: readonly FileSourceProjection[]; readonly onMicrosoftAction?: (action: "OPEN" | "CONNECT" | "RECONNECT") => void; readonly onGoogleAction?: (action: "OPEN" | "CONNECT" | "REFRESH") => void; readonly providerBodies?: Partial<Record<PanelId, ReactNode>>; }
const localCapabilities = detectLocalFileCapabilities();
const prettyPreviewState: Record<LocalPreviewState, string> = { NOT_REQUESTED: "Not opened", AVAILABLE: "Available", UNSUPPORTED: "Preview unavailable", UNAVAILABLE: "Preview unavailable", TOO_LARGE: "Preview unavailable due to size", FAILED: "Preview failed" };
const secretPattern = /(bearer\s+|token\s*[:=]|password\s*[:=]|secret\s*[:=]|-----BEGIN [A-Z ]+-----)[^\n]*/gi;

type PanelMode = "NORMAL" | "MAXIMISED" | "MINIMISED";
type PanelId = "local-files" | "microsoft-onedrive" | "microsoft-sharepoint" | "google-drive";
type PanelState = { readonly mode: PanelMode; readonly width: number; readonly height: number };

const compactToolbarButton: CSSProperties = { width: "2rem", height: "2rem", minWidth: "2rem", padding: 0, alignSelf: "flex-start", lineHeight: 1 };

function FilesProviderSubPanel({ id, title, state, onState, canGoBack = false, onBack, children }: { readonly id: PanelId; readonly title: string; readonly state: PanelState; readonly onState: (state: PanelState) => void; readonly canGoBack?: boolean; readonly onBack?: () => void; readonly children: ReactNode }) {
  const resize = (delta: number) => onState({ ...state, width: Math.max(18, Math.min(100, state.width + delta)), height: Math.max(18, Math.min(90, state.height + delta / 2)) });
  const action = (label: string, symbol: string, disabled: boolean, callback: () => void) => <button type="button" style={compactToolbarButton} aria-label={`${label} ${title}`} title={`${label} ${title}`} disabled={disabled} onClick={callback}>{symbol}</button>;
  if (state.mode === "MINIMISED") return <article className="files-provider-subpanel files-provider-subpanel--minimised" style={{ minWidth: 0, maxWidth: "100%", boxSizing: "border-box" }} aria-label={`${title} minimised`}><header style={{ display: "flex", alignItems: "center", justifyContent: "space-between", gap: "0.35rem", minWidth: 0 }}><strong style={{ overflowWrap: "anywhere" }}>{title}</strong>{action("Restore", "↗", false, () => onState({ ...state, mode: "NORMAL" }))}</header></article>;
  const panelStyle: CSSProperties = { minWidth: 0, minHeight: state.mode === "NORMAL" ? `${state.height}rem` : 0, maxWidth: "100%", width: state.mode === "MAXIMISED" ? "100%" : `${state.width}%`, boxSizing: "border-box", display: "grid", gridTemplateRows: "auto minmax(0, 1fr)", overflow: "hidden", ...(state.mode !== "NORMAL" ? { height: "100%" } : {}) };
  return <article className={`files-provider-subpanel files-provider-subpanel--${state.mode.toLowerCase()}`} style={panelStyle} aria-labelledby={`${id}-heading`}>
    <header style={{ display: "flex", alignItems: "center", justifyContent: "space-between", gap: "0.4rem", minWidth: 0, flexWrap: "wrap" }}><strong id={`${id}-heading`} style={{ minWidth: 0, overflowWrap: "anywhere" }}>{title}</strong><div role="toolbar" aria-label={`${title} controls`} style={{ display: "flex", gap: "0.2rem", flex: "0 0 auto" }}>{action("Back", "←", !canGoBack, () => onBack?.())}{action("Maximise", "↗", state.mode === "MAXIMISED", () => onState({ ...state, mode: "MAXIMISED" }))}{action("Minimise", "—", false, () => onState({ ...state, mode: "MINIMISED" }))}{action("Restore", "□", state.mode === "NORMAL", () => onState({ ...state, mode: "NORMAL" }))}{action("Resize", "◢", state.mode !== "NORMAL", () => resize(8))}</div></header><div style={{ minWidth: 0, minHeight: 0, maxWidth: "100%", overflow: "auto", overflowWrap: "anywhere", wordBreak: "break-word" }}>{children}</div>
  </article>;
}

function LocalFileWorkspace() {
  const [selection, setSelection] = useState<LocalSelection>();
  const [directory, setDirectory] = useState<LocalDirectorySelection>();
  const [previewUrl, setPreviewUrl] = useState<string>();
  const [text, setText] = useState("");
  const [dirty, setDirty] = useState(false);
  const [previewState, setPreviewState] = useState<LocalPreviewState>("NOT_REQUESTED");
  const [message, setMessage] = useState("No local file or folder selected.");
  const [busy, setBusy] = useState(false);
  const [outputMimeType, setOutputMimeType] = useState<string>();
  const [search, setSearch] = useState("");
  const [replace, setReplace] = useState("");
  const mediaRef = useRef<HTMLMediaElement | null>(null);
  const setMediaRef = (element: HTMLMediaElement | null): void => { mediaRef.current = element; };

  useEffect(() => () => { mediaRef.current?.pause(); revokePreviewUrl(previewUrl); }, [previewUrl]);
  useEffect(() => {
    revokePreviewUrl(previewUrl);
    setPreviewUrl(undefined);
    setText("");
    setDirty(false); setOutputMimeType(undefined);
    if (!selection) { setPreviewState("NOT_REQUESTED"); return; }
    if (selection.projection.validationState === "INVALID") { setPreviewState("FAILED"); return; }
    if (["image-viewer", "audio-player", "video-player", "pdf-viewer"].includes(selection.projection.viewerId ?? "")) { setPreviewUrl(createPreviewUrl(selection.file)); setPreviewState("AVAILABLE"); return; }
    void readTextPreview(selection.file).then((result) => { setText(result.text ?? ""); setPreviewState(result.state); });
  }, [selection?.projection.selectionId]);

  const replaceSelection = (next: LocalSelection | undefined) => {
    if (dirty && !window.confirm("Discard unsaved local changes?")) return;
    setDirectory(undefined); setSelection(next); setMessage(next ? `Selected ${next.projection.name}.` : "Local selection cleared.");
  };
  const openFile = async () => { try { const next = localCapabilities.filePicker === "LOCAL_FILE_PICKER_SUPPORTED" ? await selectLocalFile() : await selectLocalFileFallback(); if (next) replaceSelection(next); else setMessage("Local file selection cancelled."); } catch { setMessage("Local file permission was denied."); } };
  const openFolder = async () => { try { const next = await selectLocalDirectory(); if (next) { if (dirty && !window.confirm("Discard unsaved local changes?")) return; setSelection(undefined); setDirectory(next); setMessage(`Selected ${next.name}.`); } else setMessage("Local folder selection cancelled."); } catch { setMessage("Local folder permission was denied."); } };
  const openDirectory = async (entry: LocalDirectorySelection["items"][number]) => { if (entry.kind !== "directory" || !entry.handle.getDirectoryHandle || !directory) return; try { const child = await entry.handle.getDirectoryHandle(); setDirectory(await readLocalDirectory(child, [...directory.stack, entry.name], [...directory.parents, directory.handle])); setSelection(undefined); setMessage(`Opened ${entry.name}.`); } catch { setMessage("The selected folder is no longer available."); } };
  const openDirectoryFile = async (entry: LocalDirectorySelection["items"][number]) => { try { const next = await selectLocalDirectoryFile(entry); if (next) { setSelection(next); setMessage(`Selected ${next.projection.name}.`); } } catch { setMessage("The selected file is no longer available."); } };
  const backDirectory = () => { if (!directory || directory.parents.length === 0) return; const parents = directory.parents.slice(0, -1); void readLocalDirectory(directory.parents[directory.parents.length - 1]!, directory.stack.slice(0, -1), parents).then(setDirectory).catch(() => setMessage("The parent folder is no longer available.")); setSelection(undefined); setMessage("Returned to the parent folder."); };
  const displayText = selection?.projection.viewerId === "log-viewer" ? text.replace(secretPattern, "[REDACTED]") : text;
  const content = selection ? (selection.projection.editCapability ? new Blob([text], { type: selection.projection.mimeType }) : selection.file) : undefined;
  const saveOriginal = async () => { if (!selection?.handle || !content || !selection.projection.originalSaveCapability) return; if (!window.confirm(`Save changes to original ${selection.projection.name}?`)) return; setBusy(true); try { await writeToHandle(selection.handle, content, selection.file); setDirty(false); setSelection({ ...selection, projection: { ...selection.projection, dirty: false } }); setMessage("Original file saved and verified by the browser write completion."); } catch (error) { setMessage(error instanceof Error && error.message.includes("changed") ? "Save stopped because the original file changed. Reload or use Save As." : "Original save could not be completed."); } finally { setBusy(false); } };
  const saveCopy = async () => { if (!selection || !content) return; setBusy(true); try { const output = outputMimeType && outputMimeType !== selection.projection.mimeType ? await convertImage(selection.file, outputMimeType) : content; const extension = outputMimeType === "image/jpeg" ? ".jpg" : outputMimeType === "image/webp" ? ".webp" : outputMimeType === "image/png" ? ".png" : selection.projection.extension; const name = extension && selection.projection.name.toLowerCase().endsWith(selection.projection.extension) ? `${selection.projection.name.slice(0, -selection.projection.extension.length)}${extension}` : selection.projection.name; const result = await saveAs(output, name, outputMimeType ?? selection.projection.mimeType); setMessage(result === "PICKER" ? "Save As completed." : "Download copy created. Open the downloaded file using the operating system's default application or another installed application."); } catch (error) { if (error instanceof DOMException && error.name === "AbortError") setMessage("Save As cancelled."); else setMessage("Save As could not be completed."); } finally { setBusy(false); } };
  const openInBrowser = () => { if (!selection) return; const url = createPreviewUrl(selection.file); window.open(url, "_blank", "noopener,noreferrer"); window.setTimeout(() => revokePreviewUrl(url), 60_000); };
  const clear = () => replaceSelection(undefined);

  return <section aria-labelledby="local-files-heading" style={{ display: "grid", gap: "0.8rem", minWidth: 0 }}>
    <div style={{ display: "flex", gap: "0.5rem", flexWrap: "wrap" }}><button type="button" onClick={() => void openFile()}>Open local file</button><button type="button" onClick={() => void openFolder()} disabled={localCapabilities.directoryPicker !== "LOCAL_DIRECTORY_PICKER_SUPPORTED"}>Open local folder</button></div>
    <small role="status">{message}</small>
    {directory && <section aria-labelledby="local-folder-heading" style={{ border: "1px solid color-mix(in srgb, currentColor 18%, transparent)", padding: "0.75rem", minWidth: 0 }}><nav aria-label="Local Files breadcrumb" style={{ overflowWrap: "anywhere" }}>Local Files{directory.stack.map((part) => ` / ${part}`)} / {directory.name}</nav><h3 id="local-folder-heading" style={{ marginTop: "0.5rem", overflowWrap: "anywhere" }}>{directory.name}</h3><small>{directory.items.length} bounded items shown. No recursive scan was performed.</small>{directory.stack.length > 0 && <button type="button" onClick={backDirectory}>Back to parent</button>}<ul style={{ paddingLeft: "1.2rem", minWidth: 0 }}>{directory.items.map((entry) => <li key={`${entry.kind}-${entry.name}`} style={{ overflowWrap: "anywhere" }}>{entry.kind === "directory" ? <button type="button" onClick={() => void openDirectory(entry)} aria-label={`Open folder ${entry.name}`}>Folder: {entry.name}</button> : <button type="button" onClick={() => void openDirectoryFile(entry)} aria-label={`Open file ${entry.name}`}>File: {entry.name}</button>}{entry.size === undefined ? "" : ` (${formatBytes(entry.size)})`}</li>)}</ul></section>}
    {selection && <section aria-labelledby="selected-file-heading" style={{ border: "1px solid color-mix(in srgb, currentColor 18%, transparent)", padding: "0.75rem", display: "grid", gap: "0.7rem", minWidth: 0 }}>
      <div style={{ display: "flex", justifyContent: "space-between", gap: "0.5rem", flexWrap: "wrap" }}><h3 id="selected-file-heading" style={{ margin: 0 }}>Selected File</h3><span aria-live="polite">{dirty ? "Unsaved changes" : "Saved state"}</span></div>
      <dl style={{ display: "grid", gridTemplateColumns: "minmax(8rem, 0.4fr) minmax(0, 1fr)", gap: "0.3rem 0.8rem", margin: 0 }}><dt>Name</dt><dd>{selection.projection.name}</dd><dt>Extension</dt><dd>{selection.projection.extension || "None"}</dd><dt>MIME type</dt><dd>{selection.projection.mimeType}</dd><dt>Size</dt><dd>{formatBytes(selection.projection.size)} ({selection.projection.size} bytes)</dd><dt>Last modified</dt><dd>{selection.projection.lastModified ? new Date(selection.projection.lastModified).toLocaleString() : "Not available"}</dd><dt>Source</dt><dd>Local Files</dd><dt>Selection</dt><dd>{selection.projection.selectionMechanism}</dd><dt>Detected viewer</dt><dd>{selection.projection.viewerId ?? "Unsupported"}</dd><dt>Read permission</dt><dd>{selection.projection.readCapability ? "Granted" : "Unavailable"}</dd><dt>Write permission</dt><dd>{selection.projection.originalSaveCapability ? "Original file may be saved" : "Original save unavailable; use Save As"}</dd><dt>Preview</dt><dd>{prettyPreviewState[previewState]}</dd><dt>Editing</dt><dd>{selection.projection.editCapability ? "Supported text editing" : "Not supported"}</dd><dt>Dirty</dt><dd>{selection.projection.dirty ? "Yes" : "No"}</dd></dl>
      {previewUrl && selection.projection.viewerId === "image-viewer" && <div><img src={previewUrl} alt={selection.projection.name} style={{ display: "block", maxWidth: "100%", maxHeight: "32rem", objectFit: "contain" }} /><button type="button" onClick={openInBrowser}>Open in browser</button></div>}
      {previewUrl && selection.projection.viewerId === "audio-player" && <div><audio ref={setMediaRef} controls preload="metadata" src={previewUrl} aria-label={`Audio player for ${selection.projection.name}`} /><button type="button" onClick={openInBrowser}>Open in browser</button></div>}
      {previewUrl && selection.projection.viewerId === "video-player" && <div><video ref={setMediaRef} controls preload="metadata" src={previewUrl} style={{ display: "block", maxWidth: "100%", maxHeight: "32rem" }} aria-label={`Video player for ${selection.projection.name}`} /><button type="button" onClick={openInBrowser}>Open in browser</button></div>}
      {previewUrl && selection.projection.viewerId === "pdf-viewer" && <div><object data={previewUrl} type="application/pdf" aria-label={`PDF viewer for ${selection.projection.name}`} style={{ width: "100%", minHeight: "32rem" }}><p>Browser PDF preview is unavailable.</p></object><button type="button" onClick={openInBrowser}>Open in browser</button></div>}
      {selection.projection.editCapability && previewState === "AVAILABLE" && <><div style={{ display: "flex", gap: "0.5rem", flexWrap: "wrap" }}><label>Search<input value={search} onChange={(event) => setSearch(event.target.value)} /></label><label>Replace<input value={replace} onChange={(event) => setReplace(event.target.value)} /></label><button type="button" onClick={() => { if (search) { setText(text.split(search).join(replace)); setDirty(true); setSelection({ ...selection, projection: { ...selection.projection, dirty: true } }); } }}>Replace all</button></div><label>{selection.projection.viewerId === "code-editor" ? "Code editor (safe textarea fallback)" : "Editable file content"}<textarea value={displayText} onChange={(event) => { setText(event.target.value); setDirty(true); setSelection({ ...selection, projection: { ...selection.projection, dirty: true } }); }} rows={12} spellCheck={false} wrap="off" style={{ width: "100%", boxSizing: "border-box", fontFamily: "monospace" }} /></label><small>{displayText.split("\n").length} lines, {displayText.length} characters{selection.projection.viewerId === "log-viewer" ? " · display masking applied" : ""}</small></>}
      {!selection.projection.previewCapability && <div role="status"><b>Preview is not available for this file type.</b><p>View details, save a copy, or open the downloaded file using the operating system.</p></div>}
      {selection.projection.editCapability && previewState === "TOO_LARGE" && <small role="status">Preview unavailable due to size. The file remains available for Save As.</small>}
      {selection.projection.conversionCapabilities.length > 0 && <label>Output format<select value={outputMimeType ?? selection.projection.mimeType} onChange={(event) => setOutputMimeType(event.target.value)}><option value={selection.projection.mimeType}>Original format</option>{selection.projection.conversionCapabilities.filter((mimeType) => mimeType !== selection.projection.mimeType).map((mimeType) => <option key={mimeType} value={mimeType}>{mimeType === "image/jpeg" || mimeType === "image/webp" ? `${mimeType} (lossy)` : mimeType}</option>)}</select></label>}
      <div style={{ display: "flex", gap: "0.5rem", flexWrap: "wrap" }}><button type="button" onClick={() => void saveOriginal()} disabled={busy || !dirty || !selection.projection.originalSaveCapability || (outputMimeType !== undefined && outputMimeType !== selection.projection.mimeType)}>Save</button><button type="button" onClick={() => void saveCopy()} disabled={busy}>Save As / Download copy</button><button type="button" onClick={clear} disabled={busy}>Clear Selection</button></div>
    </section>}
  </section>;
}

export function FilesHubPanel({ sources, onMicrosoftAction = () => undefined, onGoogleAction = () => undefined, providerBodies = {} }: FilesHubPanelProps) {
  const [panelStates, setPanelStates] = useState<Record<PanelId, PanelState>>({ "local-files": { mode: "NORMAL", width: 100, height: 24 }, "microsoft-onedrive": { mode: "NORMAL", width: 100, height: 12 }, "microsoft-sharepoint": { mode: "NORMAL", width: 100, height: 12 }, "google-drive": { mode: "NORMAL", width: 100, height: 12 } });
  const actionFor = (source: FileSourceProjection): (() => void) => { if (source.sourceId === "microsoft-onedrive") return () => onMicrosoftAction(source.availability === "CONNECTED" ? "OPEN" : source.availability === "ERROR" ? "RECONNECT" : "CONNECT"); if (source.sourceId === "google-drive") return () => onGoogleAction(source.availability === "CONNECTED" ? "OPEN" : "CONNECT"); return () => undefined; };
  const maximised = Object.entries(panelStates).find(([, state]) => state.mode === "MAXIMISED")?.[0] as PanelId | undefined;
  return <section aria-labelledby="files-hub-heading" style={{ display: "grid", gap: "1rem", padding: "1rem", minWidth: 0, maxWidth: "100%", overflowX: "hidden" }}><header><h2 id="files-hub-heading" style={{ margin: 0 }}>Files</h2><p style={{ margin: "0.35rem 0 0" }}>Browse local and connected file sources.</p></header><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(min(20rem, 100%), 1fr))", gap: "0.8rem", minWidth: 0, alignItems: "start" }}>{sources.map((source) => { const id = (source.sourceId === "local" ? "local-files" : source.sourceId) as PanelId; const state = panelStates[id]; if (maximised && maximised !== id) return null; return <FilesProviderSubPanel key={source.sourceId} id={id} title={source.displayName} state={state} onState={(next) => setPanelStates((current) => { const nextStates = { ...current }; (Object.keys(nextStates) as PanelId[]).forEach((panelId) => { if (panelId !== id && next.mode === "MAXIMISED") nextStates[panelId] = { ...nextStates[panelId], mode: "NORMAL" }; }); nextStates[id] = next; return nextStates; })}>
    {source.sourceId === "local" ? <LocalFileWorkspace /> : providerBodies[id] ?? <div style={{ display: "grid", gap: "0.6rem", minWidth: 0 }}><span aria-live="polite">{source.availability}</span><small style={{ overflowWrap: "anywhere" }}>{source.capabilities.filter((capability) => capability.enabled).map((capability) => capability.operation).join(", ") || "No operations currently available"}</small><button type="button" style={{ alignSelf: "flex-start", width: "fit-content", maxWidth: "100%" }} onClick={actionFor(source)}>{source.availability === "CONNECTED" ? `Open ${source.displayName}` : source.availability === "ERROR" ? "Reconnect" : "Connect"}</button>{source.diagnostic?.reasonCode && <small role="status" style={{ overflowWrap: "anywhere" }}>{source.diagnostic.reasonCode}</small>}</div>}
  </FilesProviderSubPanel>; })}</div>{!sources.some((source) => source.sourceId === "local") && <small role="alert">Local Files source is unavailable.</small>}</section>;
}