import { useEffect, useState } from "react";
import type { Note, NoteDateBucket } from "@onyx/workspace-contracts";
import { noteDateBucket, notesRepository, notesUiStateKey, type NotesSearchResult, type NotesSort } from "../notesRepository";

const NAV_ITEMS: readonly { id: NoteDateBucket | "PINNED"; label: string }[] = [
  { id: "PINNED", label: "Pinned" }, { id: "TODAY", label: "Today" }, { id: "THIS_WEEK", label: "This Week" },
  { id: "THIS_MONTH", label: "This Month" }, { id: "THIS_YEAR", label: "This Year" }, { id: "ALL_NOTES", label: "All Notes" }, { id: "ARCHIVE", label: "Archive" },
];
type NotesUiState = { selectedId?: string; query: string; filter: NoteDateBucket | "PINNED"; sort: NotesSort; pinned: boolean; includeArchived: boolean; hasFileReferences: boolean; recent: boolean; category: string; tag: string; scrollTop?: number };
const defaultState: NotesUiState = { query: "", filter: "ALL_NOTES", sort: "UPDATED_DESC", pinned: false, includeArchived: false, hasFileReferences: false, recent: false, category: "", tag: "" };
function readUiState(accountScope: string): NotesUiState { try { return typeof localStorage === "undefined" ? defaultState : { ...defaultState, ...(JSON.parse(localStorage.getItem(notesUiStateKey(accountScope)) ?? "{}") as Partial<NotesUiState>) }; } catch { return defaultState; } }
function resultText(result: NotesSearchResult, onSelect: () => void) { return <button type="button" className="note-row" onClick={onSelect}><strong>{result.note.pinned ? "★ " : ""}{result.note.title}</strong><span>{result.snippet || "Empty note"}</span><small>{result.note.tags.length ? `#${result.note.tags.join(" #")} · ` : ""}{result.note.category ?? "Uncategorised"} · {new Date(result.note.updatedAt).toLocaleString()} · {result.fileReferenceCount} file reference{result.fileReferenceCount === 1 ? "" : "s"}</small></button>; }

export function NotesPanel({ accountScope = "local-default" }: { readonly accountScope?: string }) {
  const repository = notesRepository.forAccount(accountScope);
  const [ui, setUi] = useState<NotesUiState>(() => readUiState(accountScope));
  const [notes, setNotes] = useState<readonly Note[]>(() => repository.getNotes({ includeArchived: true }));
  const [draft, setDraft] = useState<Pick<Note, "title" | "content"> | null>(null);
  const [referenceDraft, setReferenceDraft] = useState({ fileId: "", displayName: "", provider: "local", fileType: "" });
  const [recentSearches, setRecentSearches] = useState<readonly string[]>(() => repository.getRecentSearches());
  const refresh = () => setNotes(repository.getNotes({ includeArchived: true }));
  useEffect(() => { try { localStorage.setItem(notesUiStateKey(accountScope), JSON.stringify(ui)); } catch { /* optional UI cache */ } }, [accountScope, ui]);
  const options = { includeArchived: ui.includeArchived || ui.filter === "ARCHIVE", pinned: ui.pinned || ui.filter === "PINNED" ? true : undefined, hasFileReferences: ui.hasFileReferences ? true : undefined, recent: ui.recent ? true : undefined, bucket: ui.filter === "PINNED" ? undefined : ui.filter, category: ui.category || undefined, tag: ui.tag || undefined, sort: ui.sort };
  const results = ui.query.trim() ? repository.searchNotesDetailed(ui.query, options) : repository.getNotes(options).map((note) => ({ note, snippet: `${note.title}\n${note.content}`.trim().slice(0, 180), fileReferenceCount: note.fileReferences.length }));
  const selected = notes.find((note) => note.noteId === ui.selectedId);
  const related = selected ? repository.getRelatedNotes(selected.noteId, 4) : [];
  const updateUi = (change: Partial<NotesUiState>) => setUi((current) => ({ ...current, ...change }));
  const saveDraft = () => { if (!draft || !selected) return; repository.updateNote(selected.noteId, draft); refresh(); };
  const selectNote = (note: Note) => { saveDraft(); repository.recordNoteOpened(note.noteId); updateUi({ selectedId: note.noteId }); setDraft({ title: note.title, content: note.content }); };
  const startNew = () => { saveDraft(); const created = repository.createNote(); updateUi({ selectedId: created.noteId }); setDraft({ title: created.title, content: created.content }); refresh(); };
  const submitSearch = () => { repository.recordSearch(ui.query); setRecentSearches(repository.getRecentSearches()); };
  const addReference = () => { if (!selected) return; saveDraft(); repository.updateNote(selected.noteId, { fileReferences: [...selected.fileReferences, { referenceId: `reference-${Date.now()}`, fileId: referenceDraft.fileId, provider: referenceDraft.provider, displayName: referenceDraft.displayName, fileType: referenceDraft.fileType || undefined, referencedAt: new Date().toISOString() }] }); setReferenceDraft({ fileId: "", displayName: "", provider: "local", fileType: "" }); refresh(); };
  return <section className="notes-panel" aria-labelledby="notes-heading">
    <header className="notes-header"><div><p className="notes-kicker">Local knowledge layer</p><h2 id="notes-heading">Notes</h2><p>Offline search and file references. Intelligence is disabled.</p></div><button type="button" onClick={startNew}>+ New Note</button></header>
    <div className="notes-searchbar"><input aria-label="Search notes" value={ui.query} onChange={(event) => updateUi({ query: event.target.value })} onKeyDown={(event) => { if (event.key === "Enter") submitSearch(); }} placeholder="Search notes, phrases, or #tags" /><button type="button" onClick={submitSearch}>Search</button><select aria-label="Sort notes" value={ui.sort} onChange={(event) => updateUi({ sort: event.target.value as NotesSort })}><option value="UPDATED_DESC">Updated newest</option><option value="UPDATED_ASC">Updated oldest</option><option value="CREATED_DESC">Created newest</option><option value="CREATED_ASC">Created oldest</option><option value="TITLE_ASC">A-Z</option><option value="TITLE_DESC">Z-A</option><option value="PINNED_FIRST">Pinned first</option></select></div>
    <div className="notes-layout"><nav aria-label="Notes navigation" className="notes-nav"><label>Search filters</label>{NAV_ITEMS.map((item) => <button type="button" key={item.id} className={ui.filter === item.id ? "active" : ""} onClick={() => updateUi({ filter: item.id })}>{item.label}<span>{notes.filter((note) => item.id === "PINNED" ? note.pinned && !note.archived : item.id === "ARCHIVE" ? note.archived : !note.archived && (item.id === "ALL_NOTES" || noteDateBucket(note.updatedAt) === item.id)).length}</span></button>)}<label><input type="checkbox" checked={ui.hasFileReferences} onChange={(event) => updateUi({ hasFileReferences: event.target.checked })} /> Has file references</label><label><input type="checkbox" checked={ui.pinned} onChange={(event) => updateUi({ pinned: event.target.checked })} /> Pinned</label><label><input type="checkbox" checked={ui.includeArchived} onChange={(event) => updateUi({ includeArchived: event.target.checked })} /> Include archived</label><label><input type="checkbox" checked={ui.recent} onChange={(event) => updateUi({ recent: event.target.checked })} /> Recently opened</label><input aria-label="Filter category" placeholder="Category" value={ui.category} onChange={(event) => updateUi({ category: event.target.value })} /><input aria-label="Filter tag" placeholder="Tag" value={ui.tag} onChange={(event) => updateUi({ tag: event.target.value.replace(/^#/, "") })} />{recentSearches.length > 0 && <aside className="notes-recent-searches"><strong>Recent searches</strong>{recentSearches.map((query) => <button type="button" key={query} onClick={() => updateUi({ query })}>{query}</button>)}<button type="button" onClick={() => { repository.clearRecentSearches(); setRecentSearches([]); }}>Clear history</button></aside>}</nav>
      <div className="notes-list" aria-label="Notes results" ref={(element) => { if (element && ui.scrollTop) element.scrollTop = ui.scrollTop; }} onScroll={(event) => updateUi({ scrollTop: event.currentTarget.scrollTop })}><div className="notes-result-summary" aria-live="polite">{results.length} result{results.length === 1 ? "" : "s"}</div>{results.length === 0 ? <div className="notes-empty"><strong>No Notes Found</strong><span>Try clearing search or filters.</span><button type="button" onClick={startNew}>Create Note</button><button type="button" onClick={() => updateUi({ query: "" })}>Clear Search</button></div> : results.map((result) => <div key={result.note.noteId}>{resultText(result, () => selectNote(result.note))}</div>)}</div>
      <article className="notes-editor" aria-label="Note editor">{draft ? <><input aria-label="Note title" value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} onBlur={saveDraft} /><textarea aria-label="Note content" value={draft.content} onChange={(event) => setDraft({ ...draft, content: event.target.value })} onBlur={saveDraft} rows={12} /><div className="notes-editor-meta"><span>{draft.content.length} characters</span><span>{selected ? `Last modified ${new Date(selected.updatedAt).toLocaleString()}` : "Not saved"}</span></div><div className="notes-actions"><button type="button" onClick={saveDraft}>Save</button>{selected && <><button type="button" onClick={() => { selected.pinned ? repository.unpinNote(selected.noteId) : repository.pinNote(selected.noteId); refresh(); }}>{selected.pinned ? "Unpin" : "Pin"}</button><button type="button" onClick={() => { saveDraft(); selected.archived ? repository.restoreNote(selected.noteId) : repository.archiveNote(selected.noteId); refresh(); }}>{selected.archived ? "Restore" : "Archive"}</button><button type="button" onClick={() => { repository.deleteNote(selected.noteId); updateUi({ selectedId: undefined }); setDraft(null); refresh(); }}>Delete</button></>}</div>{selected && <fieldset className="notes-reference-form"><legend>Link a file reference</legend><input aria-label="File ID" placeholder="File ID" value={referenceDraft.fileId} onChange={(event) => setReferenceDraft({ ...referenceDraft, fileId: event.target.value })} /><input aria-label="File display name" placeholder="Display name" value={referenceDraft.displayName} onChange={(event) => setReferenceDraft({ ...referenceDraft, displayName: event.target.value })} /><button type="button" disabled={!referenceDraft.fileId || !referenceDraft.displayName} onClick={addReference}>Add reference</button></fieldset>}{selected?.fileReferences.length ? <aside><strong>References</strong>{selected.fileReferences.map((reference) => <div key={reference.referenceId}>{reference.displayName} <small>{reference.fileType ?? reference.provider}</small></div>)}</aside> : null}{related.length > 0 && <aside className="notes-related"><strong>Related notes</strong>{related.map((note) => <button type="button" key={note.noteId} onClick={() => selectNote(note)}>{note.title}</button>)}</aside>}</> : <p>Select a note or create one to begin.</p>}</article>
    </div>
  </section>;
}
