import {GlassPanel,MetricBar,MiniSpark,RingMetric}from"./GlassKit";const trend=[12,16,14,23,20,31,28,40,37,52,48,64];
export function OnyxDashboard({activePanel}:{activePanel:string|null}){const now=new Date(),s=(id:string)=>activePanel===id;return <div className="scene-grid onyx-grid"><div className="scene-column left-column">
<GlassPanel panelId="home" selected={s("home")} title="Executive Context" icon="◷"><div className="onyx-context"><strong>{now.toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</strong><span>{now.toLocaleDateString([],{weekday:"long",day:"2-digit",month:"long",year:"numeric"})}</span><small>Push-to-talk command mode</small></div></GlassPanel>
<GlassPanel panelId="business" selected={s("business")} title="Business Overview"><div className="kpi-row"><div><small>Revenue MTD</small><strong>$128.4k</strong><em>↑12.4%</em></div><MiniSpark values={trend}/></div><div className="kpi-row"><div><small>Active Projects</small><strong>24</strong><em>↑8.33%</em></div><MiniSpark values={[64,48,52,37,40,28,31,20,23,14,16,12]} color="mint"/></div><MetricBar label="Tasks Completed" value={86}/></GlassPanel>
<GlassPanel panelId="finance" selected={s("finance")} title="Finance Tracker"><div className="balance"><small>Total Balance</small><strong>$512,230.50</strong><em>↑7.6%</em></div><div className="finance-layout"><RingMetric value={72} label="Invested" color="blue"/><div><MetricBar label="Investments" value={72}/><MetricBar label="Savings" value={18} color="mint"/><MetricBar label="Expenses" value={10} color="violet"/></div></div></GlassPanel>
<GlassPanel panelId="social" selected={s("social")} title="Social Monitor"><div className="social-grid"><span>𝕏 <b>12.4K</b></span><span>◎ <b>8.7K</b></span><span>in <b>5.1K</b></span><span>▶ <b>3.3K</b></span></div></GlassPanel>
<GlassPanel panelId="email" selected={s("email")} title="Email" className="aux-panel"><p>Five priority email summaries are ready.</p></GlassPanel>
</div><div className="scene-column right-column">
<GlassPanel panelId="calendar" selected={s("calendar")} title="Calendar"><ul className="timeline"><li><i/>10:00 AM <b>Strategy Meeting</b></li><li><i className="violet"/>12:30 PM <b>Client Presentation</b></li><li><i className="mint"/>04:00 PM <b>Product Review</b></li></ul></GlassPanel>
<GlassPanel panelId="smart-home" selected={s("smart-home")} title="Smart Home"><ul className="status-list"><li>Living Room <b>22°C</b></li><li>Lights <b>12 On</b></li><li>Security <b>Armed</b></li><li>Garage Door <b>Closed</b></li></ul></GlassPanel>
<GlassPanel panelId="weather" selected={s("weather")} title="Weather"><div className="weather-row"><strong>28°C</strong><div><b>Light Rain</b><small>Chennai, India</small></div></div></GlassPanel>
<GlassPanel panelId="system-health" selected={s("system-health")} title="System Performance"><div className="performance-row"><RingMetric value={23} label="CPU"/><RingMetric value={46} label="Memory" color="violet"/><RingMetric value={68} label="Storage" color="blue"/><RingMetric value={92} label="Network" color="mint"/></div></GlassPanel>
<GlassPanel panelId="news" selected={s("news")} title="News Briefing" className="aux-panel"><p>Markets and technology briefs are ready.</p></GlassPanel>
<GlassPanel panelId="automation" selected={s("automation")} title="Automation" className="aux-panel"><p>Morning brief and local backup are enabled.</p></GlassPanel>
</div></div>}
