export type VoiceEngine="system"|"azure"|"elevenlabs";export type VoiceDetail="brief"|"standard"|"detailed";
export interface VoicePreferences{enabled:boolean;engine:VoiceEngine;systemVoice?:string;azureVoice?:string;elevenLabsVoice?:string;language:string;rate:number;pitch:number;volume:number;detail:VoiceDetail;privacy:"private"|"standard"|"full";}
export interface VoiceStatus{engine:VoiceEngine;ready:boolean;diagnostic:string;}
const key="onyx.voice.preferences";export const defaultVoicePreferences:VoicePreferences={enabled:true,engine:"system",language:"en-IN",rate:1,pitch:1,volume:.9,detail:"brief",privacy:"standard"};
export const loadVoicePreferences=():VoicePreferences=>{try{return{...defaultVoicePreferences,...JSON.parse(localStorage.getItem(key)??"{}")}}catch{return defaultVoicePreferences}};export const saveVoicePreferences=(p:VoicePreferences)=>localStorage.setItem(key,JSON.stringify(p));
export const availableSystemVoices=()=>typeof speechSynthesis==="undefined"?[]:speechSynthesis.getVoices();
export class VoiceManager{private audio?:HTMLAudioElement;stop(){if(typeof speechSynthesis!=="undefined")speechSynthesis.cancel();this.audio?.pause();this.audio=undefined}pause(){if(this.audio)this.audio.pause();else speechSynthesis?.pause()}resume(){if(this.audio)void this.audio.play();else speechSynthesis?.resume()}
 async status(engine:VoiceEngine):Promise<VoiceStatus>{if(engine==="system")return{engine,ready:typeof speechSynthesis!=="undefined",diagnostic:typeof speechSynthesis!=="undefined"?"System voice ready.":"System voice unavailable."};try{const r=await fetch(`/.netlify/functions/voice-status?provider=${engine}`);const j=await r.json();return{engine,ready:Boolean(j.ready),diagnostic:j.diagnostic??"Voice provider unavailable."}}catch{return{engine,ready:false,diagnostic:"Voice backend unavailable."}}}
 private speakSystem(text:string,p:VoicePreferences){if(typeof speechSynthesis==="undefined")return false;this.stop();const u=new SpeechSynthesisUtterance(text);u.lang=p.language;u.rate=p.rate;u.pitch=p.pitch;u.volume=p.volume;u.voice=availableSystemVoices().find(v=>v.name===p.systemVoice)??availableSystemVoices().find(v=>v.lang===p.language)??null;speechSynthesis.speak(u);return true;}
 async speak(text:string,p:VoicePreferences):Promise<{engine:VoiceEngine;fallback:boolean;message?:string}>{if(!p.enabled)return{engine:p.engine,fallback:false};if(p.engine==="system"){this.speakSystem(text,p);return{engine:"system",fallback:false}}try{const s=await this.status(p.engine);if(!s.ready)throw new Error(s.diagnostic);const r=await fetch("/.netlify/functions/voice-synthesize",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({provider:p.engine,text,voiceId:p.engine==="azure"?p.azureVoice:p.elevenLabsVoice,language:p.language})});if(!r.ok)throw new Error("Premium voice synthesis failed.");this.stop();this.audio=new Audio(URL.createObjectURL(await r.blob()));await this.audio.play();return{engine:p.engine,fallback:false}}catch{this.speakSystem(text,p);return{engine:"system",fallback:true,message:"VOICE CONNECTION NOT ACTIVE · USING SYSTEM VOICE"}}}}
