import type { ResourceOwnershipRecord, SharingGrant } from "./model";
import { MODE_CAPABILITY_MATRIX, MODE_NAMES } from "./mode-policy";

export const resourceFixtures = {
  rahulMemory: {
    resourceId: "memory_owner_001",
    resourceClass: "memory-namespace",
    householdId: "household_rahul",
    owningAccountId: "acct_rahul",
    owningMembershipId: "membership_rahul",
    ownerType: "rahul",
    visibility: "rahul-only",
    disclosureClassification: "rahul-only",
    sourceClassification: "owner",
    purpose: "memory-ownership",
    policyVersion: "resource-policy-1",
    creationTime: "2026-08-23T12:00:00.000Z",
    provenanceReference: "fixture-provenance-memory",
    evidenceReference: "evidence-memory-001",
    retentionClassification: "owner-only-retention",
    redactionClassification: "none",
    sharingGrantRequired: false,
    auditRequired: true
  } satisfies ResourceOwnershipRecord,
  householdSharedMemory: {
    resourceId: "memory_household_001",
    resourceClass: "memory-namespace",
    householdId: "household_rahul",
    owningAccountId: "acct_rahul",
    owningMembershipId: "membership_rahul",
    ownerType: "household",
    visibility: "household-shared",
    disclosureClassification: "household-shared",
    sourceClassification: "household",
    purpose: "memory-ownership",
    policyVersion: "resource-policy-1",
    creationTime: "2026-08-23T12:00:00.000Z",
    provenanceReference: "fixture-provenance-household",
    evidenceReference: "evidence-household-memory-001",
    retentionClassification: "household-retention",
    redactionClassification: "summary-only",
    sharingGrantRequired: false,
    auditRequired: false
  } satisfies ResourceOwnershipRecord,
  projectJourney: {
    resourceId: "journey_001",
    resourceClass: "project-journey",
    householdId: "household_rahul",
    owningAccountId: "acct_rahul",
    owningMembershipId: "membership_rahul",
    ownerType: "rahul",
    visibility: "rahul-only",
    disclosureClassification: "rahul-only",
    sourceClassification: "project-journey",
    purpose: "history-boundary",
    policyVersion: "resource-policy-1",
    creationTime: "2026-08-23T12:00:00.000Z",
    provenanceReference: "fixture-provenance-journey",
    evidenceReference: "evidence-journey-001",
    retentionClassification: "owner-only-retention",
    redactionClassification: "detailed-history-hidden",
    sharingGrantRequired: true,
    auditRequired: true
  } satisfies ResourceOwnershipRecord,
  evidenceRecord: {
    resourceId: "evidence_001",
    resourceClass: "evidence",
    householdId: "household_rahul",
    owningAccountId: "acct_rahul",
    owningMembershipId: "membership_rahul",
    ownerType: "account",
    visibility: "private",
    disclosureClassification: "private",
    sourceClassification: "evidence",
    purpose: "evidence-integrity",
    policyVersion: "resource-policy-1",
    creationTime: "2026-08-23T12:00:00.000Z",
    provenanceReference: "fixture-provenance-evidence",
    evidenceReference: "evidence-record-001",
    retentionClassification: "evidence-retention",
    redactionClassification: "evidence-redacted",
    sharingGrantRequired: true,
    auditRequired: true
  } satisfies ResourceOwnershipRecord,
  connector: {
    resourceId: "connector_001",
    resourceClass: "connector-registration",
    householdId: "household_rahul",
    owningAccountId: "acct_rahul",
    owningMembershipId: "membership_rahul",
    ownerType: "account",
    visibility: "private",
    disclosureClassification: "private",
    sourceClassification: "connector",
    purpose: "connector-governance",
    policyVersion: "resource-policy-1",
    creationTime: "2026-08-23T12:00:00.000Z",
    provenanceReference: "fixture-provenance-connector",
    evidenceReference: "evidence-connector-001",
    retentionClassification: "account-retention",
    redactionClassification: "credential-hidden",
    sharingGrantRequired: true,
    auditRequired: true
  } satisfies ResourceOwnershipRecord,
  cache: {
    resourceId: "cache_001",
    resourceClass: "cache",
    householdId: "household_rahul",
    owningAccountId: "acct_rahul",
    owningMembershipId: "membership_rahul",
    ownerType: "account",
    visibility: "private",
    disclosureClassification: "private",
    sourceClassification: "memory",
    purpose: "cache-isolation",
    policyVersion: "resource-policy-1",
    creationTime: "2026-08-23T12:00:00.000Z",
    provenanceReference: "fixture-provenance-cache",
    evidenceReference: "evidence-cache-001",
    retentionClassification: "account-retention",
    redactionClassification: "cache-metadata-hidden",
    sharingGrantRequired: false,
    auditRequired: true
  } satisfies ResourceOwnershipRecord
};

export const validGrant: SharingGrant = {
  grantId: "grant_001",
  grantingAccountId: "acct_rahul",
  receivingAccountId: "acct_family",
  resourceClass: "memory-namespace",
  exactOperation: "read",
  exactPurpose: "memory-ownership",
  disclosureClass: "household-shared",
  sourceClasses: ["owner"],
  expiry: "2026-08-30T12:00:00.000Z",
  policyVersion: "resource-policy-1",
  status: "active",
  auditRequired: true,
  evidenceReference: "grant-evidence-001"
};

export const modeAcceptanceRegistry = {
  MODE_001: "Canonical operating modes",
  MODE_002: "Provider-neutral mode policy",
  MODE_003: "Capability matrix",
  MODE_004: "Budget envelopes",
  MODE_005: "Authorized transition request",
  MODE_006: "Reversible transitions",
  MODE_007: "Canonical data and memory preservation",
  MODE_008: "Session and authority revalidation",
  MODE_009: "No stale approval or delegation reactivation",
  MODE_010: "Connector preservation and revocation enforcement",
  MODE_011: "VACATION critical-capability preservation",
  MODE_012: "HIBERNATION non-destructive preservation",
  MODE_013: "Audit, evidence, and provenance",
  MODE_014: "Rollback and recovery",
  MODE_015: "Household isolation and gateway readiness",
  MODE_016: "No cloud mutation or deployment"
};

export const acceptedModes = MODE_NAMES;
export const capabilityMatrixFixture = MODE_CAPABILITY_MATRIX;
