export const FAILURE_CLASSES = [
  "LEASE_LOST",
  "HEARTBEAT_LOST",
  "WORKER_CRASHED",
  "STALE_WORKER_RESULT",
  "LOCK_OWNER_LOST",
  "LOCK_EXPIRED",
  "LOCK_STATE_UNCERTAIN",
  "CHECKPOINT_CAS_CONFLICT",
  "CHECKPOINT_CORRUPT",
  "CHECKPOINT_SCHEMA_MISMATCH",
  "CHECKPOINT_LINEAGE_INVALID",
  "DEPENDENCY_FAILED",
  "DEPENDENCY_CANCELLED",
  "DEPENDENCY_UNKNOWN",
  "JOIN_TIMEOUT",
  "JOIN_THRESHOLD_FAILED",
  "CANCELLATION_BLOCKED_BY_UNCERTAINTY",
  "BUDGET_WARNING",
  "BUDGET_HARD_STOP",
  "ATTEMPT_EXHAUSTED",
  "EVIDENCE_MISSING",
  "EVIDENCE_INVALID",
  "EVIDENCE_STORAGE_EXHAUSTED",
  "UNKNOWN_EXTERNAL_WRITE",
  "UNCERTAIN_REMOTE_EFFECT",
  "SCHEDULER_RESTARTED",
  "WORKFLOW_STATE_DIVERGENCE",
  "RUNTIME_STATE_DIVERGENCE",
  "SCOPE_DIVERGENCE",
  "APPROVAL_INVALIDATED",
  "PERMISSION_INVALIDATED",
  "MEMORY_SCOPE_INVALIDATED",
  "CONNECTOR_SCOPE_INVALIDATED",
  "CONTEXT_PROVENANCE_INVALID",
  "CONTEXT_POISONED",
  "CONTEXT_QUARANTINED",
  "MEMORY_TOMBSTONED",
  "PROMOTION_FAILED",
  "COUNCIL_DECISION_REQUIRED",
  "DRAFT_APPROVAL_INVALIDATED",
  "SECURITY_FAILURE",
  "PROHIBITED_EFFECT",
] as const;

export type RecoveryFailureClass = (typeof FAILURE_CLASSES)[number];

export const RECOVERY_DISPOSITIONS = [
  "NO_RECOVERY_REQUIRED",
  "CONTINUE_WITH_WARNING",
  "RETRY_CANDIDATE",
  "RESUME_CANDIDATE",
  "REASSIGNMENT_CANDIDATE",
  "WAIT_FOR_OWNER",
  "WAIT_FOR_DEPENDENCY",
  "WAIT_FOR_BUDGET",
  "CHECKPOINT_AND_STOP",
  "RELOAD_AND_REPLAN",
  "RESTART_RECONSTRUCTION",
  "STOP_AND_RECONCILE",
  "REDUCE_TO_S4",
  "REDUCE_TO_S0",
  "RECONCILE_CHECKPOINT",
  "RECONCILE_REMOTE_EFFECT",
  "RECONCILE_PROVIDER_TRUTH",
  "RECONCILE_WORKFLOW_STATE",
  "RECONCILE_RUNTIME_STATE",
  "RECONCILE_SCOPE",
  "RECONCILE_APPROVAL",
  "RECONCILE_PERMISSION",
  "RECONCILE_MEMORY_SCOPE",
  "RECONCILE_CONNECTOR_SCOPE",
  "RECONCILE_CONTEXT",
  "RECONCILE_COUNCIL_DECISION",
  "REVALIDATE_DRAFT",
  "ROLLBACK_CANDIDATE",
  "COMPENSATION_CANDIDATE",
  "ESCALATE_TO_RAHUL",
  "FAILED_SAFE",
  "PROHIBITED",
] as const;

export type RecoveryDisposition = (typeof RECOVERY_DISPOSITIONS)[number];

export interface RecoveryFailureDisposition {
  failureClass: string;
  primaryDisposition: RecoveryDisposition;
  secondaryDispositionCandidates: readonly RecoveryDisposition[];
  recoveryReasonCodes: readonly string[];
  reconciliationRequired: boolean;
}

export function projectRecoveryFailureDisposition(failureClass: string): RecoveryFailureDisposition {
  const map: Record<string, RecoveryFailureDisposition> = {
    LEASE_LOST: {
      failureClass,
      primaryDisposition: "RESUME_CANDIDATE",
      secondaryDispositionCandidates: ["RECONCILE_PROVIDER_TRUTH", "WAIT_FOR_OWNER"],
      recoveryReasonCodes: ["lease-lost"],
      reconciliationRequired: false,
    },
    HEARTBEAT_LOST: {
      failureClass,
      primaryDisposition: "WAIT_FOR_OWNER",
      secondaryDispositionCandidates: ["RECONCILE_PROVIDER_TRUTH", "RESUME_CANDIDATE"],
      recoveryReasonCodes: ["heartbeat-lost"],
      reconciliationRequired: true,
    },
    WORKER_CRASHED: {
      failureClass,
      primaryDisposition: "RECONCILE_RUNTIME_STATE",
      secondaryDispositionCandidates: ["WAIT_FOR_OWNER", "RESTART_RECONSTRUCTION"],
      recoveryReasonCodes: ["worker-crashed"],
      reconciliationRequired: true,
    },
    STALE_WORKER_RESULT: {
      failureClass,
      primaryDisposition: "RECONCILE_PROVIDER_TRUTH",
      secondaryDispositionCandidates: ["WAIT_FOR_OWNER", "FAILED_SAFE"],
      recoveryReasonCodes: ["stale-worker-result"],
      reconciliationRequired: true,
    },
    LOCK_OWNER_LOST: {
      failureClass,
      primaryDisposition: "RECONCILE_SCOPE",
      secondaryDispositionCandidates: ["WAIT_FOR_OWNER", "RECONCILE_PERMISSION"],
      recoveryReasonCodes: ["lock-owner-lost"],
      reconciliationRequired: true,
    },
    LOCK_EXPIRED: {
      failureClass,
      primaryDisposition: "RECONCILE_RUNTIME_STATE",
      secondaryDispositionCandidates: ["WAIT_FOR_OWNER", "CHECKPOINT_AND_STOP"],
      recoveryReasonCodes: ["lock-expired"],
      reconciliationRequired: true,
    },
    CHECKPOINT_CAS_CONFLICT: {
      failureClass,
      primaryDisposition: "RELOAD_AND_REPLAN",
      secondaryDispositionCandidates: ["RECONCILE_CHECKPOINT", "FAILED_SAFE"],
      recoveryReasonCodes: ["checkpoint-cas-conflict"],
      reconciliationRequired: true,
    },
    CHECKPOINT_CORRUPT: {
      failureClass,
      primaryDisposition: "RECONCILE_CHECKPOINT",
      secondaryDispositionCandidates: ["FAILED_SAFE", "RESTART_RECONSTRUCTION"],
      recoveryReasonCodes: ["checkpoint-corrupt"],
      reconciliationRequired: true,
    },
    CHECKPOINT_SCHEMA_MISMATCH: {
      failureClass,
      primaryDisposition: "RECONCILE_CHECKPOINT",
      secondaryDispositionCandidates: ["RELOAD_AND_REPLAN", "FAILED_SAFE"],
      recoveryReasonCodes: ["checkpoint-schema-mismatch"],
      reconciliationRequired: true,
    },
    BUDGET_HARD_STOP: {
      failureClass,
      primaryDisposition: "CHECKPOINT_AND_STOP",
      secondaryDispositionCandidates: ["WAIT_FOR_BUDGET", "FAILED_SAFE"],
      recoveryReasonCodes: ["budget-hard-stop"],
      reconciliationRequired: true,
    },
    WORKFLOW_STATE_DIVERGENCE: {
      failureClass,
      primaryDisposition: "REDUCE_TO_S0",
      secondaryDispositionCandidates: ["RECONCILE_WORKFLOW_STATE", "STOP_AND_RECONCILE"],
      recoveryReasonCodes: ["workflow-state-divergence"],
      reconciliationRequired: true,
    },
    RUNTIME_STATE_DIVERGENCE: {
      failureClass,
      primaryDisposition: "REDUCE_TO_S0",
      secondaryDispositionCandidates: ["RECONCILE_RUNTIME_STATE", "STOP_AND_RECONCILE"],
      recoveryReasonCodes: ["runtime-state-divergence"],
      reconciliationRequired: true,
    },
    APPROVAL_INVALIDATED: {
      failureClass,
      primaryDisposition: "RECONCILE_APPROVAL",
      secondaryDispositionCandidates: ["REVALIDATE_DRAFT", "FAILED_SAFE"],
      recoveryReasonCodes: ["approval-invalidated"],
      reconciliationRequired: true,
    },
    PERMISSION_INVALIDATED: {
      failureClass,
      primaryDisposition: "RECONCILE_PERMISSION",
      secondaryDispositionCandidates: ["FAILED_SAFE", "WAIT_FOR_OWNER"],
      recoveryReasonCodes: ["permission-invalidated"],
      reconciliationRequired: true,
    },
    MEMORY_SCOPE_INVALIDATED: {
      failureClass,
      primaryDisposition: "RECONCILE_MEMORY_SCOPE",
      secondaryDispositionCandidates: ["FAILED_SAFE", "RECONCILE_SCOPE"],
      recoveryReasonCodes: ["memory-scope-invalidated"],
      reconciliationRequired: true,
    },
    CONNECTOR_SCOPE_INVALIDATED: {
      failureClass,
      primaryDisposition: "RECONCILE_CONNECTOR_SCOPE",
      secondaryDispositionCandidates: ["FAILED_SAFE", "RECONCILE_SCOPE"],
      recoveryReasonCodes: ["connector-scope-invalidated"],
      reconciliationRequired: true,
    },
    CONTEXT_PROVENANCE_INVALID: {
      failureClass,
      primaryDisposition: "RECONCILE_CONTEXT",
      secondaryDispositionCandidates: ["FAILED_SAFE", "RECONCILE_SCOPE"],
      recoveryReasonCodes: ["context-provenance-invalid"],
      reconciliationRequired: true,
    },
    CONTEXT_POISONED: {
      failureClass,
      primaryDisposition: "RECONCILE_CONTEXT",
      secondaryDispositionCandidates: ["FAILED_SAFE", "REVALIDATE_DRAFT"],
      recoveryReasonCodes: ["context-poisoned"],
      reconciliationRequired: true,
    },
    CONTEXT_QUARANTINED: {
      failureClass,
      primaryDisposition: "RECONCILE_CONTEXT",
      secondaryDispositionCandidates: ["FAILED_SAFE", "RECONCILE_SCOPE"],
      recoveryReasonCodes: ["context-quarantined"],
      reconciliationRequired: true,
    },
    MEMORY_TOMBSTONED: {
      failureClass,
      primaryDisposition: "RECONCILE_MEMORY_SCOPE",
      secondaryDispositionCandidates: ["FAILED_SAFE", "RECONCILE_CONTEXT"],
      recoveryReasonCodes: ["memory-tombstoned"],
      reconciliationRequired: true,
    },
    PROMOTION_FAILED: {
      failureClass,
      primaryDisposition: "ROLLBACK_CANDIDATE",
      secondaryDispositionCandidates: ["RECONCILE_SCOPE", "FAILED_SAFE"],
      recoveryReasonCodes: ["promotion-failed"],
      reconciliationRequired: true,
    },
    COUNCIL_DECISION_REQUIRED: {
      failureClass,
      primaryDisposition: "ESCALATE_TO_RAHUL",
      secondaryDispositionCandidates: ["RECONCILE_COUNCIL_DECISION", "FAILED_SAFE"],
      recoveryReasonCodes: ["council-decision-required"],
      reconciliationRequired: true,
    },
    DRAFT_APPROVAL_INVALIDATED: {
      failureClass,
      primaryDisposition: "REVALIDATE_DRAFT",
      secondaryDispositionCandidates: ["RECONCILE_APPROVAL", "FAILED_SAFE"],
      recoveryReasonCodes: ["draft-approval-invalidated"],
      reconciliationRequired: true,
    },
    UNKNOWN_EXTERNAL_WRITE: {
      failureClass,
      primaryDisposition: "RECONCILE_PROVIDER_TRUTH",
      secondaryDispositionCandidates: ["WAIT_FOR_OWNER", "FAILED_SAFE"],
      recoveryReasonCodes: ["unknown-external-write"],
      reconciliationRequired: true,
    },
    UNCERTAIN_REMOTE_EFFECT: {
      failureClass,
      primaryDisposition: "RECONCILE_PROVIDER_TRUTH",
      secondaryDispositionCandidates: ["FAILED_SAFE", "WAIT_FOR_OWNER"],
      recoveryReasonCodes: ["uncertain-remote-effect"],
      reconciliationRequired: true,
    },
    SCHEDULER_RESTARTED: {
      failureClass,
      primaryDisposition: "RELOAD_AND_REPLAN",
      secondaryDispositionCandidates: ["REDUCE_TO_S0", "RECONCILE_RUNTIME_STATE"],
      recoveryReasonCodes: ["scheduler-restarted"],
      reconciliationRequired: true,
    },
    EVIDENCE_MISSING: {
      failureClass,
      primaryDisposition: "FAILED_SAFE",
      secondaryDispositionCandidates: ["RECONCILE_SCOPE", "CHECKPOINT_AND_STOP"],
      recoveryReasonCodes: ["evidence-missing"],
      reconciliationRequired: true,
    },
    EVIDENCE_INVALID: {
      failureClass,
      primaryDisposition: "FAILED_SAFE",
      secondaryDispositionCandidates: ["RECONCILE_PROVIDER_TRUTH", "CHECKPOINT_AND_STOP"],
      recoveryReasonCodes: ["evidence-invalid"],
      reconciliationRequired: true,
    },
    ATTEMPT_EXHAUSTED: {
      failureClass,
      primaryDisposition: "FAILED_SAFE",
      secondaryDispositionCandidates: ["RECONCILE_PROVIDER_TRUTH", "WAIT_FOR_BUDGET"],
      recoveryReasonCodes: ["attempt-exhausted"],
      reconciliationRequired: true,
    },
  };

  const disposition = map[failureClass];
  if (disposition) return disposition;

  return {
    failureClass,
    primaryDisposition: "FAILED_SAFE",
    secondaryDispositionCandidates: ["RECONCILE_PROVIDER_TRUTH", "FAILED_SAFE"],
    recoveryReasonCodes: ["unknown-failure-class"],
    reconciliationRequired: true,
  };
}
