export type SemanticState = "IDLE" | "LISTENING" | "UNDERSTANDING" | "THINKING" | "SPEAKING" | "APPROVAL_REQUIRED" | "PRIVACY_RESTRICTED" | "RECOVERING";
export interface TVCapabilityProfile { readonly profile: "premium" | "standard" | "reduced"; readonly max_width: number; readonly max_height: number; readonly supports_captions: boolean; readonly supports_audio: boolean; }
export function getTVCapabilityProfile(): TVCapabilityProfile { return Object.freeze({ profile: "premium", max_width: 1920, max_height: 1080, supports_captions: true, supports_audio: true }); }
export function getReadabilityForTenFoot(profile: TVCapabilityProfile): { min_font_size: number; line_height: number; safe_margin: number } { return Object.freeze({ min_font_size: profile.profile === "reduced" ? 18 : 16, line_height: 1.5, safe_margin: 5 }); }
export interface SafeZone { readonly x_min: number; readonly x_max: number; readonly y_min: number; readonly y_max: number; readonly valid: boolean; }
export function getSafeZone(): SafeZone { return Object.freeze({ x_min: 60, x_max: 1860, y_min: 60, y_max: 1020, valid: true }); }
export function validateBoundsInSafeZone(x: number, y: number, w: number, h: number): boolean { const z = getSafeZone(); return x >= z.x_min && x + w <= z.x_max && y >= z.y_min && y + h <= z.y_max && z.valid; }
export interface FocusGraph { readonly current_region: string; readonly valid_targets: string[]; readonly movement_allowed: boolean; readonly order_stable: boolean; }
export function getFocusGraph(state: SemanticState): FocusGraph { const targets = state === "SPEAKING" ? ["character", "captions", "next"] : ["character", "world", "info"]; return Object.freeze({ current_region: "character", valid_targets: targets, movement_allowed: true, order_stable: true }); }
export function rejectInvalidFocusTarget(region: string, valid_targets: string[]): boolean { return !valid_targets.includes(region); }
export interface TVPresentationMode { readonly state: SemanticState; readonly passive: boolean; readonly active_alt: boolean; readonly ambient_enabled: boolean; }
export function getPresentationMode(state: SemanticState): TVPresentationMode { const passive = ["IDLE", "LISTENING", "THINKING"].includes(state); return Object.freeze({ state, passive, active_alt: !passive, ambient_enabled: state !== "PRIVACY_RESTRICTED" }); }
export function sharedRoomPrivacy(state: SemanticState): { privacy_level: "none" | "minimal" | "full"; approval_required: boolean } { return Object.freeze({ privacy_level: state === "PRIVACY_RESTRICTED" ? "full" : state === "APPROVAL_REQUIRED" ? "minimal" : "none", approval_required: state === "APPROVAL_REQUIRED" }); }
export interface CharacterBinding { readonly character_id: string; readonly world_id: string; readonly mutable: false; }
export function createCharacterBinding(char: string, world: string): CharacterBinding { return Object.freeze({ character_id: char, world_id: world, mutable: false }); }
export function captionsAvailable(state: SemanticState): boolean { return ["SPEAKING", "APPROVAL_REQUIRED"].includes(state); }
export function accessibilityMode(state: SemanticState, high_contrast: boolean, reduced_motion: boolean): { mode: string; enforced: boolean } { return Object.freeze({ mode: high_contrast || reduced_motion ? "adaptive" : "standard", enforced: state === "PRIVACY_RESTRICTED" }); }
export function performanceTier(available_bandwidth: number): { tier: "full" | "optimized" | "minimal"; motion: "full" | "reduced" | "static"; resolution: "1080p" | "720p" | "480p" } { const tier = available_bandwidth > 10 ? "full" : available_bandwidth > 5 ? "optimized" : "minimal"; const m = tier === "full" ? "full" : tier === "optimized" ? "reduced" : "static"; const r = tier === "full" ? "1080p" : tier === "optimized" ? "720p" : "480p"; return Object.freeze({ tier, motion: m, resolution: r }); }
export function isFirstClassTV(has_remote: boolean, requires_cast: boolean): boolean { return !requires_cast; }
export function approvalCoordinationTV(state: SemanticState): { approval_visible: boolean; approval_actionable: false; approval_applies: boolean } { return Object.freeze({ approval_visible: state === "APPROVAL_REQUIRED", approval_actionable: false, approval_applies: state === "APPROVAL_REQUIRED" }); }
export function privacyCoordinationTV(state: SemanticState): { privacy_enforced: boolean; content_minimized: boolean; audio_muted: boolean } { const isPrivate = state === "PRIVACY_RESTRICTED"; return Object.freeze({ privacy_enforced: isPrivate, content_minimized: isPrivate, audio_muted: isPrivate }); }
export function recoveryCoordinationTV(state: SemanticState): { fallback_available: boolean; fallback_active: boolean; recovery_visible: boolean } { return Object.freeze({ fallback_available: state === "RECOVERING", fallback_active: state === "RECOVERING", recovery_visible: state === "RECOVERING" }); }
