export type SemanticState = "IDLE" | "LISTENING" | "UNDERSTANDING" | "THINKING" | "SPEAKING" | "APPROVAL_REQUIRED" | "PRIVACY_RESTRICTED" | "RECOVERING";
export interface WorldRegistry { readonly id: string; readonly name: string; readonly category: "operations-center" | "future-city" | "abstract"; readonly available: boolean; readonly canFallback: boolean; }
export function getOperationsCenter(): WorldRegistry { return Object.freeze({ id: "operations-center-v1", name: "Operations Center", category: "operations-center", available: true, canFallback: false }); }
export function getFutureCity(): WorldRegistry { return Object.freeze({ id: "future-city-v1", name: "Future City", category: "future-city", available: true, canFallback: false }); }
export function getAbstractWorldFallback(): WorldRegistry { return Object.freeze({ id: "abstract-fallback", name: "Abstract Environment", category: "abstract", available: true, canFallback: true }); }
export function rejectInvalidWorld(worldId: string): boolean { return !["operations-center-v1", "future-city-v1", "abstract-fallback"].includes(worldId); }
export interface WorldStateReaction { readonly world: string; readonly state: SemanticState; readonly lighting: "standard" | "operational" | "alert" | "minimal"; readonly mood: "neutral" | "responsive" | "attentive"; }
export function getWorldStateReaction(world: WorldRegistry, state: SemanticState): WorldStateReaction { const m: Record<SemanticState, "standard" | "operational" | "alert" | "minimal"> = { IDLE: "standard", LISTENING: "operational", UNDERSTANDING: "operational", THINKING: "alert", SPEAKING: "operational", APPROVAL_REQUIRED: "alert", PRIVACY_RESTRICTED: "minimal", RECOVERING: "minimal" }; return Object.freeze({ world: world.id, state, lighting: m[state] || "standard", mood: state === "IDLE" ? "neutral" : "responsive" }); }
export function isValidWorldStateTransition(from: SemanticState, to: SemanticState): boolean { const m: Record<SemanticState, SemanticState[]> = { IDLE: ["LISTENING"], LISTENING: ["UNDERSTANDING"], UNDERSTANDING: ["THINKING"], THINKING: ["SPEAKING", "UNDERSTANDING"], SPEAKING: ["IDLE"], APPROVAL_REQUIRED: ["IDLE"], PRIVACY_RESTRICTED: ["RECOVERING"], RECOVERING: ["IDLE"] }; return m[from]?.includes(to) ?? false; }
export interface AmbientLighting { readonly intensity: "dim" | "standard" | "bright"; readonly color_temp: "warm" | "neutral" | "cool"; readonly operational: false; }
export function getAmbientLighting(world: WorldRegistry, state: SemanticState): AmbientLighting { const i = state === "RECOVERING" ? "dim" : state === "THINKING" ? "bright" : "standard"; return Object.freeze({ intensity: i, color_temp: "neutral", operational: false }); }
export interface TimeOfDay { readonly hour: number; readonly period: "morning" | "afternoon" | "evening" | "night"; readonly presentational: true; }
export function getTimeOfDay(hour: number = 12): TimeOfDay { const p: "morning" | "afternoon" | "evening" | "night" = hour < 12 ? "morning" : hour < 18 ? "afternoon" : hour < 21 ? "evening" : "night"; return Object.freeze({ hour, period: p, presentational: true }); }
export type AudioIntent = "intent-none" | "intent-ambient" | "intent-speaking" | "intent-approval";
export function classifyAudioIntent(state: SemanticState): AudioIntent { const m: Record<SemanticState, AudioIntent> = { IDLE: "intent-ambient", LISTENING: "intent-ambient", UNDERSTANDING: "intent-ambient", THINKING: "intent-ambient", SPEAKING: "intent-speaking", APPROVAL_REQUIRED: "intent-approval", PRIVACY_RESTRICTED: "intent-none", RECOVERING: "intent-ambient" }; return m[state] || "intent-ambient"; }
export interface SpeakingTimingIntent { readonly state: SemanticState; readonly can_speak: boolean; readonly timing_constraint: "strict" | "flexible" | "deferred"; }
export function getSpeakingTimingIntent(state: SemanticState): SpeakingTimingIntent { return Object.freeze({ state, can_speak: state === "SPEAKING", timing_constraint: state === "SPEAKING" ? "strict" : state === "APPROVAL_REQUIRED" ? "deferred" : "flexible" }); }
export function shouldDuckAudio(state: SemanticState): boolean { return ["SPEAKING", "APPROVAL_REQUIRED"].includes(state); }
export interface AudioControlIntent { readonly state: SemanticState; readonly can_mute: boolean; readonly can_stop: boolean; readonly default_mute: boolean; }
export function getAudioControlIntent(state: SemanticState): AudioControlIntent { return Object.freeze({ state, can_mute: true, can_stop: true, default_mute: state === "PRIVACY_RESTRICTED" }); }
export function getAudioDisabledAlternative(state: SemanticState): string { return state === "SPEAKING" ? "captions" : state === "PRIVACY_RESTRICTED" ? "text-only" : "ambient-visual"; }
export function getReducedSensoryAudioMode(state: SemanticState): string { return "reduced-ambience"; }
export function isAudioPrivacyRestricted(state: SemanticState): boolean { return state === "PRIVACY_RESTRICTED"; }
export function getAudioRecoveryFallback(state: SemanticState): string { return state === "RECOVERING" ? "minimal-ambient" : "none"; }
export function ensureWorldAvailability(requested: WorldRegistry): WorldRegistry { return requested.available ? requested : getAbstractWorldFallback(); }
export function registryStable(): boolean { const o = getOperationsCenter(); const f = getFutureCity(); const fb = getAbstractWorldFallback(); return o.id === "operations-center-v1" && f.id === "future-city-v1" && fb.id === "abstract-fallback"; }
export function worldAcknowledgesApprovalRequired(world: WorldRegistry, state: SemanticState): boolean { return state === "APPROVAL_REQUIRED" && !world.canFallback; }
export function worldEnforcesPrivacy(world: WorldRegistry, state: SemanticState): boolean { return state === "PRIVACY_RESTRICTED" && world.available; }
export function worldSupportsRecovery(world: WorldRegistry): boolean { return !world.canFallback || world.id === "abstract-fallback"; }
export function worldOperationalTruthSeparated(): boolean { const l = Object.freeze({ operational: false }); const t = Object.freeze({ presentational: true }); return l.operational === false && t.presentational === true; }
