import type { ParallelSafetyClass } from "../shared/parallel-safety";
import type { RiskClass } from "../shared/risk-classes";

export interface SimulationScenarioDefinition {
  scenarioId: string;
  description: string;
  contractGroups: string[];
  requiredFixtureIds: string[];
  expectedResult: "PASS" | "BLOCKED" | "FAIL_SAFE" | "RECONCILIATION_REQUIRED";
  expectedEvidenceClasses: string[];
  riskClass: RiskClass;
  parallelSafetyClass: ParallelSafetyClass;
  liveActionPermitted: false;
  contractVersion: string;
}

export const SIMULATION_SCENARIO_DEFINITIONS: SimulationScenarioDefinition[] = [
  {
    scenarioId: "SIM_AGENT_REGISTRATION",
    description: "Governed agent registration and identity stability.",
    contractGroups: ["Shared Governance", "Track A"],
    requiredFixtureIds: ["fixture-supervising-user", "fixture-agent-onyx", "fixture-agent-nova"],
    expectedResult: "PASS",
    expectedEvidenceClasses: ["agent-registration", "identity"],
    riskClass: "R1",
    parallelSafetyClass: "READ_ONLY_PARALLEL_SAFE",
    liveActionPermitted: false,
    contractVersion: "1.0.0",
  },
  {
    scenarioId: "SIM_CAPABILITY_DECLARATION",
    description: "Capability declaration remains explicit and non-merged.",
    contractGroups: ["Track A"],
    requiredFixtureIds: ["fixture-capability-declaration", "fixture-permission-profile"],
    expectedResult: "PASS",
    expectedEvidenceClasses: ["capability"],
    riskClass: "R1",
    parallelSafetyClass: "READ_ONLY_PARALLEL_SAFE",
    liveActionPermitted: false,
    contractVersion: "1.0.0",
  },
  {
    scenarioId: "SIM_TASK_DEPENDENCY_GRAPH",
    description: "Task and dependency graph ordering remains deterministic.",
    contractGroups: ["Track A"],
    requiredFixtureIds: ["fixture-task", "fixture-dependency-graph"],
    expectedResult: "PASS",
    expectedEvidenceClasses: ["task", "dependency"],
    riskClass: "R2",
    parallelSafetyClass: "READ_ONLY_PARALLEL_SAFE",
    liveActionPermitted: false,
    contractVersion: "1.0.0",
  },
  {
    scenarioId: "SIM_LEASE_HEARTBEAT",
    description: "Lease acquisition and heartbeat progression remain valid.",
    contractGroups: ["Track A"],
    requiredFixtureIds: ["fixture-lease", "fixture-heartbeat"],
    expectedResult: "PASS",
    expectedEvidenceClasses: ["lease", "heartbeat"],
    riskClass: "R2",
    parallelSafetyClass: "READ_ONLY_PARALLEL_SAFE",
    liveActionPermitted: false,
    contractVersion: "1.0.0",
  },
  {
    scenarioId: "SIM_ABANDONED_TASK_RECOVERY",
    description: "Abandoned task recovery blocks reassignment on uncertainty.",
    contractGroups: ["Track A"],
    requiredFixtureIds: ["fixture-task", "fixture-runtime-session"],
    expectedResult: "PASS",
    expectedEvidenceClasses: ["recovery"],
    riskClass: "R2",
    parallelSafetyClass: "READ_ONLY_PARALLEL_SAFE",
    liveActionPermitted: false,
    contractVersion: "1.0.0",
  },
  {
    scenarioId: "SIM_LOCK_CONFLICT",
    description: "Lock conflicts are rejected and remain sequential.",
    contractGroups: ["Track A"],
    requiredFixtureIds: ["fixture-lock"],
    expectedResult: "PASS",
    expectedEvidenceClasses: ["lock"],
    riskClass: "R2",
    parallelSafetyClass: "SEQUENTIAL_CHECKPOINT_REQUIRED",
    liveActionPermitted: false,
    contractVersion: "1.0.0",
  },
  {
    scenarioId: "SIM_CHECKPOINT_CAS_APPLIED",
    description: "Checkpoint CAS applies only to matching canonical state.",
    contractGroups: ["Track A"],
    requiredFixtureIds: ["fixture-checkpoint", "fixture-checkpoint-cas-request"],
    expectedResult: "PASS",
    expectedEvidenceClasses: ["checkpoint", "cas"],
    riskClass: "R2",
    parallelSafetyClass: "SEQUENTIAL_CHECKPOINT_REQUIRED",
    liveActionPermitted: false,
    contractVersion: "1.0.0",
  },
  {
    scenarioId: "SIM_CHECKPOINT_CAS_STALE_WRITER",
    description: "Stale writer CAS is rejected without overwriting canonical state.",
    contractGroups: ["Track A"],
    requiredFixtureIds: ["fixture-checkpoint", "fixture-checkpoint-cas-request"],
    expectedResult: "PASS",
    expectedEvidenceClasses: ["checkpoint", "cas"],
    riskClass: "R2",
    parallelSafetyClass: "SEQUENTIAL_CHECKPOINT_REQUIRED",
    liveActionPermitted: false,
    contractVersion: "1.0.0",
  },
  {
    scenarioId: "SIM_PARALLEL_READ_ELIGIBILITY",
    description: "Read-only tasks are classified parallel-safe.",
    contractGroups: ["Track A"],
    requiredFixtureIds: ["fixture-task"],
    expectedResult: "PASS",
    expectedEvidenceClasses: ["parallel-safety"],
    riskClass: "R1",
    parallelSafetyClass: "READ_ONLY_PARALLEL_SAFE",
    liveActionPermitted: false,
    contractVersion: "1.0.0",
  },
  {
    scenarioId: "SIM_SEQUENTIAL_MUTATION_REJECTION",
    description: "Sequential mutation classes remain non-parallel by contract.",
    contractGroups: ["Track A"],
    requiredFixtureIds: ["fixture-task"],
    expectedResult: "PASS",
    expectedEvidenceClasses: ["sequential-mutation"],
    riskClass: "R2",
    parallelSafetyClass: "SEQUENTIAL_APPROVAL_REQUIRED",
    liveActionPermitted: false,
    contractVersion: "1.0.0",
  },
  {
    scenarioId: "SIM_PARALLEL_EVIDENCE_MERGE",
    description: "Evidence sequence remains deterministic under merge.",
    contractGroups: ["Track A"],
    requiredFixtureIds: ["fixture-evidence-event"],
    expectedResult: "PASS",
    expectedEvidenceClasses: ["evidence"],
    riskClass: "R1",
    parallelSafetyClass: "EVIDENCE_GENERATION_PARALLEL_SAFE",
    liveActionPermitted: false,
    contractVersion: "1.0.0",
  },
  {
    scenarioId: "SIM_CROSS_AGENT_CANCELLATION",
    description: "Cancellation waits for safe boundary and preserves lineage.",
    contractGroups: ["Track A"],
    requiredFixtureIds: ["fixture-cancellation-request", "fixture-evidence-event"],
    expectedResult: "PASS",
    expectedEvidenceClasses: ["cancellation"],
    riskClass: "R2",
    parallelSafetyClass: "READ_ONLY_PARALLEL_SAFE",
    liveActionPermitted: false,
    contractVersion: "1.0.0",
  },
  {
    scenarioId: "SIM_CANCELLATION_BLOCKED_BY_UNCERTAINTY",
    description: "Uncertainty prevents unsafe cancellation.",
    contractGroups: ["Track A"],
    requiredFixtureIds: ["fixture-cancellation-request"],
    expectedResult: "PASS",
    expectedEvidenceClasses: ["uncertainty"],
    riskClass: "R2",
    parallelSafetyClass: "READ_ONLY_PARALLEL_SAFE",
    liveActionPermitted: false,
    contractVersion: "1.0.0",
  },
  {
    scenarioId: "SIM_JOIN_BARRIER_RELEASE",
    description: "Join barrier releases only when evidence is complete.",
    contractGroups: ["Track A"],
    requiredFixtureIds: ["fixture-join-barrier"],
    expectedResult: "PASS",
    expectedEvidenceClasses: ["join-barrier"],
    riskClass: "R1",
    parallelSafetyClass: "READ_ONLY_PARALLEL_SAFE",
    liveActionPermitted: false,
    contractVersion: "1.0.0",
  },
  {
    scenarioId: "SIM_JOIN_BARRIER_BLOCKED",
    description: "Join barrier blocks on incomplete or uncertain evidence.",
    contractGroups: ["Track A"],
    requiredFixtureIds: ["fixture-join-barrier"],
    expectedResult: "PASS",
    expectedEvidenceClasses: ["join-barrier"],
    riskClass: "R1",
    parallelSafetyClass: "READ_ONLY_PARALLEL_SAFE",
    liveActionPermitted: false,
    contractVersion: "1.0.0",
  },
  {
    scenarioId: "SIM_DETERMINISTIC_AGGREGATION",
    description: "Aggregation preserves disagreement deterministically.",
    contractGroups: ["Track A"],
    requiredFixtureIds: ["fixture-aggregation-request"],
    expectedResult: "PASS",
    expectedEvidenceClasses: ["aggregation"],
    riskClass: "R2",
    parallelSafetyClass: "READ_ONLY_PARALLEL_SAFE",
    liveActionPermitted: false,
    contractVersion: "1.0.0",
  },
  {
    scenarioId: "SIM_PROMOTION_LANE_REJECTION",
    description: "Promotion is rejected without fresh R4 approval.",
    contractGroups: ["Track A"],
    requiredFixtureIds: ["fixture-promotion-lane-request", "fixture-approval"],
    expectedResult: "PASS",
    expectedEvidenceClasses: ["promotion"],
    riskClass: "R4",
    parallelSafetyClass: "PROTECTED_PROMOTION_ONLY",
    liveActionPermitted: false,
    contractVersion: "1.0.0",
  },
  {
    scenarioId: "SIM_MEMORY_TIER_RETRIEVAL",
    description: "Tiered memory retrieval preserves authority and lifecycle boundaries.",
    contractGroups: ["Track B"],
    requiredFixtureIds: ["fixture-memory-records"],
    expectedResult: "PASS",
    expectedEvidenceClasses: ["memory-tier"],
    riskClass: "R1",
    parallelSafetyClass: "READ_ONLY_PARALLEL_SAFE",
    liveActionPermitted: false,
    contractVersion: "1.0.0",
  },
  {
    scenarioId: "SIM_M1_TO_M2_PROMOTION",
    description: "M1-to-M2 promotion remains governed and non-authoritative by default.",
    contractGroups: ["Track B"],
    requiredFixtureIds: ["fixture-memory-records"],
    expectedResult: "PASS",
    expectedEvidenceClasses: ["memory-promotion"],
    riskClass: "R1",
    parallelSafetyClass: "READ_ONLY_PARALLEL_SAFE",
    liveActionPermitted: false,
    contractVersion: "1.0.0",
  },
  {
    scenarioId: "SIM_MEMORY_CORRECTION",
    description: "Corrected memory is superseded without reintroducing stale authority.",
    contractGroups: ["Track B"],
    requiredFixtureIds: ["fixture-memory-records"],
    expectedResult: "PASS",
    expectedEvidenceClasses: ["memory-correction"],
    riskClass: "R1",
    parallelSafetyClass: "READ_ONLY_PARALLEL_SAFE",
    liveActionPermitted: false,
    contractVersion: "1.0.0",
  },
  {
    scenarioId: "SIM_MEMORY_SUPERSESSION",
    description: "Superseded memory remains auditable and non-canonical.",
    contractGroups: ["Track B"],
    requiredFixtureIds: ["fixture-memory-records"],
    expectedResult: "PASS",
    expectedEvidenceClasses: ["memory-supersession"],
    riskClass: "R1",
    parallelSafetyClass: "READ_ONLY_PARALLEL_SAFE",
    liveActionPermitted: false,
    contractVersion: "1.0.0",
  },
  {
    scenarioId: "SIM_MEMORY_DELETION",
    description: "Deletion transitions preserve tombstone and propagation integrity.",
    contractGroups: ["Track B"],
    requiredFixtureIds: ["fixture-tombstone", "fixture-deletion-propagation-targets"],
    expectedResult: "PASS",
    expectedEvidenceClasses: ["memory-deletion"],
    riskClass: "R1",
    parallelSafetyClass: "READ_ONLY_PARALLEL_SAFE",
    liveActionPermitted: false,
    contractVersion: "1.0.0",
  },
  {
    scenarioId: "SIM_TOMBSTONE_PROPAGATION",
    description: "Tombstone propagation prevents resurrection through derivative indexes.",
    contractGroups: ["Track B"],
    requiredFixtureIds: ["fixture-tombstone"],
    expectedResult: "PASS",
    expectedEvidenceClasses: ["tombstone"],
    riskClass: "R1",
    parallelSafetyClass: "READ_ONLY_PARALLEL_SAFE",
    liveActionPermitted: false,
    contractVersion: "1.0.0",
  },
  {
    scenarioId: "SIM_DELETED_MEMORY_NON_RESURRECTION",
    description: "Deleted memory cannot reappear from cache, archives, or summaries.",
    contractGroups: ["Track B"],
    requiredFixtureIds: ["fixture-tombstone"],
    expectedResult: "PASS",
    expectedEvidenceClasses: ["non-resurrection"],
    riskClass: "R1",
    parallelSafetyClass: "READ_ONLY_PARALLEL_SAFE",
    liveActionPermitted: false,
    contractVersion: "1.0.0",
  },
  {
    scenarioId: "SIM_MEMORY_POISONING_QUARANTINE",
    description: "Poisoned memory is quarantined and excluded from active context.",
    contractGroups: ["Track B"],
    requiredFixtureIds: ["fixture-quarantine-record", "fixture-memory-records"],
    expectedResult: "PASS",
    expectedEvidenceClasses: ["poisoning", "quarantine"],
    riskClass: "R2",
    parallelSafetyClass: "READ_ONLY_PARALLEL_SAFE",
    liveActionPermitted: false,
    contractVersion: "1.0.0",
  },
  {
    scenarioId: "SIM_CONTEXT_ASSEMBLY",
    description: "Context pipeline preserves source precedence and provenance.",
    contractGroups: ["Track B"],
    requiredFixtureIds: ["fixture-context-package", "fixture-source-trust-evaluation"],
    expectedResult: "PASS",
    expectedEvidenceClasses: ["context"],
    riskClass: "R2",
    parallelSafetyClass: "READ_ONLY_PARALLEL_SAFE",
    liveActionPermitted: false,
    contractVersion: "1.0.0",
  },
  {
    scenarioId: "SIM_CONTEXT_PROVENANCE_FAILURE",
    description: "Invalid provenance blocks context package release.",
    contractGroups: ["Track B"],
    requiredFixtureIds: ["fixture-context-package"],
    expectedResult: "PASS",
    expectedEvidenceClasses: ["provenance"],
    riskClass: "R2",
    parallelSafetyClass: "READ_ONLY_PARALLEL_SAFE",
    liveActionPermitted: false,
    contractVersion: "1.0.0",
  },
  {
    scenarioId: "SIM_MODEL_ROUTING_LOCAL_FIRST",
    description: "Local-first routing is selected when compatible and allowed.",
    contractGroups: ["Track B"],
    requiredFixtureIds: ["fixture-model-routing-profile"],
    expectedResult: "PASS",
    expectedEvidenceClasses: ["model-routing"],
    riskClass: "R1",
    parallelSafetyClass: "READ_ONLY_PARALLEL_SAFE",
    liveActionPermitted: false,
    contractVersion: "1.0.0",
  },
  {
    scenarioId: "SIM_MODEL_ROUTING_BUDGET_FALLBACK",
    description: "Budget pressure triggers deterministic fallback without paid action.",
    contractGroups: ["Track B"],
    requiredFixtureIds: ["fixture-model-routing-profile", "fixture-token-budget"],
    expectedResult: "PASS",
    expectedEvidenceClasses: ["model-routing", "budget"],
    riskClass: "R1",
    parallelSafetyClass: "READ_ONLY_PARALLEL_SAFE",
    liveActionPermitted: false,
    contractVersion: "1.0.0",
  },
  {
    scenarioId: "SIM_CONNECTOR_ACCOUNT_ISOLATION",
    description: "Connector account attribution remains isolated and non-merged.",
    contractGroups: ["Track B", "Shared Governance"],
    requiredFixtureIds: ["fixture-connector-scope"],
    expectedResult: "PASS",
    expectedEvidenceClasses: ["connector"],
    riskClass: "R2",
    parallelSafetyClass: "CONNECTOR_READ_PARALLEL_CONDITIONAL",
    liveActionPermitted: false,
    contractVersion: "1.0.0",
  },
  {
    scenarioId: "SIM_COUNCIL_MODE_AGREEMENT",
    description: "Council mode agreement remains visible without expanding authority.",
    contractGroups: ["Track B"],
    requiredFixtureIds: ["fixture-council-session"],
    expectedResult: "PASS",
    expectedEvidenceClasses: ["council"],
    riskClass: "R2",
    parallelSafetyClass: "READ_ONLY_PARALLEL_SAFE",
    liveActionPermitted: false,
    contractVersion: "1.0.0",
  },
  {
    scenarioId: "SIM_COUNCIL_MODE_DISAGREEMENT",
    description: "Council disagreement remains visible and does not approve itself.",
    contractGroups: ["Track B"],
    requiredFixtureIds: ["fixture-council-session"],
    expectedResult: "PASS",
    expectedEvidenceClasses: ["council"],
    riskClass: "R2",
    parallelSafetyClass: "READ_ONLY_PARALLEL_SAFE",
    liveActionPermitted: false,
    contractVersion: "1.0.0",
  },
  {
    scenarioId: "SIM_COUNCIL_MODE_RAHUL_APPROVAL_REQUIRED",
    description: "Material disagreement requires Rahul approval and remains separate from persona data.",
    contractGroups: ["Track B"],
    requiredFixtureIds: ["fixture-council-session", "fixture-approval"],
    expectedResult: "PASS",
    expectedEvidenceClasses: ["council", "approval"],
    riskClass: "R4",
    parallelSafetyClass: "READ_ONLY_PARALLEL_SAFE",
    liveActionPermitted: false,
    contractVersion: "1.0.0",
  },
  {
    scenarioId: "SIM_SAVED_DRAFT_RESUME",
    description: "Saved draft resumes without creating a new lineage or new runtime permission set.",
    contractGroups: ["Track B"],
    requiredFixtureIds: ["fixture-saved-draft"],
    expectedResult: "PASS",
    expectedEvidenceClasses: ["saved-draft"],
    riskClass: "R1",
    parallelSafetyClass: "READ_ONLY_PARALLEL_SAFE",
    liveActionPermitted: false,
    contractVersion: "1.0.0",
  },
  {
    scenarioId: "SIM_SAVED_DRAFT_SAME_SCOPE_UPDATE",
    description: "Same-scope edits update the existing draft lineage and version history.",
    contractGroups: ["Track B"],
    requiredFixtureIds: ["fixture-saved-draft"],
    expectedResult: "PASS",
    expectedEvidenceClasses: ["saved-draft"],
    riskClass: "R1",
    parallelSafetyClass: "READ_ONLY_PARALLEL_SAFE",
    liveActionPermitted: false,
    contractVersion: "1.0.0",
  },
  {
    scenarioId: "SIM_SAVED_DRAFT_MATERIAL_VERSION",
    description: "Material draft changes create a new version without erasing prior policy lineage.",
    contractGroups: ["Track B"],
    requiredFixtureIds: ["fixture-saved-draft"],
    expectedResult: "PASS",
    expectedEvidenceClasses: ["saved-draft", "versioning"],
    riskClass: "R2",
    parallelSafetyClass: "READ_ONLY_PARALLEL_SAFE",
    liveActionPermitted: false,
    contractVersion: "1.0.0",
  },
  {
    scenarioId: "SIM_AUTOMATION_CENTER_V2_PROJECTION",
    description: "Automation Center V2 projections remain deterministic and UI-only.",
    contractGroups: ["UX"],
    requiredFixtureIds: ["fixture-automation-center-screen-registry"],
    expectedResult: "PASS",
    expectedEvidenceClasses: ["automation-center-v2"],
    riskClass: "R1",
    parallelSafetyClass: "READ_ONLY_PARALLEL_SAFE",
    liveActionPermitted: false,
    contractVersion: "1.0.0",
  },
  {
    scenarioId: "SIM_ACCESSIBILITY_RELEASE_ALLOWED",
    description: "Accessible release gate permits contract-level consideration on PASS.",
    contractGroups: ["UX"],
    requiredFixtureIds: ["fixture-accessibility-gates"],
    expectedResult: "PASS",
    expectedEvidenceClasses: ["accessibility"],
    riskClass: "R1",
    parallelSafetyClass: "READ_ONLY_PARALLEL_SAFE",
    liveActionPermitted: false,
    contractVersion: "1.0.0",
  },
  {
    scenarioId: "SIM_ACCESSIBILITY_RELEASE_BLOCKED",
    description: "Accessibility gates block release on failing or missing evidence.",
    contractGroups: ["UX"],
    requiredFixtureIds: ["fixture-accessibility-gates"],
    expectedResult: "PASS",
    expectedEvidenceClasses: ["accessibility"],
    riskClass: "R2",
    parallelSafetyClass: "READ_ONLY_PARALLEL_SAFE",
    liveActionPermitted: false,
    contractVersion: "1.0.0",
  },
  {
    scenarioId: "SIM_COMPATIBILITY_VERSIONS",
    description: "Compatibility binds to Phase 1A.5, 1A.6, and 1A.7 contract versions.",
    contractGroups: ["Shared Governance", "UX"],
    requiredFixtureIds: ["fixture-workflow", "fixture-runtime"],
    expectedResult: "PASS",
    expectedEvidenceClasses: ["compatibility"],
    riskClass: "R1",
    parallelSafetyClass: "READ_ONLY_PARALLEL_SAFE",
    liveActionPermitted: false,
    contractVersion: "1.0.0",
  },
  {
    scenarioId: "SIM_ACTIVE_RUNTIME_LANE_LIMIT",
    description: "Only one active runtime lane is permitted in simulation.",
    contractGroups: ["Shared Governance", "Track A"],
    requiredFixtureIds: ["fixture-runtime"],
    expectedResult: "PASS",
    expectedEvidenceClasses: ["runtime-lane"],
    riskClass: "R1",
    parallelSafetyClass: "READ_ONLY_PARALLEL_SAFE",
    liveActionPermitted: false,
    contractVersion: "1.0.0",
  },
  {
    scenarioId: "SIM_SECURITY_BOUNDARY_REJECTION",
    description: "Prohibited executable and remote-write surfaces remain rejected.",
    contractGroups: ["Shared Governance", "Track B"],
    requiredFixtureIds: ["fixture-runtime", "fixture-permission-profile"],
    expectedResult: "PASS",
    expectedEvidenceClasses: ["security"],
    riskClass: "R5",
    parallelSafetyClass: "PROHIBITED",
    liveActionPermitted: false,
    contractVersion: "1.0.0",
  },
  {
    scenarioId: "SIM_P0_MUTATION_REJECTION",
    description: "Immutable P0 persona memory remains without a writer path.",
    contractGroups: ["Track B"],
    requiredFixtureIds: ["fixture-p0-onyx-metadata", "fixture-p0-nova-metadata"],
    expectedResult: "PASS",
    expectedEvidenceClasses: ["memory-safety", "persona"],
    riskClass: "R5",
    parallelSafetyClass: "PROHIBITED",
    liveActionPermitted: false,
    contractVersion: "1.0.0",
  },
  {
    scenarioId: "SIM_COMPLETE_FAIL_SAFE",
    description: "Integrated fail-safe scenario requires reconciliation without unsafe actions.",
    contractGroups: ["Shared Governance", "Track A", "Track B", "UX"],
    requiredFixtureIds: ["fixture-task", "fixture-approval", "fixture-quarantine-record", "fixture-context-package", "fixture-accessibility-gates"],
    expectedResult: "RECONCILIATION_REQUIRED",
    expectedEvidenceClasses: ["fail-safe", "reconciliation"],
    riskClass: "R5",
    parallelSafetyClass: "PROHIBITED",
    liveActionPermitted: false,
    contractVersion: "1.0.0",
  },
];

const scenarioIdSet = new Set<string>();
for (const scenario of SIMULATION_SCENARIO_DEFINITIONS) {
  if (scenarioIdSet.has(scenario.scenarioId)) {
    throw new Error(`Duplicate simulation scenario ID: ${scenario.scenarioId}`);
  }
  scenarioIdSet.add(scenario.scenarioId);
}

export const SIMULATION_SCENARIO_IDS = SIMULATION_SCENARIO_DEFINITIONS.map((scenario) => scenario.scenarioId);
export const ALL_SIMULATION_SCENARIOS = SIMULATION_SCENARIO_DEFINITIONS;

export function validateScenarioDefinition(definition: Partial<SimulationScenarioDefinition>): asserts definition is SimulationScenarioDefinition {
  if (!definition || typeof definition !== "object") {
    throw new Error("Simulation scenario definition must be an object.");
  }
  if (!definition.scenarioId || !definition.description || !Array.isArray(definition.contractGroups) || !Array.isArray(definition.requiredFixtureIds)) {
    throw new Error(`Invalid scenario definition: ${String(definition.scenarioId ?? "<unknown>")}`);
  }
  if (!SIMULATION_SCENARIO_DEFINITIONS.some((scenario) => scenario.scenarioId === definition.scenarioId)) {
    throw new Error(`Unknown simulation scenario ID: ${definition.scenarioId}`);
  }
  if (definition.liveActionPermitted !== undefined && definition.liveActionPermitted !== false) {
    throw new Error(`Scenario ${definition.scenarioId} claims live-action permission and is prohibited.`);
  }
  if (definition.riskClass === "R5" && definition.parallelSafetyClass !== "PROHIBITED") {
    throw new Error(`Scenario ${definition.scenarioId} violates the R5/prohibited safety split.`);
  }
}

export function resolveScenarioDefinition(scenarioId: string): SimulationScenarioDefinition {
  const definition = SIMULATION_SCENARIO_DEFINITIONS.find((scenario) => scenario.scenarioId === scenarioId);
  if (!definition) {
    throw new Error(`Unknown simulation scenario ID: ${scenarioId}`);
  }
  validateScenarioDefinition(definition);
  return definition;
}
