import { boundedFreeze, JOURNEY_EVENT_KINDS, SIGNIFICANCE_CLASSIFICATIONS, SOURCE_COMPATIBILITY_RULES, SOURCE_KINDS, SOURCE_PRECEDENCE, SOURCE_PRECEDENCE_BY_KIND, type JourneyEventKindB42, type SourceKind, type SourcePrecedenceClass } from "./journey-events";
import type { NonAuthorityMarker } from "./model";

export { boundedFreeze } from "./journey-events";

export const CAPTURE_POLICY_RESULTS = boundedFreeze(["ELIGIBLE_FOR_FUTURE_CAPTURE", "INELIGIBLE_INFORMATIONAL_EVENT", "DEFERRED_MISSING_EVIDENCE", "DEFERRED_CONFLICTING_EVIDENCE", "DENIED_PROHIBITED_CONTENT", "DENIED_OWNER_SCOPE", "DENIED_PRIVACY_SCOPE", "DENIED_UNSUPPORTED_SOURCE", "DENIED_MALFORMED_EVENT", "DENIED_STALE_EVENT", "SUPERSESSION_REQUIRED", "CORRECTION_REQUIRED"] as const);
export type CapturePolicyResult = (typeof CAPTURE_POLICY_RESULTS)[number];
export const IDENTITY_CLASSIFICATIONS = boundedFreeze(["NEW_EVENT", "EXACT_DUPLICATE", "REPLAYED_EVENT", "POTENTIAL_DUPLICATE", "MATERIAL_REVISION", "SUPERSEDING_EVENT", "LATE_EVIDENCE", "AMBIGUOUS_IDENTITY"] as const);
export type IdentityClassification = (typeof IDENTITY_CLASSIFICATIONS)[number];
export const CONTINUITY_GAP_TYPES = boundedFreeze(["AUTHORITATIVE_SOURCE_MISSING", "REQUIRED_CORROBORATION_MISSING", "SOURCE_UNAVAILABLE", "SOURCE_UNSUPPORTED", "SOURCE_CONFLICT", "SOURCE_REFERENCE_MALFORMED", "SOURCE_VERSION_UNKNOWN", "EVENT_ORDER_UNKNOWN", "OWNER_SCOPE_UNVERIFIED", "PRIVACY_CLASSIFICATION_UNKNOWN", "EVIDENCE_EXPIRED", "EVIDENCE_INTEGRITY_UNVERIFIED", "MATERIAL_CHANGE_AFTER_ASSESSMENT"] as const);
export type CaptureContinuityGap = (typeof CONTINUITY_GAP_TYPES)[number];
export const PRIVACY_CLASSIFICATIONS = boundedFreeze(["PUBLIC_PROJECT_METADATA", "HOUSEHOLD_SAFE_METADATA", "OWNER_PRIVATE_PROJECT_HISTORY", "SECURITY_SENSITIVE_METADATA", "CREDENTIAL_ADJACENT_METADATA", "PROHIBITED_SECRET_CONTENT", "PROHIBITED_PRIVATE_HOUSEHOLD_CONTENT", "PROHIBITED_CAMERA_OR_BIOMETRIC_CONTENT", "UNKNOWN_SENSITIVITY"] as const);
export type CapturePrivacyClassification = (typeof PRIVACY_CLASSIFICATIONS)[number];
export const PRIVACY_DECISIONS = boundedFreeze(["ALLOW_METADATA_ONLY", "ALLOW_OWNER_ONLY", "ALLOW_AFTER_REDACTION", "DEFER_FOR_OWNER_REVIEW", "DENY_PROHIBITED_CONTENT", "DENY_UNKNOWN_SENSITIVITY"] as const);
export type PrivacyDecision = (typeof PRIVACY_DECISIONS)[number];
export const CAPTURE_PRIORITIES = boundedFreeze(["CRITICAL_CONTINUITY", "GOVERNED_MILESTONE", "STANDARD_HISTORY", "OPTIONAL_ENRICHMENT"] as const);
export type CapturePriority = (typeof CAPTURE_PRIORITIES)[number];
export const OPERATING_MODES_B42 = boundedFreeze(["ACTIVE", "LIGHT", "VACATION", "HIBERNATION"] as const);
export type OperatingModeB42 = (typeof OPERATING_MODES_B42)[number];
export const NOISE_CLASSIFICATIONS = boundedFreeze(["MATERIAL_EVENT", "SUPPORTING_EVENT", "REPEATED_NONMATERIAL_EVENT", "TRANSIENT_TOOLING_EVENT", "LOCAL_DEBUG_EVENT", "UNSUPPORTED_NOISE"] as const);
export type NoiseClassification = (typeof NOISE_CLASSIFICATIONS)[number];
export const NOISE_DECISIONS = boundedFreeze(["PRESERVE", "DEFER", "AGGREGATE_LATER", "REJECT_NOISE"] as const);
export type NoiseDecision = (typeof NOISE_DECISIONS)[number];
export const ARTIFACT_PURPOSES = boundedFreeze(["PROJECT_JOURNEY_RECORD", "SECURITY_AUDIT_EVENT", "OPERATIONAL_LOG", "USER_MEMORY", "CONVERSATION_HISTORY", "RECOVERY_MANIFEST", "INTEGRITY_MANIFEST", "ARCHIVE_INDEX"] as const);
export type ArtifactPurpose = (typeof ARTIFACT_PURPOSES)[number];
export const JOURNEY_AUDIT_CLASSES = ARTIFACT_PURPOSES;
export type JourneyAuditClass = ArtifactPurpose;

export interface DeterministicEventIdentity extends NonAuthorityMarker { readonly eventKind: JourneyEventKindB42; readonly sourceKind: SourceKind; readonly sourceReference: string; readonly occurredAt: string; }
export interface EvidenceReference extends NonAuthorityMarker { readonly reference: string; readonly sourceKind: SourceKind; readonly precedence: SourcePrecedenceClass; readonly compatible: boolean; }
export interface CaptureEvidenceAssessment extends NonAuthorityMarker { readonly result: CapturePolicyResult; readonly gap?: CaptureContinuityGap; readonly conflictPreserved: true; readonly evidenceReferences: readonly EvidenceReference[]; readonly safeNextAction: string; readonly privacyDecision: PrivacyDecision; readonly ownerOnly: boolean; readonly reasonCodes: readonly string[]; }
export interface PrivacyPolicyAssessment extends NonAuthorityMarker { readonly classification: CapturePrivacyClassification; readonly decision: PrivacyDecision; readonly technicalInformationVisible: false; }
export interface CapturePriorityPolicy extends NonAuthorityMarker { readonly mode: OperatingModeB42; readonly priority: CapturePriority; readonly allowed: boolean; readonly behavior: "PRESERVE" | "DEFER"; }
export interface IdentityAssessmentInput { readonly exactMatch: boolean; readonly replayed: boolean; readonly potentialMatch: boolean; readonly materiallyChanged: boolean; readonly lateEvidence: boolean; readonly superseding: boolean; readonly sourceReference: string; }
export interface MaterialRevisionAssessment extends NonAuthorityMarker { readonly classification: "MATERIAL_REVISION" | "NO_MATERIAL_REVISION"; readonly priorRecordReference: string; readonly preservesPriorEvidence: true; }
export const SUPERSESSION_REASONS = ["MATERIAL_REVISION", "OWNER_CORRECTION"] as const;
export type SupersessionReason = (typeof SUPERSESSION_REASONS)[number];
export const CORRECTION_REASONS = ["MISSING_EVIDENCE", "CONFLICT_RESOLUTION", "OWNER_CORRECTION", "POLICY_CORRECTION"] as const;
export type CorrectionReason = (typeof CORRECTION_REASONS)[number];
export interface SupersessionAssessment extends NonAuthorityMarker { readonly required: true; readonly validReferences: boolean; readonly validReason: boolean; readonly priorRecordReference: string; readonly supersedingRecordReference: string; readonly reason: SupersessionReason | "INVALID"; readonly provenanceReference: string; readonly validProvenance: boolean; }
export interface OwnerCorrectionAssessment extends NonAuthorityMarker { readonly allowed: boolean; readonly validReferences: boolean; readonly validReason: boolean; readonly validProvenance: boolean; readonly correctedRecordReference: string; readonly supersedingRecordReference: string; readonly reason: CorrectionReason | "INVALID"; readonly provenanceReference: string; readonly ownerOnly: true; }
export interface MandatoryEvidencePolicy extends NonAuthorityMarker { readonly requiredSourceKinds: readonly SourceKind[]; readonly optionalCorroboratingSourceKinds: readonly SourceKind[]; readonly prohibitedSourceKinds: readonly SourceKind[]; readonly minimumEvidenceCount: number; }
export interface EvidenceAssessmentInput { readonly eventKind: JourneyEventKindB42; readonly evidence: readonly EvidenceReference[]; readonly malformed: boolean; readonly stale: boolean; readonly materialChangeAfterAssessment: boolean; readonly conflicting: boolean; readonly privacyClassification: CapturePrivacyClassification; readonly safeRedactionPossible?: boolean; readonly detailedProjectJourney?: boolean; readonly canonicalPrimaryOwner?: boolean; readonly ownerScopeVerified?: boolean; }
export interface ConflictAssessment extends NonAuthorityMarker { readonly unresolved: true; readonly competingEvidence: readonly EvidenceReference[]; readonly conflictReason: "SOURCE_CONFLICT" | "MATERIAL_DISAGREEMENT"; readonly conflictDetails: string; readonly safeNextAction: string; readonly ownerOnly: boolean; }
export interface NoiseBudgetPolicy extends NonAuthorityMarker { readonly maximumOptionalContextItems: number; readonly maximumInformationalEventsPerMilestone: number; readonly repeatedEventThreshold: number; readonly burstThreshold: number; }
export interface NoiseAssessment extends NonAuthorityMarker { readonly classification: NoiseClassification; readonly decision: NoiseDecision; readonly mandatoryEvidencePreserved: true; }
export interface ArtifactSeparationAssessment extends NonAuthorityMarker { readonly source: ArtifactPurpose; readonly target: ArtifactPurpose; readonly allowedAsJourneyReference: boolean; readonly payloadAbsorptionAllowed: false; }
export interface OwnerScopeAssessmentInput { readonly detailedProjectJourney: boolean; readonly authenticatedAsCanonicalPrimaryOwner: boolean; readonly ownerScopeVerified: boolean; readonly privacyClassification: CapturePrivacyClassification; readonly requestedDisclosureLevel: "CURATED_BASIC" | "DETAILED_OWNER"; readonly characterOrAlias?: string; }
export interface OwnerScopeAssessment extends NonAuthorityMarker { readonly allowed: boolean; readonly ownerOnly: boolean; readonly privacyDecision: PrivacyDecision; readonly safeNextAction: string; readonly reasonCodes: readonly string[]; }

export const SOURCE_PRECEDENCE_RANK: Readonly<Record<SourcePrecedenceClass, number>> = boundedFreeze({ OWNER_SIGNED_CORRECTION: 6, MERGED_REPOSITORY_EVIDENCE: 5, APPROVED_REVIEW_EVIDENCE: 4, VALIDATION_EVIDENCE: 3, PLANNING_EVIDENCE: 2, UNSUPPORTED_ASSERTION: 1 });
export const eventIdentityKey = (event: Pick<DeterministicEventIdentity, "eventKind" | "sourceKind" | "sourceReference" | "occurredAt">): string => JSON.stringify({ eventKind: event.eventKind, sourceKind: event.sourceKind, sourceReference: event.sourceReference.normalize("NFC").trim(), occurredAt: event.occurredAt.normalize("NFC").trim() });
export const compareSourcePrecedence = (left: SourcePrecedenceClass, right: SourcePrecedenceClass): number => SOURCE_PRECEDENCE_RANK[left] - SOURCE_PRECEDENCE_RANK[right];
export const classifyIdentity = (input: IdentityAssessmentInput): IdentityClassification => { const facts = [input.exactMatch, input.replayed, input.potentialMatch, input.materiallyChanged, input.lateEvidence, input.superseding].filter(Boolean).length; return !input.sourceReference || facts > 1 ? "AMBIGUOUS_IDENTITY" : input.replayed ? "REPLAYED_EVENT" : input.exactMatch ? "EXACT_DUPLICATE" : input.potentialMatch ? "POTENTIAL_DUPLICATE" : input.materiallyChanged ? "MATERIAL_REVISION" : input.superseding ? "SUPERSEDING_EVENT" : input.lateEvidence ? "LATE_EVIDENCE" : "NEW_EVENT"; };
export const assessMaterialRevision = (priorRecordReference: string, materiallyChanged: boolean): MaterialRevisionAssessment => ({ classification: materiallyChanged ? "MATERIAL_REVISION" : "NO_MATERIAL_REVISION", priorRecordReference, preservesPriorEvidence: true, createsAuthority: false });
const validReference = (value: unknown): value is string => typeof value === "string" && value.trim().length > 0 && !/[\s<>]/.test(value.trim());
const isSupersessionReason = (value: unknown): value is SupersessionReason => typeof value === "string" && (SUPERSESSION_REASONS as readonly string[]).includes(value);
const isCorrectionReason = (value: unknown): value is CorrectionReason => typeof value === "string" && (CORRECTION_REASONS as readonly string[]).includes(value);
export const assessSupersession = (priorRecordReference: string, supersedingRecordReference: string, reason: unknown, provenanceReference: string): SupersessionAssessment => { const validReferences = validReference(priorRecordReference) && validReference(supersedingRecordReference) && priorRecordReference.trim() !== supersedingRecordReference.trim(); const validReason = isSupersessionReason(reason); const validProvenance = validReference(provenanceReference); return { required: true, validReferences, validReason, priorRecordReference, supersedingRecordReference, reason: validReason ? reason : "INVALID", provenanceReference, validProvenance, createsAuthority: false }; };
export const assessOwnerCorrection = (correctedRecordReference: string, supersedingRecordReference: string, reason: unknown, provenanceReference: string, ownerScopeVerified: boolean): OwnerCorrectionAssessment => { const validReferences = validReference(correctedRecordReference) && validReference(supersedingRecordReference) && correctedRecordReference.trim() !== supersedingRecordReference.trim(); const validReason = isCorrectionReason(reason); const validProvenance = validReference(provenanceReference); return { allowed: ownerScopeVerified === true && validReferences && validReason && validProvenance, validReferences, validReason, validProvenance, correctedRecordReference, supersedingRecordReference, reason: validReason ? reason : "INVALID", provenanceReference, ownerOnly: true, createsAuthority: false }; };
export const MANDATORY_EVIDENCE_POLICY: Readonly<Record<JourneyEventKindB42, MandatoryEvidencePolicy>> = boundedFreeze(Object.fromEntries(JOURNEY_EVENT_KINDS.map((eventKind) => { const rule = SOURCE_COMPATIBILITY_RULES[eventKind]; return [eventKind, { requiredSourceKinds: rule.required, optionalCorroboratingSourceKinds: rule.optionalCorroboration, prohibitedSourceKinds: rule.prohibited, minimumEvidenceCount: 1, createsAuthority: false }]; })) as Record<JourneyEventKindB42, MandatoryEvidencePolicy>);
export const createMandatoryEvidencePolicy = (eventKind: JourneyEventKindB42, minimumEvidenceCount: number): MandatoryEvidencePolicy => boundedFreeze({ ...MANDATORY_EVIDENCE_POLICY[eventKind], minimumEvidenceCount, createsAuthority: false });
export const createEvidenceReference = (reference: string, sourceKind: SourceKind, eventKind: JourneyEventKindB42): EvidenceReference => ({ reference, sourceKind, precedence: SOURCE_PRECEDENCE_BY_KIND[sourceKind], compatible: SOURCE_COMPATIBILITY_RULES[eventKind].required.includes(sourceKind) || SOURCE_COMPATIBILITY_RULES[eventKind].optionalCorroboration.includes(sourceKind), createsAuthority: false });
const isPrivacyClassification = (value: unknown): value is CapturePrivacyClassification => typeof value === "string" && (PRIVACY_CLASSIFICATIONS as readonly string[]).includes(value);
const privacyFor = (classification: CapturePrivacyClassification, safeRedactionPossible = false): PrivacyPolicyAssessment => ({ classification, decision: classification === "CREDENTIAL_ADJACENT_METADATA" && !safeRedactionPossible ? "DEFER_FOR_OWNER_REVIEW" : classifyPrivacy(classification), technicalInformationVisible: false, createsAuthority: false });
const deniedAssessment = (privacyDecision: PrivacyDecision, reasonCodes: readonly string[], ownerOnly = false, result: CapturePolicyResult = privacyDecision === "DENY_UNKNOWN_SENSITIVITY" ? "DENIED_PRIVACY_SCOPE" : privacyDecision === "DENY_PROHIBITED_CONTENT" ? "DENIED_PROHIBITED_CONTENT" : "DENIED_PRIVACY_SCOPE"): CaptureEvidenceAssessment => ({ result, privacyDecision, ownerOnly, reasonCodes, conflictPreserved: true, evidenceReferences: [], safeNextAction: "Keep the content excluded and request an explicit owner-authorized policy review.", createsAuthority: false });
const assessmentWithPrivacy = (result: CapturePolicyResult, evidenceReferences: readonly EvidenceReference[], gap: CaptureContinuityGap | undefined, privacy: PrivacyPolicyAssessment, reasonCodes: readonly string[]): CaptureEvidenceAssessment => ({ result, gap, conflictPreserved: true, evidenceReferences: [...evidenceReferences], safeNextAction: result === "ELIGIBLE_FOR_FUTURE_CAPTURE" ? "Await future authorized capture evaluation." : "Preserve evidence and request owner-authorized review.", privacyDecision: privacy.decision, ownerOnly: privacy.classification === "OWNER_PRIVATE_PROJECT_HISTORY" || privacy.decision === "ALLOW_OWNER_ONLY", reasonCodes, createsAuthority: false });
const validTimestamp = (value: unknown): value is string => typeof value === "string" && value.trim().length > 0 && /^\d{4}-\d{2}-\d{2}T/.test(value) && !Number.isNaN(Date.parse(value));
const ownerFactsValid = (record: Record<string, unknown>): boolean => typeof record.detailedProjectJourney === "boolean" && typeof record.canonicalPrimaryOwner === "boolean" && typeof record.ownerScopeVerified === "boolean";
export const assessEvidence = (input: EvidenceAssessmentInput): CaptureEvidenceAssessment => { const privacy = isPrivacyClassification(input.privacyClassification) ? privacyFor(input.privacyClassification, input.safeRedactionPossible) : undefined; const protectedJourney = privacy?.classification === "OWNER_PRIVATE_PROJECT_HISTORY" || input.detailedProjectJourney === true; if (!privacy || privacy.decision === "DENY_UNKNOWN_SENSITIVITY" || privacy.decision === "DENY_PROHIBITED_CONTENT" || privacy.decision === "DEFER_FOR_OWNER_REVIEW") return deniedAssessment(privacy?.decision ?? "DENY_UNKNOWN_SENSITIVITY", [privacy ? "PRIVACY_SCOPE_NOT_PERMITTED" : "PRIVACY_CLASSIFICATION_MISSING"], protectedJourney); if (protectedJourney && !(input.canonicalPrimaryOwner === true && input.ownerScopeVerified === true)) return deniedAssessment("DENY_UNKNOWN_SENSITIVITY", ["OWNER_SCOPE_NOT_VERIFIED"], true, "DENIED_OWNER_SCOPE"); const policy = MANDATORY_EVIDENCE_POLICY[input.eventKind]; const hasRequired = input.evidence.length >= policy.minimumEvidenceCount && policy.requiredSourceKinds.every((required) => input.evidence.some((evidence) => evidence.sourceKind === required && evidence.compatible)); const result = input.malformed ? "DENIED_MALFORMED_EVENT" : input.stale || input.materialChangeAfterAssessment ? "DENIED_STALE_EVENT" : input.conflicting ? "DEFERRED_CONFLICTING_EVIDENCE" : input.evidence.some((evidence) => !evidence.compatible || policy.prohibitedSourceKinds.includes(evidence.sourceKind)) ? "DENIED_UNSUPPORTED_SOURCE" : !hasRequired ? "DEFERRED_MISSING_EVIDENCE" : "ELIGIBLE_FOR_FUTURE_CAPTURE"; return assessmentWithPrivacy(result, input.evidence, result === "DENIED_STALE_EVENT" ? (input.materialChangeAfterAssessment ? "MATERIAL_CHANGE_AFTER_ASSESSMENT" : "EVIDENCE_EXPIRED") : result === "DEFERRED_MISSING_EVIDENCE" ? "AUTHORITATIVE_SOURCE_MISSING" : result === "DEFERRED_CONFLICTING_EVIDENCE" ? "SOURCE_CONFLICT" : undefined, privacy, [result]); };
export const assessEvent = (event: unknown): CaptureEvidenceAssessment => { const record = typeof event === "object" && event !== null ? event as Record<string, unknown> : undefined; const validKind = typeof record?.eventKind === "string" && (JOURNEY_EVENT_KINDS as readonly string[]).includes(record.eventKind); const validSignificance = typeof record?.significance === "string" && (SIGNIFICANCE_CLASSIFICATIONS as readonly string[]).includes(record.significance); const validSource = typeof record?.sourceKind === "string" && (SOURCE_KINDS as readonly string[]).includes(record.sourceKind); const protectedJourney = record?.privacyClassification === "OWNER_PRIVATE_PROJECT_HISTORY" || record?.detailedProjectJourney === true; const malformed = !record || !validKind || !validSignificance || !validSource || !validTimestamp(record?.recordedAt) || !validTimestamp(record?.occurredAt) || !validReference(record?.eventId as string) || !validReference(record?.sourceReference as string) || (protectedJourney && !ownerFactsValid(record)); if (malformed) return deniedAssessment("DENY_UNKNOWN_SENSITIVITY", [!record?.eventId ? "EVENT_ID_MISSING" : !validReference(record.eventId as string) ? "EVENT_ID_MALFORMED" : !validKind ? "EVENT_KIND_UNSUPPORTED" : !validSignificance ? "SIGNIFICANCE_INVALID" : !validTimestamp(record.recordedAt) ? "RECORDED_AT_INVALID" : !validTimestamp(record.occurredAt) ? "OCCURRED_AT_INVALID" : !validSource ? "SOURCE_UNSUPPORTED" : protectedJourney && !ownerFactsValid(record) ? "OWNER_FACTS_MISSING_OR_MALFORMED" : "SOURCE_REFERENCE_MALFORMED"], protectedJourney, "DENIED_MALFORMED_EVENT"); return assessEvidence({ eventKind: record.eventKind as JourneyEventKindB42, evidence: [], malformed: false, stale: record.stale === true, materialChangeAfterAssessment: record.materialChangeAfterAssessment === true, conflicting: record.conflicting === true, privacyClassification: record.privacyClassification as CapturePrivacyClassification, safeRedactionPossible: record.safeRedactionPossible === true, detailedProjectJourney: record.detailedProjectJourney as boolean, canonicalPrimaryOwner: record.canonicalPrimaryOwner as boolean, ownerScopeVerified: record.ownerScopeVerified as boolean }); };
export const assessConflict = (competingEvidence: readonly EvidenceReference[], ownerOnly: boolean, conflictReason: ConflictAssessment["conflictReason"] = "SOURCE_CONFLICT", conflictDetails = "Evidence references disagree."): ConflictAssessment => ({ unresolved: true, competingEvidence, conflictReason, conflictDetails, safeNextAction: "Preserve all evidence and request authoritative review.", ownerOnly, createsAuthority: false });
export const classifyPrivacy = (classification: CapturePrivacyClassification): PrivacyDecision => classification === "PROHIBITED_SECRET_CONTENT" || classification === "PROHIBITED_PRIVATE_HOUSEHOLD_CONTENT" || classification === "PROHIBITED_CAMERA_OR_BIOMETRIC_CONTENT" ? "DENY_PROHIBITED_CONTENT" : classification === "UNKNOWN_SENSITIVITY" ? "DENY_UNKNOWN_SENSITIVITY" : classification === "CREDENTIAL_ADJACENT_METADATA" ? "ALLOW_AFTER_REDACTION" : classification === "OWNER_PRIVATE_PROJECT_HISTORY" || classification === "SECURITY_SENSITIVE_METADATA" ? "ALLOW_OWNER_ONLY" : "ALLOW_METADATA_ONLY";
export const classifyCapturePriority = (mode: OperatingModeB42, priority: CapturePriority): CapturePriorityPolicy => ({ mode, priority, allowed: priority === "CRITICAL_CONTINUITY" || priority === "GOVERNED_MILESTONE" || mode === "ACTIVE" || (mode === "LIGHT" && priority === "STANDARD_HISTORY"), behavior: priority === "OPTIONAL_ENRICHMENT" && mode !== "ACTIVE" ? "DEFER" : "PRESERVE", createsAuthority: false });
export const isValidNoiseBudget = (budget: NoiseBudgetPolicy): boolean => [budget.maximumOptionalContextItems, budget.maximumInformationalEventsPerMilestone, budget.repeatedEventThreshold, budget.burstThreshold].every((value) => Number.isInteger(value) && value >= 0);
export const assessNoise = (classification: NoiseClassification, budget: NoiseBudgetPolicy, repeatedCount: number, optionalContextCount: number, informationalEvents: number, burstCount: number, mandatoryEvidence: boolean): NoiseAssessment => ({ classification, decision: mandatoryEvidence || classification === "MATERIAL_EVENT" ? "PRESERVE" : !isValidNoiseBudget(budget) ? "DEFER" : classification === "UNSUPPORTED_NOISE" || classification === "LOCAL_DEBUG_EVENT" ? "REJECT_NOISE" : classification === "REPEATED_NONMATERIAL_EVENT" && repeatedCount >= budget.repeatedEventThreshold ? "AGGREGATE_LATER" : burstCount >= budget.burstThreshold || optionalContextCount >= budget.maximumOptionalContextItems || informationalEvents >= budget.maximumInformationalEventsPerMilestone ? "DEFER" : "PRESERVE", mandatoryEvidencePreserved: true, createsAuthority: false });
export const assessArtifactSeparation = (source: ArtifactPurpose, target: ArtifactPurpose = "PROJECT_JOURNEY_RECORD"): ArtifactSeparationAssessment => ({ source, target, allowedAsJourneyReference: target === "PROJECT_JOURNEY_RECORD", payloadAbsorptionAllowed: false, createsAuthority: false });
export const assessEvidenceAgainstPolicy = (input: EvidenceAssessmentInput, policy: MandatoryEvidencePolicy): CaptureEvidenceAssessment => assessEvidence(input).result === "ELIGIBLE_FOR_FUTURE_CAPTURE" && input.evidence.length < policy.minimumEvidenceCount ? assessmentWithPrivacy("DEFERRED_MISSING_EVIDENCE", input.evidence, "AUTHORITATIVE_SOURCE_MISSING", privacyFor(input.privacyClassification, input.safeRedactionPossible), ["AUTHORITATIVE_SOURCE_MISSING"]) : assessEvidence(input);
export const assessOwnerScope = (input: OwnerScopeAssessmentInput): OwnerScopeAssessment => { const privacy = isPrivacyClassification(input.privacyClassification) ? privacyFor(input.privacyClassification) : undefined; const validFacts = typeof input.detailedProjectJourney === "boolean" && typeof input.authenticatedAsCanonicalPrimaryOwner === "boolean" && typeof input.ownerScopeVerified === "boolean" && (input.requestedDisclosureLevel === "CURATED_BASIC" || input.requestedDisclosureLevel === "DETAILED_OWNER"); const allowed = Boolean(validFacts && input.detailedProjectJourney && input.authenticatedAsCanonicalPrimaryOwner && input.ownerScopeVerified && input.requestedDisclosureLevel === "DETAILED_OWNER" && privacy?.decision === "ALLOW_OWNER_ONLY"); return { allowed, ownerOnly: input.detailedProjectJourney === true, privacyDecision: privacy?.decision ?? "DENY_UNKNOWN_SENSITIVITY", safeNextAction: allowed ? "Keep detailed Journey access within the verified owner scope." : "Deny detailed Journey access and request verified canonical owner scope.", reasonCodes: allowed ? ["VERIFIED_CANONICAL_PRIMARY_OWNER"] : ["OWNER_SCOPE_OR_PRIVACY_NOT_VERIFIED"], createsAuthority: false }; };
export const isKnownCaptureVocabulary = (value: string): boolean => [...JOURNEY_EVENT_KINDS, ...SIGNIFICANCE_CLASSIFICATIONS, ...SOURCE_KINDS, ...SOURCE_PRECEDENCE, ...Object.keys(SOURCE_PRECEDENCE_BY_KIND)].includes(value as never);
