import type { ArchiveSetDescriptor, CopyReceiptDescriptor, IntegrityManifestDescriptor, JourneyRecordDescriptor, RecoveryPackageDescriptor, SanitizationDescriptor } from "./model";

const evidence = (sourceId: string, trust: "AUTHORITATIVE" | "UNVERIFIED" | "CONFLICTING") => ({ sourceKind: "SYNTHETIC_FIXTURE" as const, sourceId, trust, createsAuthority: false as const });
const provenance = (sourceId: string) => ({ recordedBy: "synthetic-fixture", reason: "Deterministic contract example", evidence: [evidence(sourceId, "AUTHORITATIVE")], createsAuthority: false as const });
const ownerAccess = { ownerOnly: true, accessClassification: "OWNER_ONLY" as const, authenticationRequired: "DESCRIPTIVE_ONLY" as const, defaultDisclosure: "RESTRICTED" as const, restrictedView: "DENY_UNAUTHORIZED_DETAIL" as const, technicalInformation: { available: true, defaultVisible: false as const, notes: "Technical Information remains policy-gated." }, createsAuthority: false as const };
export const VALID_JOURNEY_RECORD: Readonly<JourneyRecordDescriptor> = Object.freeze({ recordId: "fixture-journey-001", eventKind: "MILESTONE", evidenceState: "AUTHORITATIVE", summaryQuality: "COMPLETE", title: "Synthetic foundation milestone", ownerOnly: true, privacyClass: "OWNER_ONLY", attribution: "synthetic-fixture", provenance: provenance("fixture-evidence-001"), continuityGaps: [], access: ownerAccess, createsAuthority: false });
export const MISSING_EVIDENCE_RECORD: Readonly<JourneyRecordDescriptor> = Object.freeze({ ...VALID_JOURNEY_RECORD, recordId: "fixture-journey-missing", evidenceState: "INCOMPLETE", summaryQuality: "PARTIAL", continuityGaps: [{ type: "MISSING_EVIDENCE", explanation: "Synthetic evidence is absent.", createsAuthority: false }] as const });
export const CONFLICTING_EVIDENCE_RECORD: Readonly<JourneyRecordDescriptor> = Object.freeze({ ...VALID_JOURNEY_RECORD, recordId: "fixture-journey-conflict", evidenceState: "CONFLICTING", continuityGaps: [{ type: "CONFLICTING_EVIDENCE", explanation: "Synthetic sources disagree.", createsAuthority: false }] as const, provenance: { ...provenance("fixture-evidence-002"), evidence: [evidence("fixture-evidence-002", "CONFLICTING"), evidence("fixture-evidence-003", "CONFLICTING")] } });
export const VALID_RECOVERY_PACKAGE: Readonly<RecoveryPackageDescriptor> = Object.freeze({ packageId: "fixture-package-001", state: "DESCRIBED", contentsPolicy: "SAFE_METADATA_ONLY", routes: ["LOCAL", "OFFLINE", "REMOTE_SUPPLEMENT"] as const, providerIndependent: true, subscriptionIndependent: true, internetIndependent: true, manifestId: "fixture-manifest-001", restorePlanId: "fixture-restore-plan-001", createsAuthority: false });
export const INVALID_RECOVERY_PACKAGE: Readonly<RecoveryPackageDescriptor> = Object.freeze({ ...VALID_RECOVERY_PACKAGE, packageId: "fixture-package-invalid", state: "INVALID", contentsPolicy: "PROHIBITED_CONTENT_PRESENT" });
export const INTEGRITY_MANIFEST: Readonly<IntegrityManifestDescriptor> = Object.freeze({ manifestId: "fixture-integrity-001", expectedArtifacts: ["fixture-artifact-001"], state: "UNVERIFIED", hashing: "DEFERRED", createsAuthority: false });
export const CORRUPT_PACKAGE_STATUS: Readonly<IntegrityManifestDescriptor> = Object.freeze({ ...INTEGRITY_MANIFEST, manifestId: "fixture-integrity-corrupt", state: "CORRUPT" });
export const VERIFIED_LOCAL_COPY_RECEIPT: Readonly<CopyReceiptDescriptor> = Object.freeze({ receiptId: "fixture-copy-local-001", route: "LOCAL", health: "AVAILABLE_PROJECTION", syntheticProjection: true, createsAuthority: false });
export const UNAVAILABLE_OFFLINE_COPY_RECEIPT: Readonly<CopyReceiptDescriptor> = Object.freeze({ receiptId: "fixture-copy-offline-001", route: "OFFLINE", health: "UNAVAILABLE", syntheticProjection: true, createsAuthority: false });
export const DEGRADED_ARCHIVE_SET: Readonly<ArchiveSetDescriptor> = Object.freeze({ archiveSetId: "fixture-archive-degraded", health: "DEGRADED", storagePressure: "ELEVATED", retention: "RETAIN_PENDING_REVIEW", operatingMode: "LIGHT", createsAuthority: false });
export const CRITICAL_STORAGE_PRESSURE: Readonly<ArchiveSetDescriptor> = Object.freeze({ ...DEGRADED_ARCHIVE_SET, archiveSetId: "fixture-archive-critical", health: "CRITICAL", storagePressure: "CRITICAL", operatingMode: "ACTIVE" });
export const SANITIZATION_DENIAL: Readonly<SanitizationDescriptor> = Object.freeze({ contentClass: "UNKNOWN_SENSITIVE_CONTENT", decision: "DENIED_UNKNOWN", createsAuthority: false });
export const FIXTURE_OPERATING_MODES = Object.freeze(["ACTIVE", "LIGHT", "VACATION", "HIBERNATION"] as const);