import type { NonAuthorityMarker } from "./model";

const MAX_FREEZE_DEPTH = 32;
const MAX_FREEZE_NODES = 512;
const freeze = <T>(value: T): T => Object.freeze(value);
// Bounded helper for finite package constants; never apply it to caller input.
export const boundedFreeze = <T>(value: T): T => {
  const seen = new WeakSet<object>();
  let nodes = 0;
  const visit = (current: unknown, depth: number): void => {
    if (typeof current !== "object" || current === null || seen.has(current)) return;
    if (depth > MAX_FREEZE_DEPTH || nodes >= MAX_FREEZE_NODES) throw new RangeError("policy data exceeds bounded freeze limits");
    seen.add(current); nodes += 1;
    for (const child of Object.values(current)) visit(child, depth + 1);
    Object.freeze(current);
  };
  visit(value, 0);
  return value;
};

export const JOURNEY_EVENT_KINDS = freeze([
  "PULL_REQUEST_MERGED", "CHECKPOINT_TAG_ACCEPTED", "ARCHITECTURE_DECISION_RECORDED", "ROADMAP_DECISION_RECORDED",
  "ACCEPTANCE_REQUIREMENT_ADDED", "ACCEPTANCE_REQUIREMENT_CHANGED", "ACCEPTANCE_REQUIREMENT_SUPERSEDED", "IMPLEMENTATION_STARTED",
  "IMPLEMENTATION_COMPLETED", "IMPLEMENTATION_REJECTED", "VALIDATION_COMPLETED", "VALIDATION_FAILED",
  "INDEPENDENT_REVIEW_ACCEPTED", "INDEPENDENT_REVIEW_REJECTED", "POLICY_CHANGED", "SECURITY_FINDING_RECORDED",
  "SECURITY_FINDING_RESOLVED", "RECOVERY_EXERCISE_COMPLETED", "RECOVERY_EXERCISE_FAILED", "ROLLBACK_PERFORMED",
  "OWNER_CORRECTION_RECORDED", "CONTINUITY_GAP_DETECTED", "EVIDENCE_CONFLICT_DETECTED", "OPERATING_MODE_CHANGED",
  "PHASE_OR_WAVE_FROZEN", "PHASE_OR_WAVE_REOPENED"
] as const);
export type JourneyEventKindB42 = (typeof JOURNEY_EVENT_KINDS)[number];

export const SIGNIFICANCE_CLASSIFICATIONS = freeze(["MANDATORY_MILESTONE", "GOVERNED_DECISION", "VALIDATION_EVIDENCE", "CONTINUITY_EXCEPTION", "OWNER_CORRECTION", "INFORMATIONAL"] as const);
export type SignificanceClassification = (typeof SIGNIFICANCE_CLASSIFICATIONS)[number];

export const SOURCE_KINDS = freeze([
  "MERGED_PULL_REQUEST", "REPOSITORY_COMMIT", "CHECKPOINT_TAG", "APPROVED_ARCHITECTURE_DECISION", "APPROVED_ROADMAP_DECISION",
  "ACCEPTANCE_REGISTRY", "TEST_EVIDENCE", "TYPECHECK_EVIDENCE", "INDEPENDENT_REVIEW", "MERGE_VERIFICATION",
  "RECOVERY_EXERCISE_REPORT", "ROLLBACK_REPORT", "OWNER_SIGNED_CORRECTION", "GOVERNED_POLICY_RECORD", "OPERATING_MODE_AUDIT_RECORD"
] as const);
export type SourceKind = (typeof SOURCE_KINDS)[number];

export const SOURCE_PRECEDENCE = freeze(["OWNER_SIGNED_CORRECTION", "MERGED_REPOSITORY_EVIDENCE", "APPROVED_REVIEW_EVIDENCE", "VALIDATION_EVIDENCE", "PLANNING_EVIDENCE", "UNSUPPORTED_ASSERTION"] as const);
export type SourcePrecedenceClass = (typeof SOURCE_PRECEDENCE)[number];

export const SOURCE_PRECEDENCE_BY_KIND: Readonly<Record<SourceKind, SourcePrecedenceClass>> = boundedFreeze({
  MERGED_PULL_REQUEST: "MERGED_REPOSITORY_EVIDENCE", REPOSITORY_COMMIT: "MERGED_REPOSITORY_EVIDENCE", CHECKPOINT_TAG: "MERGED_REPOSITORY_EVIDENCE",
  APPROVED_ARCHITECTURE_DECISION: "APPROVED_REVIEW_EVIDENCE", APPROVED_ROADMAP_DECISION: "APPROVED_REVIEW_EVIDENCE", ACCEPTANCE_REGISTRY: "PLANNING_EVIDENCE",
  TEST_EVIDENCE: "VALIDATION_EVIDENCE", TYPECHECK_EVIDENCE: "VALIDATION_EVIDENCE", INDEPENDENT_REVIEW: "APPROVED_REVIEW_EVIDENCE", MERGE_VERIFICATION: "APPROVED_REVIEW_EVIDENCE",
  RECOVERY_EXERCISE_REPORT: "VALIDATION_EVIDENCE", ROLLBACK_REPORT: "MERGED_REPOSITORY_EVIDENCE", OWNER_SIGNED_CORRECTION: "OWNER_SIGNED_CORRECTION",
  GOVERNED_POLICY_RECORD: "PLANNING_EVIDENCE", OPERATING_MODE_AUDIT_RECORD: "VALIDATION_EVIDENCE"
});

export interface SourceCompatibilityRule {
  readonly required: readonly SourceKind[];
  readonly optionalCorroboration: readonly SourceKind[];
  readonly prohibited: readonly SourceKind[];
}

export const SOURCE_COMPATIBILITY: Readonly<Record<JourneyEventKindB42, readonly SourceKind[]>> = boundedFreeze({
  PULL_REQUEST_MERGED: ["MERGED_PULL_REQUEST", "MERGE_VERIFICATION"], CHECKPOINT_TAG_ACCEPTED: ["CHECKPOINT_TAG", "MERGE_VERIFICATION"],
  ARCHITECTURE_DECISION_RECORDED: ["APPROVED_ARCHITECTURE_DECISION"], ROADMAP_DECISION_RECORDED: ["APPROVED_ROADMAP_DECISION"],
  ACCEPTANCE_REQUIREMENT_ADDED: ["ACCEPTANCE_REGISTRY"], ACCEPTANCE_REQUIREMENT_CHANGED: ["ACCEPTANCE_REGISTRY"], ACCEPTANCE_REQUIREMENT_SUPERSEDED: ["ACCEPTANCE_REGISTRY"],
  IMPLEMENTATION_STARTED: ["REPOSITORY_COMMIT", "MERGED_PULL_REQUEST"], IMPLEMENTATION_COMPLETED: ["MERGED_PULL_REQUEST", "REPOSITORY_COMMIT", "MERGE_VERIFICATION"],
  IMPLEMENTATION_REJECTED: ["INDEPENDENT_REVIEW", "TEST_EVIDENCE", "MERGE_VERIFICATION"], VALIDATION_COMPLETED: ["TEST_EVIDENCE", "TYPECHECK_EVIDENCE", "MERGE_VERIFICATION"],
  VALIDATION_FAILED: ["TEST_EVIDENCE", "TYPECHECK_EVIDENCE"], INDEPENDENT_REVIEW_ACCEPTED: ["INDEPENDENT_REVIEW"], INDEPENDENT_REVIEW_REJECTED: ["INDEPENDENT_REVIEW"],
  POLICY_CHANGED: ["GOVERNED_POLICY_RECORD"], SECURITY_FINDING_RECORDED: ["INDEPENDENT_REVIEW", "GOVERNED_POLICY_RECORD"], SECURITY_FINDING_RESOLVED: ["INDEPENDENT_REVIEW", "TEST_EVIDENCE"],
  RECOVERY_EXERCISE_COMPLETED: ["RECOVERY_EXERCISE_REPORT"], RECOVERY_EXERCISE_FAILED: ["RECOVERY_EXERCISE_REPORT"], ROLLBACK_PERFORMED: ["ROLLBACK_REPORT"],
  OWNER_CORRECTION_RECORDED: ["OWNER_SIGNED_CORRECTION"], CONTINUITY_GAP_DETECTED: ["GOVERNED_POLICY_RECORD", "INDEPENDENT_REVIEW"], EVIDENCE_CONFLICT_DETECTED: ["GOVERNED_POLICY_RECORD", "INDEPENDENT_REVIEW"],
  OPERATING_MODE_CHANGED: ["OPERATING_MODE_AUDIT_RECORD"], PHASE_OR_WAVE_FROZEN: ["GOVERNED_POLICY_RECORD", "MERGE_VERIFICATION"], PHASE_OR_WAVE_REOPENED: ["GOVERNED_POLICY_RECORD", "OWNER_SIGNED_CORRECTION"]
});

export const SOURCE_COMPATIBILITY_RULES: Readonly<Record<JourneyEventKindB42, SourceCompatibilityRule>> = boundedFreeze(Object.fromEntries(
  JOURNEY_EVENT_KINDS.map((eventKind) => {
    const compatible = SOURCE_COMPATIBILITY[eventKind];
    return [eventKind, { required: compatible.slice(0, 1), optionalCorroboration: compatible.slice(1), prohibited: SOURCE_KINDS.filter((sourceKind) => !compatible.includes(sourceKind)) }];
  })
) as unknown as Record<JourneyEventKindB42, SourceCompatibilityRule>);

export interface JourneyEventContract extends NonAuthorityMarker {
  readonly eventId: string;
  readonly eventKind: JourneyEventKindB42;
  readonly significance: SignificanceClassification;
  readonly sourceKind: SourceKind;
  readonly sourceReference: string;
  readonly occurredAt: string;
  readonly recordedAt: string;
}

export const isCompatibleSource = (eventKind: JourneyEventKindB42, sourceKind: SourceKind): boolean => SOURCE_COMPATIBILITY[eventKind].includes(sourceKind);
