import { PERMISSION_IDS, ROLE_CATALOG } from "./catalog";
import { CURRENT_PERMISSION_CATALOG_VERSION, CURRENT_POLICY_VERSION, CURRENT_ROLE_VERSION, type HouseholdIdentityContext, type PermissionCatalogVersion, type PermissionId, type PolicyVersion, type PresentationIdentity, type ResourceClassification, type RequestPurpose, type RoleVersion, validateIdentity } from "./model";

export interface AuthorizationInput {
  identity?: HouseholdIdentityContext; requestedPermission?: string; assignedPermissions?: PermissionId[]; targetResourceOwner?: string; targetHouseholdId?: string; resourceClassification?: ResourceClassification; purpose?: RequestPurpose; policyVersion?: PolicyVersion; roleVersion?: RoleVersion; permissionCatalogVersion?: PermissionCatalogVersion; currentTime?: string; sessionValidity?: "valid" | "invalid" | "missing"; authenticationAssurance?: "sufficient" | "insufficient" | "missing"; auditAvailable?: boolean; technicalInformationRequest?: boolean; characterPresentationIdentity?: PresentationIdentity; explicitHistoricalIntent?: boolean;
}
export interface AuthorizationDecision { allowed: boolean; decisionCode: string; title: string; explanation: string; safeNextAction: string; technicalReason: string; policyVersion?: PolicyVersion; roleVersion?: RoleVersion; permissionCatalogVersion?: PermissionCatalogVersion; auditRequired: boolean; }
const deny = (code: string, explanation: string, next = "Check your account access or ask the Primary Owner.", input?: AuthorizationInput): AuthorizationDecision => ({ allowed: false, decisionCode: code, title: "You do not have permission to view this information", explanation, safeNextAction: next, technicalReason: code, policyVersion: input?.policyVersion, roleVersion: input?.roleVersion, permissionCatalogVersion: input?.permissionCatalogVersion, auditRequired: false });
export function evaluateAuthorization(input: AuthorizationInput): AuthorizationDecision {
  if (!input.identity || !input.currentTime) return deny("MALFORMED_IDENTITY_INPUT", "Your identity information is incomplete.", "Verify your identity and try again.", input);
  const identity = validateIdentity(input.identity, input.currentTime);
  if (!identity.valid) return deny(identity.technicalReason, identity.reason, "Verify your account and membership, then try again.", input);
  if (!input.requestedPermission || !PERMISSION_IDS.has(input.requestedPermission as PermissionId)) return deny(input.requestedPermission ? "UNKNOWN_PERMISSION" : "MISSING_PERMISSION", "The requested access is not available.", undefined, input);
  const permission = input.requestedPermission as PermissionId;
  const role = ROLE_CATALOG[input.identity.membership.roleId];
  if (!role || input.roleVersion !== CURRENT_ROLE_VERSION) return deny("STALE_ROLE_VERSION", "The role information is out of date.", "Refresh your access information and try again.", input);
  if (input.policyVersion !== CURRENT_POLICY_VERSION) return deny("STALE_POLICY_VERSION", "The access policy is out of date.", "Refresh your access information and try again.", input);
  if (input.permissionCatalogVersion !== CURRENT_PERMISSION_CATALOG_VERSION) return deny("STALE_PERMISSION_CATALOG_VERSION", "The permission information is out of date.", "Refresh your access information and try again.", input);
  if (input.sessionValidity !== "valid") return deny(input.sessionValidity === "missing" ? "MISSING_SESSION_VALIDITY" : "INVALID_SESSION", "Your session cannot be verified.", "Verify your identity and try again.", input);
  if (input.authenticationAssurance !== "sufficient") return deny(input.authenticationAssurance === "missing" ? "MISSING_AUTHENTICATION_ASSURANCE" : "INSUFFICIENT_AUTHENTICATION_ASSURANCE", "Please verify your identity to continue.", "Verify your identity, then try again.", input);
  if (!input.resourceClassification || !["profile", "private", "shared_household", "project_basic", "project_detailed", "technical", "owner_protected"].includes(input.resourceClassification)) return deny("UNSUPPORTED_CLASSIFICATION", "This information type cannot be verified.", undefined, input);
  if (!input.purpose || !["self_service", "household_support", "project_information", "technical_review", "owner_oversight"].includes(input.purpose)) return deny("UNSUPPORTED_PURPOSE", "The purpose of this request cannot be verified.", undefined, input);
  if (input.targetHouseholdId !== input.identity.householdId) return deny("HOUSEHOLD_MISMATCH", "This information belongs to another household.", undefined, input);
  if (input.targetResourceOwner && input.targetResourceOwner !== input.identity.account.accountId && input.resourceClassification === "private") return deny("CROSS_ACCOUNT_PRIVATE_RESOURCE", "Private information belongs to another account.", undefined, input);
  if (permission === "DETAILED_PROJECT_JOURNEY_ACCESS" && (input.identity.account.accountId !== "account_rahul_canonical" || !input.explicitHistoricalIntent)) return deny(input.explicitHistoricalIntent ? "OWNER_ONLY_REQUEST" : "EXPLICIT_HISTORICAL_INTENT_REQUIRED", "Detailed Project History is available only to the Primary Owner after an explicit request.", undefined, input);
  if (permission === "BASIC_PROJECT_INFORMATION_ACCESS" && input.resourceClassification === "project_detailed") return deny("BASIC_PERMISSION_CANNOT_ACCESS_DETAILED_HISTORY", "Project Overview does not include Detailed Project History.", undefined, input);
  if (permission === "DETAILED_PROJECT_JOURNEY_ACCESS" && input.resourceClassification !== "project_detailed") return deny("CLASSIFICATION_MISMATCH", "The requested permission does not match this information.", undefined, input);
  if (input.technicalInformationRequest && (permission !== "TECHNICAL_INFORMATION_ACCESS" || !role.technicalInformationEligible)) return deny("TECHNICAL_INFORMATION_NOT_AUTHORIZED", "Technical Information is not available for this account.", undefined, input);
  if (role.prohibitedPermissions.includes(permission) || !role.allowedPermissions.includes(permission) || !(input.assignedPermissions ?? []).includes(permission)) return deny("PROHIBITED_OR_MISSING_PERMISSION", "This account does not have the requested permission.", undefined, input);
  const auditRequired = ["PROTECTED_OWNER_INSPECTION", "ROLE_ASSIGNMENT", "PERMISSION_ASSIGNMENT", "AUDIT_METADATA_ACCESS"].includes(permission);
  if (auditRequired && input.auditAvailable !== true) return { ...deny("AUDIT_UNAVAILABLE", "This protected action cannot continue because its audit record is unavailable.", "Restore audit availability and try again.", input), auditRequired: true };
  return { allowed: true, decisionCode: "ALLOW_EXPLICIT_POLICY_GRANT", title: "Access permitted", explanation: "Your verified account has this permission for the requested purpose.", safeNextAction: "Continue with the requested information.", technicalReason: "EXPLICIT_POLICY_GRANT", policyVersion: input.policyVersion, roleVersion: input.roleVersion, permissionCatalogVersion: input.permissionCatalogVersion, auditRequired };
}
