import { appendFile, mkdir, readFile, rename, stat, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import { digest, type ProviderClassification } from "./contracts";
export interface Checkpoint { workflowId: string; workflowVersion: string; repository: string; currentState: string; stepId: string; scopeHash: string; approvalPackageDigest: string; inputDigest: string; idempotencyKey: string; attempt: number; startedAt: string; previousCheckpointDigest: string; outputDigest?: string; providerResultClassification?: ProviderClassification; resourceId?: string; resourceUrl?: string; completedAt?: string; evidenceReferences?: string[]; nextPermittedState?: string; digest: string; }
export interface CheckpointStore { append(checkpoint: Omit<Checkpoint, "digest">): Promise<Checkpoint>; list(workflowId: string): Promise<Checkpoint[]>; }
export class InMemoryCheckpointStore implements CheckpointStore { private readonly records: Checkpoint[] = []; async append(value: Omit<Checkpoint, "digest">) { const checkpoint = { ...value, digest: digest(value) }; this.records.push(checkpoint); return checkpoint; } async list(workflowId: string) { return this.records.filter((record) => record.workflowId === workflowId); } }
export class FileCheckpointStore implements CheckpointStore { constructor(private readonly path: string) {} async append(value: Omit<Checkpoint, "digest">) { await mkdir(dirname(this.path), { recursive: true }); const checkpoint = { ...value, digest: digest(value) }; const tmp = `${this.path}.${process.pid}.${Date.now()}.tmp`; await writeFile(tmp, `${JSON.stringify(checkpoint)}\n`, "utf8"); await rename(tmp, this.path); return checkpoint; } async list(workflowId: string) { try { const file = await stat(this.path); if (!file.size) return []; const content = await readFile(this.path, "utf8"); return content.trim().split("\n").filter(Boolean).map((line) => JSON.parse(line) as Checkpoint).filter((record) => record.workflowId === workflowId); } catch { return []; } } }
export function verifyCheckpointChain(records: Checkpoint[], expected: { workflowId: string; repository: string; workflowVersion: string; scopeHash: string }): void { let previous = ""; for (const record of records) { const { digest: actual, ...unsigned } = record; if (record.workflowId !== expected.workflowId || record.repository !== expected.repository || record.workflowVersion !== expected.workflowVersion || record.scopeHash !== expected.scopeHash || record.previousCheckpointDigest !== previous || digest(unsigned) !== actual) throw new Error("Corrupt or mismatched checkpoint chain."); previous = record.digest; } }
export function validateCheckpoint(record: Checkpoint, expected: { workflowId: string; repository: string; workflowVersion: string; scopeHash: string }): void { if (record.workflowId !== expected.workflowId) throw new Error("Checkpoint workflow mismatch."); if (record.repository !== expected.repository) throw new Error("Checkpoint repository mismatch."); if (record.workflowVersion !== expected.workflowVersion) throw new Error("Checkpoint workflow version mismatch."); if (record.scopeHash !== expected.scopeHash) throw new Error("Checkpoint scope mismatch."); const recalculated = digest(({ ...record, digest: undefined })); if (recalculated !== record.digest) throw new Error("Checkpoint hash mismatch."); }
