import { describe, expect, it } from "vitest";
import { isDistinctCharacter, canonicalIdentityAcrossVariants, projectForVariant, coversAllEightStates, idleMotionIsOptionalAndNonSemantic, transitionIntentNotOperationalEvent, approvalPriorityWithoutGranting, privacyPriorityOverAppearance, recoveringWithoutClaimingCompletion, reducedMotionRemovesNonessentialMotion, highContrastPreservesStateDistinction, textOnlyFallbackWhenUnavailable } from "../src/requirement-coverage.js";
import { CHARACTERS, renderIntent } from "../src/index.js";
describe("VP-RENDERER requirement rows", () => {
  it("VP-RENDERER-01-POS-001: ONYX is distinct", () => { expect(isDistinctCharacter("ONYX")).toBe(true); });
  it("VP-RENDERER-01-NEG-001: unknown character not distinct", () => { expect(isDistinctCharacter("" as any)).toBe(false); });
  it("VP-RENDERER-02-POS-001: NOVA is distinct", () => { expect(isDistinctCharacter("NOVA")).toBe(true); });
  it("VP-RENDERER-02-NEG-001: duplicate check ensures uniqueness", () => { expect(CHARACTERS.filter(c => c === "ONYX").length).toBe(1); });
  it("VP-RENDERER-03-POS-001: canonical identity across variants", () => { expect(canonicalIdentityAcrossVariants("ONYX", "IDLE")).toBe(true); });
  it("VP-RENDERER-03-NEG-001: identity invariant across devices", () => { const d = projectForVariant("ONYX", "IDLE", "DESKTOP"); const t = projectForVariant("ONYX", "IDLE", "TV"); expect(d.character).toEqual(t.character); });
  it("VP-RENDERER-04-POS-001: adapter bound", () => { expect(renderIntent("ONYX", "IDLE")).toBeDefined(); });
  it("VP-RENDERER-04-NEG-001: no external binding", () => { const a = projectForVariant("ONYX", "IDLE", "DESKTOP"); expect(a.provider).toBe("abstract"); });
  it("VP-RENDERER-05-POS-001: covers eight states", () => { expect(coversAllEightStates("ONYX")).toBe(true); });
  it("VP-RENDERER-05-NEG-001: eight unique state representations", () => { const s = new Set(["IDLE", "LISTENING", "UNDERSTANDING", "THINKING", "SPEAKING", "APPROVAL_REQUIRED", "PRIVACY_RESTRICTED", "RECOVERING"].map((st: any) => renderIntent("ONYX", st).state)); expect(s.size).toBe(8); });
  it("VP-RENDERER-06-POS-001: IDLE motion non-semantic", () => { expect(idleMotionIsOptionalAndNonSemantic("ONYX")).toBe(true); });
  it("VP-RENDERER-06-NEG-001: IDLE state invariant to motion", () => { const w = renderIntent("ONYX", "IDLE"); const r = renderIntent("ONYX", "IDLE", { reducedMotion: true }); expect(w.state).toEqual(r.state); });
  it("VP-RENDERER-07-POS-001: transition non-operational", () => { const i = transitionIntentNotOperationalEvent("IDLE", "LISTENING"); expect(i.operational).toBe(false); });
  it("VP-RENDERER-07-NEG-001: transition immutable", () => { const i = transitionIntentNotOperationalEvent("IDLE", "LISTENING"); expect(Object.isFrozen(i)).toBe(true); });
  it("VP-RENDERER-08-POS-001: approval without grant", () => { expect(approvalPriorityWithoutGranting("ONYX")).toBe(true); });
  it("VP-RENDERER-08-NEG-001: no fallback for approval", () => { const i = renderIntent("ONYX", "APPROVAL_REQUIRED"); expect(i.fallback).toBe(false); });
  it("VP-RENDERER-09-POS-001: privacy minimizes", () => { expect(privacyPriorityOverAppearance("ONYX")).toBe(true); });
  it("VP-RENDERER-09-NEG-001: expression minimized", () => { const i = renderIntent("ONYX", "PRIVACY_RESTRICTED"); expect(i.expression).toBe("minimized"); });
  it("VP-RENDERER-10-POS-001: recovery fallback", () => { expect(recoveringWithoutClaimingCompletion("ONYX")).toBe(true); });
  it("VP-RENDERER-10-NEG-001: no recovery completion claim", () => { const i = renderIntent("ONYX", "RECOVERING"); expect("recoveryComplete" in i).toBe(false); });
  it("VP-RENDERER-11-POS-001: reduced motion removes motion", () => { expect(reducedMotionRemovesNonessentialMotion("ONYX", "SPEAKING")).toBe(true); });
  it("VP-RENDERER-11-NEG-001: motion reduced uniformly", () => { const s = ["IDLE", "LISTENING", "UNDERSTANDING", "THINKING", "SPEAKING", "APPROVAL_REQUIRED", "PRIVACY_RESTRICTED", "RECOVERING"] as const; const r = s.every((st) => renderIntent("ONYX", st, { reducedMotion: true }).motion === "reduced"); expect(r).toBe(true); });
    it("VP-RENDERER-12-POS-001: high contrast distinguishes", () => { 
      const s = ["IDLE", "LISTENING", "UNDERSTANDING", "THINKING", "SPEAKING", "APPROVAL_REQUIRED", "PRIVACY_RESTRICTED", "RECOVERING"] as const; 
      const allHC = s.every((st) => renderIntent("ONYX", st, { highContrast: true }).contrast === "high"); 
      expect(allHC).toBe(true); 
    });
  it("VP-RENDERER-12-NEG-001: high contrast preserves minimum distinctions", () => { const s = ["IDLE", "LISTENING", "UNDERSTANDING", "THINKING", "SPEAKING", "APPROVAL_REQUIRED", "PRIVACY_RESTRICTED", "RECOVERING"] as const; const e = new Set(s.map((st) => renderIntent("ONYX", st, { highContrast: true }).expression)); expect(e.size).toBeGreaterThan(1); });
  it("VP-RENDERER-13-POS-001: unavailable fallback", () => { expect(textOnlyFallbackWhenUnavailable("UNKNOWN" as any, "IDLE")).toBe(true); });
  it("VP-RENDERER-13-NEG-001: available no fallback", () => { const a = renderIntent("ONYX", "IDLE"); expect(a.fallback).toBe(false); });
  it("VP-RENDERER-14-POS-001: TV projection", () => { const tv = projectForVariant("ONYX", "SPEAKING", "TV"); expect(tv.variant).toBe("TV"); expect(tv.character).toBe("ONYX"); });
  it("VP-RENDERER-14-NEG-001: TV semantics match", () => { const d = projectForVariant("ONYX", "SPEAKING", "DESKTOP"); const t = projectForVariant("ONYX", "SPEAKING", "TV"); expect(d.state).toEqual(t.state); });
  it("VP-RENDERER-15-POS-001: mobile adapts", () => { const m = projectForVariant("ONYX", "SPEAKING", "MOBILE"); expect(m.variant).toBe("MOBILE"); });
  it("VP-RENDERER-15-NEG-001: constrained reduces motion", () => { const c = projectForVariant("NOVA", "IDLE", "CONSTRAINED"); expect(c.motion).toBe("reduced"); });
});
