import { describe, expect, it } from "vitest";
import { generateKeyPairSync, sign } from "node:crypto";
import { AUTHORITY_ACCEPTANCE_REGISTRY, COMPLETE_ACCEPTANCE_REGISTRY, FixedWindowRateLimiter, InMemoryAccountRecordRepository, InMemoryAuditSink, SYNTHETIC_AUDIENCE, SYNTHETIC_ISSUER, SYNTHETIC_KEYS, SyntheticAuthenticationProvider, SyntheticHmacTokenVerifier, SyntheticRs256JwksVerifier, protectRequest, sameAccountPolicy, signSyntheticToken, syntheticClaims, validateCompleteAcceptanceRegistry, validateEntraConfiguration } from "../src";
import type { AuthenticatedRequestContext, AuthenticationProvider } from "../src";

const now = 1_700_000_100;
const verifier = () => new SyntheticHmacTokenVerifier(SYNTHETIC_ISSUER, SYNTHETIC_AUDIENCE, SYNTHETIC_KEYS);
const provider = () => new SyntheticAuthenticationProvider(verifier(), "test-scope-salt");
const request = (token: string, overrides: Partial<{ method: string; contentType: string; body: string; targetScope: string; requestId: string; governed: boolean }> = {}) => ({ method: "POST", contentType: "application/json", body: "{}", authorization: `Bearer ${token}`, action: "character-preference", governed: false, ...overrides });
const base64url = (value: string) => Buffer.from(value).toString("base64url");
const keyPair = generateKeyPairSync("rsa", { modulusLength: 2048 });
const jwk = keyPair.publicKey.export({ format: "jwk" }) as { kty: "RSA"; n: string; e: string };
const rsToken = (claims = syntheticClaims(), header: Record<string, string> = { alg: "RS256", kid: "current" }, signingKey = keyPair.privateKey) => { const encodedHeader = base64url(JSON.stringify(header)); const encodedClaims = base64url(JSON.stringify(claims)); return `${encodedHeader}.${encodedClaims}.${sign("RSA-SHA256", Buffer.from(`${encodedHeader}.${encodedClaims}`), signingKey).toString("base64url")}`; };
const rsVerifier = (keys: Record<string, object> = { current: { ...jwk, kid: "current", alg: "RS256", use: "sig" }, rotated: { ...jwk, kid: "rotated", alg: "RS256", use: "sig" } }) => new SyntheticRs256JwksVerifier({ issuer: SYNTHETIC_ISSUER, audiences: [SYNTHETIC_AUDIENCE], resolver: { resolve: (kid) => keys[kid] as never }, clockSkewSeconds: 30, maxTokenBytes: 4096 });

describe("synthetic authentication and server authority foundation", () => {
  it("accepts valid tokens and derives opaque distinct account scopes", () => {
    const activeProvider = provider(); const valid = activeProvider.verifyProof(signSyntheticToken(), now); expect(valid.code).toBe("AUTHENTICATED"); expect(valid.proof).toBeDefined(); if (!valid.proof) throw new Error("missing synthetic proof");
    const accountA = activeProvider.deriveAuthenticatedContext(valid.proof, "request_a"); const proofB = activeProvider.verifyProof(signSyntheticToken(syntheticClaims({ sub: "synthetic-account-b" })), now); if (!proofB.proof) throw new Error("missing synthetic proof"); const accountB = activeProvider.deriveAuthenticatedContext(proofB.proof, "request_b");
    expect(accountA.opaqueAccountScope).not.toContain("synthetic-account-a"); expect(accountA.opaqueAccountScope).not.toBe(accountB.opaqueAccountScope);
  });
  it.each([["invalid signature", signSyntheticToken(undefined, "current", "HS256", "wrong-key"), "TOKEN_SIGNATURE_INVALID"], ["wrong issuer", signSyntheticToken(syntheticClaims({ iss: "https://wrong.invalid" })), "TOKEN_ISSUER_INVALID"], ["wrong audience", signSyntheticToken(syntheticClaims({ aud: "wrong" })), "TOKEN_AUDIENCE_INVALID"], ["expired", signSyntheticToken(syntheticClaims({ exp: now - 31 })), "TOKEN_EXPIRED"], ["not yet valid", signSyntheticToken(syntheticClaims({ nbf: now + 31 })), "TOKEN_NOT_YET_VALID"], ["unsupported algorithm", signSyntheticToken(undefined, "current", "none"), "TOKEN_MALFORMED"], ["unknown key", signSyntheticToken(undefined, "unknown"), "TOKEN_SIGNATURE_INVALID"], ["malformed", "not.a.token", "TOKEN_MALFORMED"]] as const)("rejects %s", (_name, token, code) => expect(verifier().verify(token, now).code).toBe(code));
  it("fails closed for cross-account, policy, audit, replay, and request bounds", () => {
    const activeProvider = provider(); const token = signSyntheticToken(); const verified = activeProvider.verifyProof(token, now); if (!verified.proof) throw new Error("missing synthetic proof"); const context = activeProvider.deriveAuthenticatedContext(verified.proof, "request_match");
    expect(protectRequest(request(token, { targetScope: "account-scope_other" }), activeProvider, sameAccountPolicy(), new InMemoryAuditSink(), new FixedWindowRateLimiter(), now).code).toBe("ACCOUNT_MISMATCH");
    expect(protectRequest(request(token, { targetScope: context.opaqueAccountScope }), activeProvider, sameAccountPolicy(false), new InMemoryAuditSink(), new FixedWindowRateLimiter(), now).code).toBe("POLICY_UNAVAILABLE");
    expect(protectRequest(request(token, { targetScope: context.opaqueAccountScope, governed: true }), activeProvider, sameAccountPolicy(), new InMemoryAuditSink(false), new FixedWindowRateLimiter(), now).code).toBe("AUDIT_UNAVAILABLE");
    const limiter = new FixedWindowRateLimiter(); expect(protectRequest(request(token, { targetScope: context.opaqueAccountScope, requestId: "request_replay" }), activeProvider, sameAccountPolicy(), new InMemoryAuditSink(), limiter, now).code).toBe("AUTHENTICATED"); expect(protectRequest(request(token, { targetScope: context.opaqueAccountScope, requestId: "request_replay" }), activeProvider, sameAccountPolicy(), new InMemoryAuditSink(), limiter, now).code).toBe("RATE_LIMITED");
    expect(protectRequest(request(token, { targetScope: context.opaqueAccountScope, body: "x".repeat(4097) }), activeProvider, sameAccountPolicy(), new InMemoryAuditSink(), new FixedWindowRateLimiter(), now).code).toBe("INVALID_REQUEST");
  });
  it("rejects revoked sessions and preserves secret-safe audit evidence", () => {
    const activeProvider = provider(); const token = signSyntheticToken(); activeProvider.invalidateSessionProjection("synthetic-session-a"); expect(activeProvider.verifyProof(token, now).code).toBe("SESSION_REVOKED");
    const deviceProvider = provider(); deviceProvider.invalidateDeviceProjection("synthetic-device-a"); expect(deviceProvider.verifyProof(token, now).code).toBe("DEVICE_REVOKED");
    const repository = new InMemoryAccountRecordRepository(); expect(repository.reserveIdempotency("operation-1")).toBe(true); expect(repository.reserveIdempotency("operation-1")).toBe(false);
  });
  it("fails closed for malformed Entra configuration and redacts raw identity from audits", () => {
    expect(validateEntraConfiguration({ issuer: "", audience: "", jwksUri: "", allowedAlgorithms: [], clockSkewSeconds: -1, opaqueScopeSalt: "short", claimMappingVersion: "ENTRA_EXTERNAL_ID_V1" })).toBe(false);
    const activeProvider = provider(); const token = signSyntheticToken(); const verified = activeProvider.verifyProof(token, now); if (!verified.proof) throw new Error("missing synthetic proof"); const context = activeProvider.deriveAuthenticatedContext(verified.proof, "request_audit"); const audit = new InMemoryAuditSink();
    expect(protectRequest(request(token, { targetScope: context.opaqueAccountScope, requestId: "request_audit" }), activeProvider, sameAccountPolicy(), audit, new FixedWindowRateLimiter(), now).code).toBe("AUTHENTICATED"); expect(JSON.stringify(audit.entries)).not.toContain("synthetic-account-a"); expect(AUTHORITY_ACCEPTANCE_REGISTRY.find((entry) => entry.id === "DEPLOY-001")?.implementationState).toBe("pending");
  });
  const rsCases: Array<[string, string, string, Record<string, object> | undefined]> = [["RS256-001", rsToken(), "AUTHENTICATED", undefined], ["RS256-002", `${rsToken()}x`, "TOKEN_SIGNATURE_INVALID", undefined], ["RS256-003", rsToken(syntheticClaims({ iss: "https://wrong.invalid" })), "TOKEN_ISSUER_INVALID", undefined], ["RS256-004", rsToken(syntheticClaims({ aud: "wrong" })), "TOKEN_AUDIENCE_INVALID", undefined], ["RS256-005", rsToken(syntheticClaims({ exp: now - 31 })), "TOKEN_EXPIRED", undefined], ["RS256-006", rsToken(syntheticClaims({ nbf: now + 31 })), "TOKEN_NOT_YET_VALID", undefined], ["RS256-007", "bad.token", "TOKEN_MALFORMED", undefined], ["RS256-008", rsToken(undefined, { alg: "HS256", kid: "current" }), "TOKEN_MALFORMED", undefined], ["RS256-009", rsToken(undefined, { alg: "none", kid: "current" }), "TOKEN_MALFORMED", undefined], ["RS256-010", signSyntheticToken(), "TOKEN_MALFORMED", undefined], ["RS256-011", rsToken(undefined, { alg: "RS256" }), "TOKEN_MALFORMED", undefined], ["RS256-012", rsToken(undefined, { alg: "RS256", kid: "unknown" }), "TOKEN_SIGNATURE_INVALID", undefined], ["RS256-013", rsToken(), "TOKEN_SIGNATURE_INVALID", { current: { kty: "RSA", kid: "current", alg: "RS256", use: "sig" } }], ["RS256-014", rsToken(), "TOKEN_SIGNATURE_INVALID", { current: { kty: "EC", kid: "current", alg: "RS256", use: "sig", n: "x", e: "AQAB" } }], ["RS256-015", rsToken(undefined, { alg: "RS256", kid: "rotated" }), "AUTHENTICATED", undefined], ["RS256-016", rsToken(undefined, { alg: "RS256", kid: "stale" }), "TOKEN_SIGNATURE_INVALID", undefined], ["RS256-017", "x".repeat(4097), "TOKEN_MALFORMED", undefined], ["RS256-018", rsToken(syntheticClaims({ sub: undefined })), "UNAUTHENTICATED", undefined]];
  it.each(rsCases)("%s verifies offline", (_id, token, expected, keys) => expect(rsVerifier(keys).verify(token, now).code).toBe(expected));
  it("RS256-019 and RS256-020 preserve post-verification scope and secret-safe errors", () => { const result = rsVerifier().verify(rsToken(), now); expect(result.proof?.claims.sub).toBe("synthetic-account-a"); expect(JSON.stringify(rsVerifier().verify("bad.token", now))).not.toContain("synthetic-account-a"); });
  it("materializes and validates the exact complete acceptance registry", () => { const first = COMPLETE_ACCEPTANCE_REGISTRY[0]; if (!first) throw new Error("missing registry row"); expect(COMPLETE_ACCEPTANCE_REGISTRY).toHaveLength(240); expect(validateCompleteAcceptanceRegistry(COMPLETE_ACCEPTANCE_REGISTRY)).toEqual([]); expect(validateCompleteAcceptanceRegistry([...COMPLETE_ACCEPTANCE_REGISTRY, first])).toContain("ROW_COUNT"); expect(validateCompleteAcceptanceRegistry([{ ...first, id: "EXTRA-001" }, ...COMPLETE_ACCEPTANCE_REGISTRY.slice(1)])).toContain("EXTRA_EXTRA-001"); });
  it("exposes device invalidation through the provider-neutral interface", () => { const interfaceTypedProvider: AuthenticationProvider = provider(); interfaceTypedProvider.invalidateDeviceProjection("synthetic-device-a"); expect(interfaceTypedProvider.verifyProof(signSyntheticToken(), now).code).toBe("DEVICE_REVOKED"); });
  it("isolates rate limits per server-derived account scope and bounds scope buckets", () => { const activeProvider = provider(); const accountA = activeProvider.verifyProof(signSyntheticToken(), now); const accountB = activeProvider.verifyProof(signSyntheticToken(syntheticClaims({ sub: "synthetic-account-b" })), now); if (!accountA.proof || !accountB.proof) throw new Error("missing synthetic proof"); const contextA = activeProvider.deriveAuthenticatedContext(accountA.proof, "request_a"); const contextB = activeProvider.deriveAuthenticatedContext(accountB.proof, "request_b"); let clock = 0; const limiter = new FixedWindowRateLimiter(1, 1, 60, () => clock); expect(limiter.reserve(contextA, "request_a")).toBe(true); expect(limiter.reserve(contextA, "request_a")).toBe(false); expect(limiter.reserve(contextB, "request_b")).toBe(true); clock = 60; expect(limiter.reserve(contextA, "request_rollover")).toBe(true); const malformedContext = { ...contextA, opaqueAccountScope: "invalid" } as unknown as AuthenticatedRequestContext; expect(limiter.reserve(malformedContext, "request_invalid")).toBe(false); });
});