import { describe, expect, it } from "vitest";
import { concurrentImmutableReadersCompatible, evaluateCheckpointCas, evaluateCheckpointCreate, evaluateSchemaCompatibility, projectSafeResume, type SafeResumeInput, type SchedulerCheckpointCreateRequest } from "../src";
const hash = "sha256:" + "a".repeat(64);
const checkpoint = (overrides: Partial<SchedulerCheckpointCreateRequest> = {}): SchedulerCheckpointCreateRequest => ({ checkpointDecisionId: "1a9:checkpoint:decision", schedulerRunId: "1a9:run:1", schedulerTaskReferenceId: "1a9:task-ref:1", taskId: "task-1", workflowId: "workflow-1", runtimeId: "runtime-1", runtimeSessionId: "session-1", agentId: "agent-1", leaseId: "lease-1", leaseGeneration: 1, lockIds: ["lock-1"], currentCheckpointId: "", currentCheckpointVersion: 0, requestedCheckpointId: "checkpoint-1", requestedCheckpointVersion: 1, stateHash: hash, payloadReference: "ref:payload-1", payloadDigest: hash, schemaVersion: "1.0.0", resumePoint: "step-1", scopeHash: "scope-1", approvalId: "approval-1", permissionProfileId: "permission-1", memoryAccessProfileId: "memory-1", connectorScopeIds: ["connector-1"], evidenceArtifactIds: ["evidence-1"], requestedAt: "2026-08-21T00:00:00.000Z", contractVersion: "1.0.0", ...overrides });
const resume = (overrides: Partial<SafeResumeInput> = {}): SafeResumeInput => ({ safeResumeDecisionId: "1a9:resume:1", schedulerTaskReferenceId: "1a9:task-ref:1", taskId: "task-1", workflowId: "workflow-1", runtimeId: "runtime-1", runtimeSessionId: "session-1", checkpointId: "checkpoint-1", checkpointVersion: 1, stateHash: hash, payloadReference: "ref:payload-1", payloadDigest: hash, schemaVersion: "1.0.0", resumePoint: "step-1", leaseId: "lease-1", leaseGeneration: 1, lockIds: ["lock-1"], approvalId: "approval-1", scopeHash: "scope-1", permissionProfileId: "permission-1", memoryAccessProfileId: "memory-1", connectorScopeIds: ["connector-1"], providerOutcome: "KNOWN_NONE", remoteSideEffectStatus: "NONE", idempotencyKey: "idempotency-1", riskClass: "R1", promotionOnly: false, stateHashValid: true, payloadDigestValid: true, schemaCompatibility: "EXACT_MATCH", lineageValid: true, leaseValid: true, lockValid: true, scopeValid: true, approvalValid: true, permissionValid: true, memoryScopeValid: true, connectorScopeValid: true, resumePointValid: true, evidenceArtifactIds: ["evidence-1"], evaluatedAt: "2026-08-21T00:00:00.000Z", ...overrides });
describe("Wave 2D checkpoint projections", () => {
  it("accepts initial and exact next versions as projections", () => { expect(evaluateCheckpointCreate(checkpoint()).decision).toBe("CREATE_ELIGIBLE_AS_PROJECTION"); expect(evaluateCheckpointCreate(checkpoint({ currentCheckpointId: "checkpoint-1", currentCheckpointVersion: 1, requestedCheckpointId: "checkpoint-2", requestedCheckpointVersion: 2 }), 1).decision).toBe("CAS_UPDATE_ELIGIBLE_AS_PROJECTION"); });
  it("rejects stale and future CAS writers without retrying", () => { const canonical = checkpoint({ currentCheckpointId: "checkpoint-1", currentCheckpointVersion: 1 }); expect(evaluateCheckpointCas(checkpoint({ currentCheckpointId: "checkpoint-1", currentCheckpointVersion: 0 }), canonical).decision).toBe("DENIED_STALE_WRITER"); expect(evaluateCheckpointCreate(checkpoint({ currentCheckpointId: "checkpoint-1", currentCheckpointVersion: 1, requestedCheckpointVersion: 3 }), 1).decision).toBe("DENIED_VERSION_GAP"); });
  it("rejects corrupt references and unsupported or migrating schemas", () => { expect(evaluateCheckpointCreate(checkpoint({ stateHash: "bad" })).stateHashValid).toBe(false); expect(evaluateSchemaCompatibility("1.0.0", "3.0.0")).toBe("UNSUPPORTED"); expect(evaluateSchemaCompatibility("1.0.0", "2.0.0")).toBe("MIGRATION_REQUIRED"); });
  it("blocks unsafe resume and permits immutable compatible readers", () => { expect(projectSafeResume(resume()).automaticResumePermitted).toBe(true); expect(projectSafeResume(resume({ providerOutcome: "UNCERTAIN" })).automaticResumePermitted).toBe(false); expect(projectSafeResume(resume({ schemaCompatibility: "MIGRATION_REQUIRED" })).decision).toBe("MIGRATION_REQUIRED"); expect(concurrentImmutableReadersCompatible(resume(), resume())).toBe(true); expect(concurrentImmutableReadersCompatible(resume(), resume({ payloadDigest: "sha256:" + "b".repeat(64) }))).toBe(false); });
});