import { describe, expect, it } from "vitest";
import { COMPATIBLE_GOVERNED_CONTRACTS_VERSION, COMPATIBLE_RUNTIME_CONTRACT_VERSION, COMPATIBLE_UI_CONTRACT_VERSION_FROM_PREDECESSOR, COMPATIBLE_WORKFLOW_CONTRACT_VERSION, PHASE1A9_SCHEDULER_CONTRACT_VERSION, WORKFLOW_STATES } from "../src";
describe("Phase 1A.9 compatibility", () => {
  it("binds every predecessor contract at 1.0.0 and reuses all workflow states", () => {
    expect([PHASE1A9_SCHEDULER_CONTRACT_VERSION, COMPATIBLE_WORKFLOW_CONTRACT_VERSION, COMPATIBLE_RUNTIME_CONTRACT_VERSION, COMPATIBLE_UI_CONTRACT_VERSION_FROM_PREDECESSOR, COMPATIBLE_GOVERNED_CONTRACTS_VERSION]).toEqual(["1.0.0", "1.0.0", "1.0.0", "1.0.0", "1.0.0"]);
    expect(WORKFLOW_STATES).toHaveLength(32);
  });
});