import { describe, expect, it } from "vitest";
import { canonicalizeResourceKeys, evaluateDeadlockPrevention, evaluateLockAcquisition, evaluateLockRelease, evaluateLockRenewal, projectLostOwnerReconciliation, validateLockGeneration, type ActiveSchedulerLock, type SchedulerLockRequest } from "../src";
const request = (overrides: Partial<SchedulerLockRequest> = {}): SchedulerLockRequest => ({ lockDecisionId: "1a9:lock:decision", schedulerRunId: "1a9:run:1", schedulerTaskReferenceId: "1a9:task-ref:1", taskId: "task-1", workflowId: "workflow-1", runtimeId: "runtime-1", runtimeSessionId: "session-1", agentId: "agent-1", leaseId: "lease-1", leaseGeneration: 1, resourceKeys: ["db:users"], requestedLockMode: "READ_SHARED", requestedLockGeneration: 1, requestedAt: "2026-08-21T00:00:00.000Z", requestedExpiry: "2026-08-21T00:05:00.000Z", scopeHash: "sha256:scope", permissionProfileId: "permission-1", memoryAccessProfileId: "memory-1", connectorScopeIds: ["connector-1"], approvalId: "approval-1", checkpointDigest: "sha256:checkpoint", parallelSafetyClass: "READ_ONLY_PARALLEL_SAFE", riskClass: "R1", promotionRequired: false, evidenceArtifactIds: ["evidence-1"], contractVersion: "1.0.0", ...overrides });
const lock = (overrides: Partial<ActiveSchedulerLock> = {}): ActiveSchedulerLock => ({ lockId: "lock-1", taskReferenceId: "1a9:task-ref:old", taskId: "task-old", workflowId: "workflow-1", agentId: "agent-old", leaseId: "lease-old", leaseGeneration: 1, resourceKeys: ["db:users"], lockMode: "READ_SHARED", lockGeneration: 1, scopeHash: "sha256:scope", status: "HELD", expiresAt: "2026-08-21T00:05:00.000Z", ...overrides });
describe("Wave 2D lock projections", () => {
  it("reuses authoritative modes and permits shared reads", () => expect(evaluateLockAcquisition(request(), [lock()]).decision).toBe("SHARED_READ_COMPATIBLE"));
  it("blocks read-write and same-resource write conflicts", () => { expect(evaluateLockAcquisition(request({ requestedLockMode: "WRITE_EXCLUSIVE", parallelSafetyClass: "SEQUENTIAL_CHECKPOINT_REQUIRED" }), [lock()]).decision).toBe("DENIED_CONFLICT"); expect(evaluateLockAcquisition(request(), [lock({ lockMode: "WRITE_EXCLUSIVE" })]).decision).toBe("WAIT_REQUIRED"); });
  it("requires proof for disjoint writes and canonicalizes inverse order", () => { const first = evaluateLockAcquisition(request({ requestedLockMode: "WRITE_EXCLUSIVE", parallelSafetyClass: "SEQUENTIAL_CHECKPOINT_REQUIRED", resourceKeys: ["db:b", "db:a"] }), [lock({ resourceKeys: ["db:c"] })]); expect(first.decision).toBe("DISJOINT_WRITE_COMPATIBLE"); expect(first.canonicalResourceOrder).toEqual(["db:a", "db:b"]); expect(evaluateDeadlockPrevention([["db:a", "db:b"], ["db:a", "db:b"]])).toBe(false); });
  it("fails closed for malformed or duplicate resources", () => { expect(canonicalizeResourceKeys([]).valid).toBe(false); expect(canonicalizeResourceKeys(["db:a", "db:a"]).valid).toBe(false); expect(evaluateLockAcquisition(request({ resourceKeys: ["not a key"] })).decision).toBe("DENIED_SCOPE"); });
  it("validates generations and owner-bound renewal/release", () => { expect(validateLockGeneration(1, 1)).toBe(true); expect(validateLockGeneration(1, 3)).toBe(false); expect(evaluateLockRenewal(request({ requestedLockGeneration: 2 }), lock({ taskId: "task-1", agentId: "agent-1", leaseId: "lease-1" })).decision).toBe("ACQUISITION_ELIGIBLE_AS_PROJECTION"); expect(evaluateLockRenewal(request({ agentId: "other", requestedLockGeneration: 2 }), lock()).decision).toBe("DENIED_GENERATION"); expect(evaluateLockRelease(request({ agentId: "other" }), lock()).decision).toBe("DENIED_OWNER"); });
  it("does not blindly release a lost owner write lock", () => { const projection = projectLostOwnerReconciliation({ leaseGenerationTrusted: true, lastHeartbeatValid: false, lastCheckpointValid: true, externalEffect: "UNCERTAIN", resourceStateKnown: false, idempotencyKey: "idempotency-1", approvalValid: true, permissionValid: true, memoryScopeValid: true, connectorScopeValid: true, checkpointLineageValid: true }); expect(projection.reconciliationRequired).toBe(true); expect(projection.lockMayBeReleased).toBe(false); });
});